### ISSUE TITLE
iptables error

### ISSUE THREAD

**Issue by mrelova** [ab77/netflix-proxy#1]
Hello there - Thanks for putting this together.  I ran your script on my DigitalOcean Droplet, but get the following error:
iptables: No chain/target/match by that name.

Can you assist? 

+ sudo iptables -A INPUT -j REJECT --reject-with icmp-host-prohibited
+ sudo iptables -A FORWARD -j REJECT --reject-with icmp-host-prohibited
+ sudo iptables -A DOCKER -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables: No chain/target/match by that name.

Thanks!

**Comment by ab77** [comment]
Hi there, I am pretty sure you are deploying a standard Ubuntu droplet,
which won't have Docker installed by default and therefore the iptables
rules involving the DOCKER chain will fail.

Try deploying a Docker 1.6.2 on 14.04 from the Applications tab instead.

[image: Inline images 1]

Let me know how that goes..

-- ab1

**Comment by mrelova** [comment]
It worked beautifully!  Thanks for that clarification!

**Comment by ab77** [comment]
Great stuff!
