### ISSUE TITLE
Changing IP

### ISSUE THREAD

**Issue by dazuaz** [ab77/netflix-proxy#10]
Hello, 

Thanks a lot for sharing this, been using it for a while and works great.

My ip keeps changing every couple of days, whats the easiest way for me to update the firewall?

Thanks a lot,
Daniel

**Comment by ab77** [comment]
Please give this approach a go and let me know if it works:
[https://github.com/ab77/netflix-proxy/issues/9#issuecomment-117580338](https://github.com/ab77/netflix-proxy/issues/9#issuecomment-117580338)

If it works for you, I'll make a new Wiki page..

-- ab1

**Comment by ab77** [comment]
Sorry, forgot to add that you'll need to add `pre-up iptables-restore < /etc/iptables.rules` to your interfaces file to restore iptables rules on start-up:

    # vim /etc/network/interfaces
    ...
    auto eth0
    iface eth0 inet static
        address 46.x.x.x
        netmask 255.255.x.x
        gateway 46.x.x.x
        pre-up iptables-restore < /etc/iptables.rules
