### ISSUE TITLE
Is the authentication part REALLY working?

### ISSUE THREAD

**Issue by kyle95wm** [ab77/netflix-proxy#100]
So I'm just wondering, does it really work? Or is it just for show?

The reason I asked is, it appears that even though I de authorized my IP, I'm still able to load Netflix and other websites. I thought the whole idea was to only allow select ip's access to the custom Netflix server.

**Comment by ab77** [comment]
Works fine for me. Something is probably ignoring your Smart DNS server IP I am guessing. Try doing all your tests in a controlled browser environment.

When you deauthorize you IP and do `dig netflix.com @your-vps-ip`, you should get a different looking response to the one you get when your IP is authorised. 

-- ab1

**Comment by kyle95wm** [comment]
Alright I get this:

Kyle-iMac:.ssh kyle$ dig netflix.com @104.236.46.190
# This was when the IP was auth'd
; <<>> DiG 9.8.3-P1 <<>> netflix.com @104.236.46.190
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33093
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; QUESTION SECTION:
;netflix.com.			IN	A

;; ANSWER SECTION:
netflix.com.		86400	IN	A	104.236.46.190

;; AUTHORITY SECTION:
netflix.com.		86400	IN	NS	ns1.netflix.com.

;; ADDITIONAL SECTION:
ns1.netflix.com.	86400	IN	A	104.236.46.190

;; Query time: 40 msec
;; SERVER: 104.236.46.190#53(104.236.46.190)
;; WHEN: Sat Mar 19 17:14:31 2016
;; MSG SIZE  rcvd: 79

Kyle-iMac:.ssh kyle$ dig netflix.com @104.236.46.190
# I de-auth'd the IP and I get the below output
; <<>> DiG 9.8.3-P1 <<>> netflix.com @104.236.46.190
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2201
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;netflix.com.			IN	A

;; ANSWER SECTION:
netflix.com.		0	IN	A	104.236.46.190

;; Query time: 38 msec
;; SERVER: 104.236.46.190#53(104.236.46.190)
;; WHEN: Sat Mar 19 17:14:46 2016
;; MSG SIZE  rcvd: 45

Im assuming this is normal behaviour?
