### ISSUE TITLE
Roku

### ISSUE THREAD

**Issue by 3djake** [ab77/netflix-proxy#101]
Hi

Is there a way  to get this working on a Roku Stick? As far as I am aware Roku supports SNI.

I can stream via my browser if I add nflxvideo.net to zones.overide and add 
server=/nflxvideo.net/##.###.##.## to my dnsmasq on my router.

When streaming from Roku I get the "Proxy" error

Thanks
Regards, Jake.

**Comment by ab77** [comment]
Roku isn't using your Smart DNS IP, it's reverting to using Google's or some other well known public DNS server IP(s) if it detects it can get to it. Null route 8.8.8.8 and 8.8.4.4 on your router and your should be fine. See [this](http://www.mondaiji.com/blog/other/it/10225-roku-blocking-hard-coded-dns).

-- ab1

**Comment by 3djake** [comment]
Sorry should have mentioned I already did that using iptables.

iptables -t nat -A PREROUTING -d 8.8.8.8 -j DNAT --to-destination ###.###.###.###

**Comment by ab77** [comment]
The you need to put a packet sniffer between Roku and your router and see what it is actually doing..

**Comment by 3djake** [comment]
k, I will run a tcpdump on my router tomorrow and get back to you. Thanks for replying.

**Comment by 3djake** [comment]
I did a tcpdump, I could not determine any issues but I do not know much about networking.

So, here I see the Roku making a request to googles DNS 

`334	38.172195	8.8.8.8	10.0.0.140	DNS	399	Standard query response 0xea88 A so0.akam.nflximg.com CNAME so.akam.nflximg.com.edgesuite.net CNAME a1123.dscg.akamai.net A 23.220.148.40 A 23.220.148.17 NS l.root-servers.net NS b.root-servers.net NS m.root-servers.net NS i.root-servers.net NS c.root-servers.net NS k.root-servers.net NS g.root-servers.net NS e.root-servers.net NS d.root-servers.net NS a.root-servers.net NS j.root-servers.net NS f.root-servers.net NS h.root-servers.net`

How ever my iptables policy should be forwarding it to my proxy in the states
I verified my policy was working with iptables -t nat -L

```
DNAT       0    --  anywhere             google-public-dns-a.google.com to:192.81.208.100
DNAT       0    --  anywhere             google-public-dns-b.google.com to:192.81.208.100
DNAT       0    --  anywhere             google-public-dns-a.google.com to:192.81.208.100
DNAT       0    --  anywhere             google-public-dns-b.google.com to:192.81.208.100
```
But as I said, I am not good at networking so I might have missed something from the tcpdump.
I have the file if you would like to open it in wireshark or something.

Thanks.
Regards, Jake.

**Comment by ab77** [comment]
Have you actually verified your DNAT rules are working?

If they are, from a PC `dig netflix.com @8.8.8.8` and if you should only get a single A record returned, with the IP of your VPS..

**Comment by 3djake** [comment]
yeah, looks like its working

`; <<>> DiG 9.9.5-3ubuntu0.7-Ubuntu <<>> netflix.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46501
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;netflix.com.			IN	A

;; ANSWER SECTION:
netflix.com.		86400	IN	A	###.##.##.##

;; AUTHORITY SECTION:
netflix.com.		86400	IN	NS	ns1.netflix.com.

;; ADDITIONAL SECTION:
ns1.netflix.com.	86400	IN	A	###.##.##.##

;; Query time: 210 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon Mar 21 01:42:44 NZDT 2016
;; MSG SIZE  rcvd: 90
`

**Comment by ab77** [comment]
Well, if you are proxying both `netflix.com` and `nflxvideo.net` and the Roku is still getting a proxy error (while a browser doesn't), it may be something to do with account level blocking. Try logging off Netflix on the Roku and then logging back in..

I am guessing the browser is working on the same network segment as Roku (wireless/wired), so it is odd that one device is working and not the other.. Could be as simple as caching, etc. Try rebooting the Roku, etc.

**Comment by 3djake** [comment]
I tried restarting several times, this time I logged out and then restarted, logged back in and a blocked TV show started playing. I am not the one who uses the Roku's in my house so I will have to see if it keeps working. Sorry about creating a ticket about something so trivial but the Roku's are usually always being used by some one so I did not have many opportunity's to test it.

Thanks for this great program.
I will add a page to the wiki for setting up proxies with dd-wrt.

**Comment by ab77** [comment]
No problem at all, please do. Every little bit of info helps! :grimacing:

**Comment by 3djake** [comment]
Well it appeared to only work once when I briefly tested it but later on when some one tried to watch netflix on the device, the proxy error comes up again and I even tried removing and reinstalling the netflix app.

**Comment by ab77** [comment]
Common sense suggests that if it worked once and then stopped, then something has changed. If you are confident your end is fine, then the change is on the other side. I suspect Netflix are doing some account level blocking, so you could always try creating a new account. There isn't much else that could be done purely from the networking perspective..

**Comment by 3djake** [comment]
Yeah that might be true, though I am yet to try a new account. Strange that it would still work via the browser though.

I even tried forcing Android to use the proxy for all traffic via port 53 but to no avial
iptables -t nat -I PREROUTING -i br0 -s 10.0.0.41/25 -p tcp --dport 53 -j DNAT --to ##.##.##.##

**Comment by 3djake** [comment]
I tried using a new account, I am still getting the Proxy error on android and roku

**Comment by ab77** [comment]
I'll see if I can get an Android device and have a play myself..

**Comment by ab77** [comment]
Here is the answer: https://www.facebook.com/GetflixAU/posts/650132888457824

In summary: if you account is "tagged" by Netflix, the browser is your only friend.

**Comment by 3djake** [comment]
Do you think it will work if I installed openVPM and made all traffic going to netflix go through that?

**Comment by ab77** [comment]
Give it a go.. At least you'll know that regardless of what the app is doing (bypassing DNS entirely with hardcoded IPs), all the traffic is going to come out from the VPN on the other side..

**Comment by 3djake** [comment]
I might give it a go in the weekend, for now I just told people in my house to plug their laptops into their TV's. They have wireless mouses, not a good permanent solution but it will do for now.

**Comment by ab77** [comment]
Closing now that Netflix blocked IPv6.

**Comment by 3djake** [comment]
On a side note, Digital Ocean appears to be blocked. I ran OpenVPN on a droplet and still got the proxy error. I think netflix are not going to just block well known VPN's but also VPS and dedicated servers. I think they are pretty much going to block IP's from all data centres.
