### ISSUE TITLE
Netflix: Your device may not be connected to the internet. Please make sure you connection is working and try again.

### ISSUE THREAD

**Issue by WeirdG** [ab77/netflix-proxy#102]
I just finished rebuilding my server with the code, and now I'm testing things out.  

Pandora:
- Works on my laptop and Sonos wireless speaker.
- No change from before.

Netflix US:
- Works on my laptop
- Fails to work on my Samsung SmartTV.  Content available to Canada works, but when I play Sons of Anarchy or Star Trek DS9, which are US only, I receive the error below"

"Your device may not be connected to the internet. Please make sure you connection is working and try again."

Any ideas on how I can get around this?  Netflix was working on my SmartTV up until a couple of days ago, and then this morning I received the proxy error.  I noticed some updates were made to the code, so I decided to rebuild my server and start over again.

TIA.

**Comment by kyle95wm** [comment]
hmm No problems here. It works great on my Samsung. Can you please tell me what provider you're using? If it's DO, what region are you in?

For best results NYC3 seems to work. Remember to enable IPV6 before running the script. After that authorize your IP in the admin pannel for good measure.

I was considering maybe allowing others the use of my server, but you'd have to submit maybe a form to me or something detailing your IP and maybe a sort of contact info so I can keep track of who's using my server. Then again, I could enable automatic authorization, but the author doesn't recommend it.


Only as a last resort though. I encourage everyone here to get their own instance working

**Comment by kyle95wm** [comment]
Oh and I forgot, which branch are you using? I suggest the new-auth branch

**Comment by ab77** [comment]
If some titles are working and some aren't, it sounds to me like some sort of Netflix account issue. Logout from all devices, clear cookies where possible, log back in and create a new watching profile.

Presumably you'll also verified your Samsung TV has SNI support? https://sni.velox.ch/

-- ab1

**Comment by WeirdG** [comment]
I'm not using DO.  I found a another service which was previously working.  My TV has SNI support because it received the Great! message when I went to sni.velox.ch on my TV's browser.

I logged out and back in Netflix, I created a new profile, and I set the TV's DNS server to my KVM's IP.

How does the new-auth branch differ from the master?  I may try rebuilding using new-auth.

**Comment by ab77** [comment]
`new-auth` basically adds a better UI for add/removing IP addresses, plus some minor tweaks.

Jus thinking about your issue.. Have you added `nflxvideo.net` to your `zones.override` and rebooted? 

-- ab1

**Comment by WeirdG** [comment]
Yes... I added `nflxvideo.net` to `zones.override`.  I saw you recommended it in the [wiki](https://github.com/ab77/netflix-proxy/wiki).

**Comment by ab77** [comment]
You are going to have to capture the HTTP traffic from the TV to Netflix when you try to play a title which is working as well as one which isn't. Then compare to see what the difference is..

If you can run `tcpdump` on your router, you should be able to do this.. Otherwise we are diagnosing blind.

**Comment by WeirdG** [comment]
k... will see what I can do.

**Comment by ab77** [comment]
Here is the answer: https://www.facebook.com/GetflixAU/posts/650132888457824

In summary: if you account is "tagged" by Netflix, the browser is your only friend.

**Comment by WeirdG** [comment]
Hmm... think canceling my account and subscribing to Netflix US could fix the problem?  I currently have a Netflix Canada account.

**Comment by ab77** [comment]
Unlikely, but you could try. I've read suggestions, that new accounts are all flagged by default.

**Comment by WeirdG** [comment]
Couple of question... I wanted to try the new-auth branch.  The installation went pretty smoothly, but I ran into one issue at the end.  It tells me `WARNING: IPv6=Disabled`.  I set a static IPv6 address, and I still get that message.  When I run `ifconfig`, I see IPv6 network configs.  What am I doing wrong, what needs to be enabled?

The other thing is, I tried Unlocator (free trial), and their beta DNS get around the Netflix "tag"

**Comment by WeirdG** [comment]
k... I think I figured it out by using a DO account.  I created a new droplet in DO with IPv6 enabled.  Then I installed new-auth.  I test Netflix, but it still didn't work.  Then I added the nflxvideo entry to zones.override, and tried again.  This time it worked.

With my other host, it seems IPv6 isn't enabled, even though I have an IPv6 address.  Any idea how to enable it in Debian?

**Comment by belodedenko** [comment]
Yes, you need to both have IPv6 on the host enabled and to proxy `nflxvideo.net` domain. I am not convinced anyone could get around an account level flag just by moving network traffic around, but if it is true, then I guess there's hope for us all after all.. :grimacing:

**Comment by ab77** [comment]
Yes, you need to both have IPv6 on the host enabled and to proxy `nflxvideo.net` domain. I am not convinced anyone could get around an account level flag just by moving network traffic around, but if it is true, then I guess there's hope for us all after all.. :grimacing:

**Comment by ab77** [comment]
Closing that Netflix has now blocked IPv6.

**Comment by WeirdG** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOO!!!!!!

**Comment by WeirdG** [comment]
Will need to test when I get home.

**Comment by WeirdG** [comment]
Worst case, I'll switch back to the Mar 11, 2016 commit and sign-up with Hulu.

**Comment by ab77** [comment]
New work around in place, make sure to read the README very carefully before redeploying, because the instructions are a bit more complicated now..

-- ab1
