### ISSUE TITLE
Device Support outside of Web Browser

### ISSUE THREAD

**Issue by JoeTurksta** [ab77/netflix-proxy#103]
Tried to make this work on my Apple TV, but the content doesn't stream. Is there a way to make this solution work on my Apple TV? Web browser was fine.

**Comment by ab77** [comment]
Have you added `nflxvideo.net` domain to your `zones.override` and restarted?

**Comment by ab77** [comment]
Also, what router/firewall are you running this through and do you get the same problem if you AirPlay from your iOS device to ATV?

**Comment by ab77** [comment]
I've just tested on my ATV v3 and it seems to work fine with `nflxvideo.net` domain being proxied in addition to `netflix.com`..

**Comment by machcnz** [comment]
Tested on Android app, Samsung smart BDP (app) and Browser.  Only Browser is working.  To test on WDTV LIve tomorrow.  Thanks developer, excellent work!

**Comment by ab77** [comment]
https://github.com/ab77/netflix-proxy/wiki/Apple-TV-4,-Roku,-Google-Chromecast-and-any-other-device-with-hard-coded-DNS

https://github.com/ab77/netflix-proxy/wiki/setting-up-netflix-proxy-with-dd-wrt

**Comment by ab77** [comment]
Here is the answer: https://www.facebook.com/GetflixAU/posts/650132888457824

In summary: if you account is "tagged" by Netflix, the browser is your only friend.

**Comment by JoeTurksta** [comment]
Interesting it worked for your ATV v3 (same as mine). I'll ensure I have the nflxvideo.net added into the zones.override file and restart the services. 

As for "Tagged by Netflix", I don't get it. I'm actually paying US Netflix for my account and I have my ATV set as US with a US iTunes account. I am actually based in New Zealand, so I'll be interested in getting this working for sure. 

My host is Ramnode, $3.50 per month is very affordable. Is it possible that my IPv6 config is the issue, I tried to follow your instructions, but got slightly confused (Need more time to get my head around it).

**Comment by ab77** [comment]
Try creating a new account (buy a Netflix gift card online if you have to), but make sure when you are creating the account, you are accessing via your setup, so that Netflix thinks you are in the US. The phone number at the bottom of the site should be a US one, plus everything should be in USD.

**Comment by machcnz** [comment]
Re. "In summary: if you account is "tagged" by Netflix, the browser is your only friend."
- What I have found is that your DNS/Proxy solution works per my last comment.  Having stood up OpenVPN on that same VPS, I receive "You seem to be using a proxy" message, so perhaps NFX are tagging the account and blocking against known IPv4 ranges.  

Interested to know from others of any VPS hosts which are not being blocked, but probably best not commented here for obvious reasons :)

**Comment by JoeTurksta** [comment]
Agree about being commented here, HA!

Is netflix Filtering IPv6 Blocks as well?

**Comment by machcnz** [comment]
As a follow up to my last post.  Soln - PC with Chrome browser+Chromecast = select title and cast to the big screen.  Thanks again ab77, very nice work.  ipv6 is our friend :)

**Comment by ab77** [comment]
:+1:

**Comment by JoeTurksta** [comment]
Hey @machcnz , can I contact you offline? :) 

Twitter/FB/Email ?

**Comment by machcnz** [comment]
Hi Joe, keen to help out where I can.  Drop me a text file with your contact email in here :)

https://drive.google.com/open?id=0B39sQOUqkfp2SlJ4VW9tbXlFWlk

**Comment by JoeTurksta** [comment]
@machcnz done, thanks man!
