### ISSUE TITLE
BBC appears to be down again

### ISSUE THREAD

**Issue by JcMaltaDev** [ab77/netflix-proxy#104]
Early this morning, I spun up a new DO Droplet to look at this solution.

On first attempt, things were looking good ... Got past their new VERY fast geo-locate block, past "Have you got a licence?", "Are you over 18?", but on video loading .... "This content doesn't seem to be working" <sigh>

I made the suggested change adding "bbcfmt.vo.llnwd.net." to zones.override and watched around 10 mins of BBC1/2 and some archive. Impressed!

But a few hours later the "content doesn't seem to be working" is happening all the time.

I have built droplets with both the latest and previous versions and also added all the zones mentioned in [This item](https://github.com/ab77/netflix-proxy/issues/42#issuecomment-152128091), but with no further sucess :(

Is there a later list of the CDNs the BBC may be using?

**Comment by ab77** [comment]
Can you please try to capture the actual CDN hostname when is returning a `403 Unauthorised` by playing in a browser (i.e. Chrome) with dev. tools console open on the `network` tab..

**Comment by JcMaltaDev** [comment]
Well ... I tried .... but it is suddenly working again with only "bbcfmt.vo.llnwd.net." added !

I will of course send the information you requested if I run into the problem again.

Many thanks for your hard work!

**Comment by ab77** [comment]
No worries.
