### ISSUE TITLE
Not working right now

### ISSUE THREAD

**Issue by nixxle** [ab77/netflix-proxy#106]
Had a great week watching all of Netflix, for which I thank you. 

It doesn't seem to work anymore, though. I added the extra entry to the zone, didn't work. I set up a new server with the newest version, didn't work. I set up a SSH tunnel with putty but that didn't work either. 

Then, I tried creating a new Netflix account, using the server. Maybe a fully US Netflix account wouldn't be 'tagged'. But it still didn't work. So this makes me wonder.... if it's an US Netflix account and all data goes through the US, how can they still know what I'm doing?

I guess it's because the IP address of the server? How do I get around that? Do I need a more 'obscure'  host?

**Comment by ab77** [comment]
Yep, blocked. If you can find a host somewhere, which isn't blacklisted, keep it to yourself :grimacing:

**Comment by ab77** [comment]
New work around in place, make sure to read the README very carefully before redeploying, because the instructions are a bit more complicated now..

-- ab1

**Comment by machcnz** [comment]
Legendary ab1, cheers!

**Comment by machcnz** [comment]
One question, do you recommend rebuilding with your latest comits or just implementing the new steps?

**Comment by ab77** [comment]
Yep, destroy and rebuild.
