### ISSUE TITLE
BBC appears to be down again (cont)

### ISSUE THREAD

**Issue by JcMaltaDev** [ab77/netflix-proxy#107]
Further to [Issue 104](https://github.com/ab77/netflix-proxy/issues/104):

A similar, but slightly different failure.

After the 3 second "channel splash", just left with the spinning "loading" icon at program start.

There was a 403 on request for _http://vod-hds-uk-live.edgesuite.net/crossdomain.xml_.

Added vod-hds-uk-live.edgesuite.net to zones.override and all OK now.

I am not at all familiar with BIND. Is it possible to "wildcard" zone entries? eg " vs-hds-uk-live.* " ?

**Comment by ab77** [comment]
Cheers, I've added this and other domains now to the file.

Read: http://serverfault.com/questions/229085/wildcard-dns-with-bind
