### ISSUE TITLE
Problems at the Testing DNS step. 

### ISSUE THREAD

**Issue by iulianhostiuc** [ab77/netflix-proxy#108]
I have followed all the steps and everything works OK until the "Testing DNS" step, where it hangs, it retries, with no succes: <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> +time=10 netflix.com @104.131.169.185 ;; global options: +cmd ;; connection timed out; no servers could be reached. 

How can I check if I have done all the steps properly before running build.sh?

**Comment by ab77** [comment]
Fixed, problem in the `zones.override` file.
