### ISSUE TITLE
Iptables keeps reverting back

### ISSUE THREAD

**Issue by rjclarkewp007** [ab77/netflix-proxy#11]
Hi

I'm trying to set this up on Amazon EC2 now. Works fine after install, but as soon as my public IP changes it won't work anymore. I do have no-ip.org setup on my router already.

I've tried everything and still it seems like as soon as I make a change to /etc/iptables/rules.v4 and save it, it has no effect. Then I do a reboot and the rules are gone when I do iptables -L. I think iptables persistent is installed, but not sure if I need to save anything after making changes? So after editing /etc/iptables/rules.v4 what do I do?

Also, the script to update the iptables (/opt/scripts/update-firewall.pl) for dynamic DNS does not seem to work. I picked up that in the script it has /etc/iptables.rules and my rules are under /etc/iptables/rule.v4. Does does make any difference? Also the restore of the rules in this script I'm not sure if it's correct? Like the /sbin/iptables and /usr/bin/docker?

    if (system("/sbin/iptables -L -v | grep -i $vName > /dev/null ") != 0) {
      system "/sbin/iptables-restore/iptables-restore < /etc/iptables.rules" ;
      system "/usr/bin/docker restart bind sniproxy" ;

I'm using Ubuntu 14.04. So not sure if that makes any difference as well?

Any help will greatly be appreciated!!

**Comment by ab77** [comment]
On EC2's `Ubuntu Server 14.04 LTS (HVM), SSD Volume Type (ami-d05e75b8)`, your rules should go into `/etc/iptables/rules.v4` and `/etc/iptables/rules.v6` (if you are using IPv6 - not supported by `update-firewall.pl`, but can be trivially added).

These files should already be there since they are created by the `iptables-persistent` service, which is installed by `build.sh`.

So, edit the rules in `/etc/iptables/rules.v4` to change your IP address to your dynamic host name (x3 rules in total) and then update your `/opt/scripts/update-firewall.pl` script as follows to reflect changes in locations under EC2:

    if (system("/sbin/iptables -L -v | grep -i $vName > /dev/null ") != 0) {
        system "/sbin/iptables-restore < /etc/iptables/rules.v4" ;
        system "/usr/bin/docker restart bind sniproxy" ;

Save everything, reboot the instance and it should start working. Let me know how it goes..

-- ab1

**Comment by rjclarkewp007** [comment]
Hi Anton

 

I’ve tried this again now and after the reboot iptables –L returns: (all open now)

 

Chain FORWARD (policy ACCEPT)

target     prot opt source               destination

DOCKER     all  --  anywhere             anywhere

ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED

ACCEPT     all  --  anywhere             anywhere

ACCEPT     all  --  anywhere             anywhere

 

Chain OUTPUT (policy ACCEPT)

target     prot opt source               destination

 

Chain DOCKER (1 references)

target     prot opt source               destination

ACCEPT     udp  --  anywhere             ip-172-17-0-1.us-west-2.compute.internal  udp dpt:domain

 

_____________________________________________________________________________

 

Before reboot i edited /etc/iptables/rules.v4 and :wq it.

Also created the /opt/scripts directory and created update-firewall.pl that looks like this now:

 

#!/usr/bin/perl -w

# restart the firewall if the IP address changed

# /etc/sysconfig/iptables

use strict;

 

pAllow("rjclarkewp.no-ip.org");

 

sub pAllow {

  my ($aName) = @_;

  #print "aName: $aName\n";

  my $vAddress = readpipe("host $aName | cut -d \" \" -f4");

  chomp $vAddress;

  #print "vAdress: $vAddress\n";

  my $vName = readpipe("host $vAddress | cut -d \" \" -f5");

  chomp $vName;

  if ($vName =~ "SERVFAIL") {

    $vName = $vAddress;

  }

  #print "vName: $vName \n";

  if ($vName ne "") {

    if (system("/sbin/iptables -L -v | grep -i $vName > /dev/null ") != 0) {

      system "/sbin/iptables-restore < /etc/iptables/rules.v4" ;

      system "/usr/bin/docker restart bind sniproxy" ;

    }

  }

}

 

 

Then ran: chmod 700 /opt/scripts/update-firewall.pl

Then: crontab –e and added */15 * * * * /opt/scripts/update-firewall.pl

Then rebooted and all rules gone and ports now all open.

 

Any ideas?

 

Raymond Clarke

Mobile: 071 480 6651

Mail Address:  <mailto:rjclarkewp007@gmail.com> rjclarkewp007@gmail.com

**Comment by rjclarkewp007** [comment]
Oh and sorry, my /etc/iptables/rules.v4 looks like this. Still has the no-ip.org in that I saved:

 

# Generated by iptables-save v1.4.21 on Fri Jul 10 11:25:06 2015

*nat

:PREROUTING ACCEPT [0:0]

:INPUT ACCEPT [0:0]

:OUTPUT ACCEPT [28:2270]

:POSTROUTING ACCEPT [28:2270]

:DOCKER - [0:0]

-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER

-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER

-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE

COMMIT

# Completed on Fri Jul 10 11:25:06 2015

# Generated by iptables-save v1.4.21 on Fri Jul 10 11:25:06 2015

*filter

:INPUT ACCEPT [0:0]

:FORWARD ACCEPT [0:0]

:OUTPUT ACCEPT [46:21674]

:DOCKER - [0:0]

-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

-A INPUT -p icmp -j ACCEPT

-A INPUT -i lo -j ACCEPT

-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT

-A INPUT -s rjclarkewp.no-ip.org -p tcp -m tcp --dport 80 -j ACCEPT

-A INPUT -s rjclarkewp.no-ip.org -p tcp -m tcp --dport 443 -j ACCEPT

-A INPUT -j REJECT --reject-with icmp-host-prohibited

-A FORWARD -o docker0 -j DOCKER

-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A FORWARD -i docker0 ! -o docker0 -j ACCEPT

-A FORWARD -i docker0 -o docker0 -j ACCEPT

-A FORWARD -j REJECT --reject-with icmp-host-prohibited

-A DOCKER -m state --state RELATED,ESTABLISHED -j ACCEPT

-A DOCKER -p icmp -j ACCEPT

-A DOCKER -s rjclarkewp.no-ip.org -p udp -m udp --dport 53 -j ACCEPT

-A DOCKER -j REJECT --reject-with icmp-host-prohibited

COMMIT

# Completed on Fri Jul 10 11:25:06 2015

 

Raymond Clarke

Mobile: 071 480 6651

Mail Address:  <mailto:rjclarkewp007@gmail.com> rjclarkewp007@gmail.com

**Comment by ab77** [comment]
What happens when you run `sudo service iptables-persistent start` manually after reboot?

**Comment by ab77** [comment]
Sorry, forgot to add that you'll need to add `pre-up iptables-restore < /etc/iptables.rules` to your interfaces file to restore iptables rules on start-up:

    # vim /etc/network/interfaces
    ...
    auto eth0
    iface eth0 inet static
        address 46.x.x.x
        netmask 255.255.x.x
        gateway 46.x.x.x
        pre-up iptables-restore < /etc/iptables.rules

That should do it..

**Comment by rjclarkewp007** [comment]
Thanks Anton!

 

I think it might actually be working now!

So far so good. Will add my friends and see how it goes.

 

Thanks again for all the help! Much appreciated!

 

Raymond Clarke

Mobile: 071 480 6651

Mail Address:  <mailto:rjclarkewp007@gmail.com> rjclarkewp007@gmail.com

**Comment by ab77** [comment]
Good stuff, I'll have to pull all of this together into a Wiki page..

**Comment by rjclarkewp007** [comment]
That will be nice yes! Thanks man!!

 

Raymond Clarke

Mobile: 071 480 6651

Mail Address:  <mailto:rjclarkewp007@gmail.com> rjclarkewp007@gmail.com
