### ISSUE TITLE
Hulu does not work

### ISSUE THREAD

**Issue by iulianhostiuc** [ab77/netflix-proxy#110]
With the latest master branch, everything works fine at build time. Netflix also works fine (so far). 
However, Hulu does not seem to work anymore. I get the Anonymous Proxy error when playing a video. Hulu works for me for other commercial unblockers, like unblocator.com

**Comment by ab77** [comment]
Have you read foot note [n2] in the README?

**Comment by iulianhostiuc** [comment]
Yes, I've read it. What are our options? This means that we do not support Hulu?

**Comment by ab77** [comment]
If you can find a provider that Hulu hasn't blocked (good luck), then this will work just fine.

**Comment by ab77** [comment]
I am going to close this since there are no actions..

Cheers!
