### ISSUE TITLE
sniproxy restart overwrites all my sniproxy.conf addresses

### ISSUE THREAD

**Issue by edwinsc** [ab77/netflix-proxy#111]
I added IP addresses to sniproxy.conf to run my own webserver in the same machine, but restarting sniproxy overwrites all my 127.0.0.1 for 8.8.8.8. 
So I can't access my webserver.

**Comment by ab77** [comment]
I don't really have a solution for this unfortunately, as it wasn't a design consideration. You could try making the file read-only, system, etc. and see if that is a work-around, otherwise you need to build your own local sniproxy container with the changes in its start-up script.
