### ISSUE TITLE
Netflix not working on mobile/smart tv

### ISSUE THREAD

**Issue by iulianhostiuc** [ab77/netflix-proxy#113]
Netflix is fully working for me on browser, but on mobile it somehow detects my real location and a popup message says that the selected title is not available in my region. So no proxy error. 
I've read about the account tagging you mentioned. I've created another Netflix account, a fresh one, and the same thing happens. 

Is there anyway we can make this work also on the mobile/smart tv devices? Are these apps using internal DNS addresses (like Chromecast does)? Do we know them so we can block them in the router?

Thanks.

**Comment by iulianhostiuc** [comment]
How can I route all traffice through the VPS? In a previous version of the Readme file you posted this from what I remember

**Comment by ab77** [comment]
You'll have to follow: https://github.com/ab77/netflix-proxy#further-work

Then set you local DNS (via DHCP?) to the Smart DNS IP and block/null-route all known public DNS servers (i.e Google, OpenDNS, etc.).

**Comment by ab77** [comment]
OK, I fixed the major issue, which was affecting most people. Basically, IPv6 was broken in most cases.

Please rebuild with the new version and it should be good to go

(no need to destroy the tunnel, use the current configuration - jut rebuild the VPS).

**Comment by ab77** [comment]
(also, re-read the instructions, there is an extra step without which it will fail)

**Comment by iulianhostiuc** [comment]
I've rebuilt the VPS and followed the extra step too. Will be able to test on mobile & smart TV in about 2h. I will let you know. 

Thanks.

**Comment by ab77** [comment]
Test in a browser first to make sure it is working generally, then move onto other devices.

**Comment by iulianhostiuc** [comment]
In a browser Netflix in working (it was also working before). I only had problems with other devices. 
Hulu does not work neither on browser nor on mobile devices. Hulu however works with the Unlocator DNS.

**Comment by ab77** [comment]
Forget Huu, unless you can find a VPS which they haven't blocked yet :)

**Comment by iulianhostiuc** [comment]
Netflix works on mobile. Fingers crossed for Smart TV.

**Comment by iulianhostiuc** [comment]
Uf, it worked for a few tests and now it does not work on mobile and TV anymore :(

**Comment by iulianhostiuc** [comment]
It started working again :) Thanks. I will also donate a beer++

**Comment by ab77** [comment]
Good work and thank you!
