### ISSUE TITLE
your-routed-64-prefix-subnet

### ISSUE THREAD

**Issue by WeirdG** [ab77/netflix-proxy#114]
What are we supposed to enter for that? I'm a little confused on that step.

**Comment by ab77** [comment]
You will find it on the HE tunnel info page.

**Comment by WeirdG** [comment]
Thanks for the tip Anton.  That worked.  You can close this issue.

**Comment by WeirdG** [comment]
Oh... one other thing.  Is it possible to have the admin console display all authorized IPs addresses (even if dupicates)?

**Comment by ab77** [comment]
There is a feature in there where you can create a non-admin user and non-admin users get a filtered drop-down of all authorised IPs. Duplicates are not shown, as if you de-authorise an IP, it automatically removes all entries associated with that IP.

You'll need to get into the sqlite DB and create a non-admin user, setting the privilege column to 0 (e.g.):

```
sqlite> .schema USERS
CREATE TABLE USERS(
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   created DATETIME DEFAULT CURRENT_TIMESTAMP,
   privilege int NOT NULL,
   expires date NOT NULL,
   username char(50) NOT NULL,
   password char(255) NOT NULL
);
```

You can create a user like this:

```
export USERNAME=[username]
export PASSWORD=[password_plaintext]
export EXPIRES=YYYY-MM-DD # user access expiry
export PRIVILEGE=0 # 0 = user; 1 = admin
export BUILD_ROOT=/opt/netflix-proxy
export SQLITE_DB=${BUILD_ROOT}/auth/db/auth.db
cd ${BUILD_ROOT} && \
  export HASH=`${BUILD_ROOT}/auth/pbkdf2_sha256_hash.py ${PASSWORD}` && \
  sqlite3 ${SQLITE_DB} "INSERT INTO USERS (privilege, expires, username, password) VALUES (${PRIVILEGE}, '${EXPIRES}', '${USERNAME}', '${HASH}');"
```
