### ISSUE TITLE
Problem running netflix proxy

### ISSUE THREAD

**Issue by denebola2015** [ab77/netflix-proxy#115]
I keep getting, syntax error near unexpected token `newline' when I run ifup he-ipv6 && apt-get update && apt-get -y install vim dnsutils curl sudo git && curl -sSL https://get.docker.com/ | sh && git clone https://github.com/ab77/netflix-proxy /opt/netflix-proxy && cd /opt/netflix-proxy && ./build.sh -s <2001:470:1f07:890::/64> on the server

**Comment by ab77** [comment]
Which line?

**Comment by denebola2015** [comment]
Doesn't say, I'm left guessing as to wether its a syntax error or something else. I'm using vultr debian 8 X 64.

**Comment by ab77** [comment]
Very good :grimacing:
