### ISSUE TITLE
Feature: integrate with DynDNS

### ISSUE THREAD

**Issue by haniag** [ab77/netflix-proxy#116]
It would be a really neat feature to integrate with DynDNS, or similar, to auto update when ISP changes IP.

**Comment by ab77** [comment]
This has been documented elsewhere. You need to configure `ddclient` to update your HE tunnel (see an  old post here: http://blog.belodedenko.me/2013/06/a-practical-guide-to-setting-up-ipv6.html).

The proxy will automatically redirect you to the auth web page if you IP address has changed as is no longer authorised.

-- ab1

**Comment by ab77** [comment]
Also, you could in theory use a custom script with `ddclient` to update your tunnel IP and also authorise the new IP with iptables. Should be fairly trivial to script.. Feel free to submit a pull request.
