### ISSUE TITLE
Testing proxy failure

### ISSUE THREAD

**Issue by matty** [ab77/netflix-proxy#117]
In the latest update I am using now on an Ubuntu server, the testing part fails with

"Testing proxy (OpenSSL)
CONNECTED(00000003)
Failure! Retrying in 10.."

It keeps repeating and never passes.

**Comment by matty** [comment]
Also the admin user/pass doesn't output anymore

**Comment by ab77** [comment]
It is possible this is related to the last update I made, which I've just rolled back. Seems to be OK, t leat on DO. Give it a go and if it doesn't work, blow away your VPS and build a new one, possibly even in a different DC (doesn't have to be in the US).

**Comment by matty** [comment]
I believe that has solved the testing issue. What's with the tunnelbroker requirement now? I had ipv6 enabled on Linode and everything working properly before this update, now netflix doesn't work and with Tunnelbroker it detects the proxy?

**Comment by ab77** [comment]
Native IPv6 blocked. HE tunnel IPv6 isn't. Make sure to disable native IPv6 on the host before you start installing the proxy and you have established IPv6 connectivity via tunnel (ping6 google.com) to test.

**Comment by matty** [comment]
Disabling good enough by just removing the ipv6 config from the interfaces config?

**Comment by ab77** [comment]
That should be fine. As long as there no pubic IPv6 IPs on the interfaces and no IPv6 connectivity, you should be OK to proceed.

**Comment by ab77** [comment]
Simplest way: http://superuser.com/a/575701/257944

**Comment by matty** [comment]
Confirmed that works @ab77
