### ISSUE TITLE
ifup he-ipv6 issue

### ISSUE THREAD

**Issue by haniag** [ab77/netflix-proxy#118]
On RamNode, I reinstalled image, created the tunnel and copied the config data to interfaces file. Afterwards, when I type "ifup he-ipv6", I get:

RTNETLINK answers: File exists
Failed to bring up he-ipv6.

If I type "ifup he-ipv6 ping6 google.com", I get:

add tunnel "sit0" failed: No buffer space available
Failed to bring up he-ipv6.
Ignoring unknown interface ping6=ping6.
Ignoring unknown interface google.com=google.com.

In instructions, it says not to enable IPv6, but there is no where in RamNode for that option. Is this related?

**Comment by ab77** [comment]
Probably, make sure to disable native IPv6 if it is enabled or find another provider..

**Comment by ab77** [comment]
edit `/etc/network/interfaces`, comment out the three `up ip ...` lines at the bottom, save, run `ifdown eth0; ifup eth0` and test by `ping6 google.com`. If you get `network unreachable`, proceed with the steps as documented.

**Comment by ab77** [comment]
Or https://github.com/ab77/netflix-proxy/issues/117#issuecomment-201866250

**Comment by haniag** [comment]
The commenting worked great and I was able to successfully install it. However, netflix still detects that I am behind a proxy even after flushing cache. This is happening on web and other devices. I guess I have to try a different host?

**Comment by ab77** [comment]
Sounds like your Docker containers can't communicate over IPv6..  Try `docker run -it ubuntu bash -c "ping6 google.com"`.

If you get no response, re-build on a different host, provider, DC, etc. Ultimately, the build script needs to enable IPv6, so you should see `IPv6=Enabled` at the end. If you do, then try the ping command above. If that works, you should be good to go, otherwise repeat from zero.

Good luck!

**Comment by haniag** [comment]
Ok, I finally figured it out and it works! I needed your instruction in addition to the one in link to disable native IPv6 in RamNode:

-edit /etc/network/interfaces
-comment out the three up ip ... lines at the bottom
-save
-edit /etc/sysctl.conf
-add net.ipv6.conf.eth0.disable_ipv6 = 1
-run ifdown eth0; ifup eth0
-test by ping6 google.com
-If you get network unreachable, proceed with the steps as documented

**Comment by ab77** [comment]
Good work!
