### ISSUE TITLE
Device "link" does not exist.

### ISSUE THREAD

**Issue by davedxb** [ab77/netflix-proxy#12]
>./build.sh
>Device "link" does not exist.

:(

**Comment by davedxb** [comment]
>ifconfig

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

venet0    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:127.0.0.2  P-t-P:127.0.0.2  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1
          RX packets:78 errors:0 dropped:0 overruns:0 frame:0
          TX packets:52 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:6898 (6.8 KB)  TX bytes:9351 (9.3 KB)

venet0:0  Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:162.208.9.231  P-t-P:162.208.9.231  Bcast:162.208.9.231  Mask:255.255.255.255
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1

**Comment by ab77** [comment]
What cloud provider are you using and what OS are you deploying?

**Comment by davedxb** [comment]
Provider: vpscheap.net
OS: I tried them all, Ubuntu, Centos, Debian, all types of versions, 86, 64, all.

All gets stuck in the end with "Device "link" does not exist"

I will try with another provider (trial) and hope it works.

**Comment by ab77** [comment]
The build script assumes presence of eth0 Ethernet interface. You are trying to use a VPS provider that gives you container-based virtualisation VM as opposed to properly virtualised hardware. Try DigitalOcean instead..

**Comment by davedxb** [comment]
You are correct, this would be a good idea to look into for future development, since VPS is very hot these days. Thank you for the clarification.

**Comment by ab77** [comment]
On your VPS, could you please run the following commands and paste the output:

    sudo dmidecode -s system-product-name
    sudo ip route
    sudo ls -1 /dev/disk/by-id/
    sudo cat /proc/user_beancounters
    sudo lshw -class system

I'll see if I can update the script to work with operating-system-level virtualization (containers).

Cheers!

**Comment by davedxb** [comment]
So kind of you....please feel free to login yourself for testing...its and empty server, so go ahead.

162.208.9.231
ssh (22)
root
mypass

**Comment by ab77** [comment]
Please check the password..

**Comment by davedxb** [comment]
Sorry, i had to reset that server...

162.208.11.98
root
p@ssword

I reset this server and installed clean Ubuntu 15.04 X86 64

I will not touch this one, you are free to use it for testing purposes.

Thank you very much for your efforts and support!

**Comment by ab77** [comment]
I've had a play on your server and I think it is a waste of time trying to run Docker inside OpenVZ, which is basically like trying to run container-based virtualisation inside another container-based virtualisation.

Even if it can be made to work, it is very [hackish](http://stackoverflow.com/questions/28568893/i-cant-run-docker-daemon-on-ubuntu-14-04-lts-on-vps) and with some performance implications.

If you really want to try, the `build.sh` script in `/opt/netflix-proxy` is already patched to work out the interface/ipaddr of your VPS. You just need to hack Docker to be able to start up (i.e.):

    docker -d --bridge="venet0"

Good luck!

-- ab1

**Comment by davedxb** [comment]
Thanks for shedding some light into the topic! Really appreciated.
