### ISSUE TITLE
docker-compose/netflix-proxy.yaml does not exist

### ISSUE THREAD

**Issue by matty** [ab77/netflix-proxy#120]
There is an error when build.sh is first run on a new install, it complains that "docker-compose/netflix-proxy.yaml does not exist" but there is a .template file in that directory.

**Comment by matty** [comment]
Checking the build.sh file, it _should_ copy the yaml file, which is strange.

**Comment by ab77** [comment]
I just tested on a fresh VPS and it works fine.
