### ISSUE TITLE
SSL handshake error

### ISSUE THREAD

**Issue by matty** [ab77/netflix-proxy#121]
During testing, the SSL handshake is now failing in the setup process.

```
CONNECTED(00000003)
139643255592608:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:s23_lib.c:177:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 314 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---
```

I tried running manually "/usr/bin/timeout 10 /usr/bin/openssl s_client -CApath /etc/ssl/certs -servername google.com -connect 45.79.201.164:443" testing with google, the output above is what is presented.

**Comment by matty** [comment]
I have had quite a few issues with the latest changes so I've reverted back to commit "bcd2e95cfbd7950f9d3218cabaa573b641193140". Netflix hasn't blocked my ip addresses I am using yet and Tunnelbroker is way too slow (Netflix buffers etc).

**Comment by ab77** [comment]
I found some providers/DCs are too slow or don't work at all with HE tunnels. Your best bet is still to find a native IPv6/IPv4 provider which isn't blocked or find a provider/DC combination which works with HE..

**Comment by matty** [comment]
How do you use it without HE? The latest version seems to disable any native ipv6

**Comment by ab77** [comment]
The latest version doesn't disable anything. It will happily use native IPv6 if it available. Just don't setup any tunnels and run without `-s` switch. This should be obvious if you inspect the code.

**Comment by matty** [comment]
Yes I did check the code, before setup ping6 google.com works, after setup without -s switch ping6 google.com says host is not reachable. SSL handshake test also fails. The only version that works for me with native ipv6 is reverting back to commit bcd2e95cfbd7950f9d3218cabaa573b641193140.
