### ISSUE TITLE
Failed to start ndp-proxy-helper.service

### ISSUE THREAD

**Issue by paranoidjack** [ab77/netflix-proxy#126]
Debian 8 / Vultr VPS with IPv6 disabled

Using the latest revision I'm getting the following errors:

`add tunnel "sit0" failed: No buffer space available`
`Failed to bring up he-ipv6.`
`testing IPv6 tunnel interface, this could take a while...`

However, the script continues until it terminates with this error:

`Status: Downloaded newer image for ab77/sniproxy:latest`
`Creating sniproxy`
`Creating caching-resolver`
`/sbin/init: unrecognized option '--version'`
`Created symlink from /etc/systemd/system/multi-user.target.wants/netflix-proxy-admin.service to /lib/systemd/system/netflix-proxy-admin.service.`
`Created symlink from /etc/systemd/system/multi-user.target.wants/ndp-proxy-helper.service to /lib/systemd/system/ndp-proxy-helper.service.`
`Created symlink from /etc/systemd/system/multi-user.target.wants/systemd-networkd.service to /lib/systemd/system/systemd-networkd.service.`
`Created symlink from /etc/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service to /lib/systemd/system/systemd-networkd-wait-online.service.`
`Failed to start ndp-proxy-helper.service: Unit docker-sniproxy.service failed to load: No such file or directory.`

The problem seems to have arisen in the last couple of days worth of commits.

**Comment by ab77** [comment]
Cheers, found the problem. Should be OK now, please give it anther go and let me know how it goes..

**Comment by paranoidjack** [comment]
The latest commit solves the issue. Thank you.
