### ISSUE TITLE
Proxy left wide open by default?

### ISSUE THREAD

**Issue by securityguy** [ab77/netflix-proxy#127]
I just did a fresh install on a new Digital Ocean droplet. It seemed to install fine, but I don't see any restrictions in iptables - I'm able to connect to the proxy on port 443 from everywhere:

root@ny2:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     icmp --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:ssh
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:mdns
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http-alt
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
DOCKER-ISOLATION  all  --  anywhere             anywhere            
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (1 references)
target     prot opt source               destination         

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            
root@ny2:~#

**Comment by ab77** [comment]
This is actually by design. The connections you are seeing are to the auth portal, not the proxy. This is so that if your IP address ever changes, you are not locked out of the solution entirely. Once the IP is authorised, ports 443/80 are redirected to the actual proxy engine. Same this goes for DNS. IF the IP isn't authorised, you'll only every get the same response from the DNS server for all domains.

**Comment by securityguy** [comment]
Thank you very much!
