### ISSUE TITLE
OpenVPN Recommendation

### ISSUE THREAD

**Issue by haniag** [ab77/netflix-proxy#129]
Do you have any recommendations on how to install OpenVPN access server in combination with the DNS proxy? I have tried this: https://github.com/scotty-c/docker-openvpnas as a separate docker, but it failed since it indicated port 443 is in use. When I changed the port to 445 in Dockerfile, it installed, but the admin page won't open on https://xx.xx.xx.xx:943/admin. I am running a KMV VPS on RamNode.

**Comment by ab77** [comment]
No, not really. It feels to me like it should be a separate project, if you want to shoe-horn OpenVPN server in there. However, Docker allows you to map different external ports to internal ports used by applications. Try `... -p 8443:443` to have port 8443 on the Docker host mapped to the OpenVPN AS port 443 inside the container.
