### ISSUE TITLE
Can't work on Azure

### ISSUE THREAD

**Issue by k4roshi** [ab77/netflix-proxy#130]
Hi, and thanks for the great work.
I just wanted to let you and everybody know that AFAIK this can't work on Azure. Microsoft doesn't allow inbound ICMP traffic on Azure VMs and tunnelbroker checks the IP with a ping before setting the tunnel up. Too bad...

**Comment by ab77** [comment]
Thanks for the heads up. I'll update the README.

**Comment by sandeeprawat** [comment]
This is not correct. I had it running on Azure VMs for a while and it worked fine (unless there is some specific problem you ran into)

**Comment by k4roshi** [comment]
If that's the case i'll be glad to be wrong. 
How did you set you VM up so that it responds to ping? AFAIK Azure explicitly forbids it.

**Comment by ab77** [comment]
Without IPv6 it should work just fine. Perhaps Netflix isn't blocking Azure yet..

**Comment by sandeeprawat** [comment]
Yeah my VMs dont respond to ping but as he said probably not required for ipv4. Btw they are blocking azure too. Happy to be wrong though. Please let me know if someone finds it otherwise ;) .

**Comment by ab77** [comment]
Things move fast in this space, almost daily :grimacing:

**Comment by ab77** [comment]
I am going to close this, since there are no actions.
