### ISSUE TITLE
Problems with ocean digital

### ISSUE THREAD

**Issue by kahnhellsing** [ab77/netflix-proxy#131]
I followed the guide but for some reason it keeps dropping connection or i can't connect at all.

(i also tried the troubleshooting steps)

any help will be appreciate it.

**Comment by 3djake** [comment]
At what point does the connection drop?
Is this while streaming netflix?

We need to figure out if the problem is between your router and your droplet or between the droplet and netflix, it could be an issue with the ipv6 tunnel.

A basic way to check if packets are being dropped is
On Linux
`ping -c 50 yourserversiphere`
On Windows
`ping -n 50 yourserversiphere`

then from your server ping netflix.com

**Comment by ab77** [comment]
Try a different VPS, in a different DC. Also, create a new HE tunnel, different region and use `-n X` flag during build, where `X` is the tunnel number (index), starting from 1 (i.e. 1 = first tunnel in the portal, 2 = second tunnel, etc.)

**Comment by kalenjin** [comment]
Have set up a few droplets and HE tunnels. Installed correctly, with success message saved at end. In each case I can ping the server IP from desktop. In all cases I cannot ping netflix.com from the server.

**Comment by ab77** [comment]
Try:

```
ping google.com && ping6 google.com
ping netflix.com && ping6 netflix.com
docker run -it ubuntu bash -c "ping6 google.com"
docker run -it ubuntu bash -c "ping6 netflix.com"
```

**Comment by kalenjin** [comment]
--- google.com ping statistics ---
6 packets transmitted, 0 received, +6 errors, 100% packet loss, time 5007ms
--- netflix.com ping statistics ---
34 packets transmitted, 0 received, 100% packet loss, time 32999ms

then w/ docker, it updated, and returned, "address unreachable"
--- google.com ping statistics ---
15 packets transmitted, 0 received, +13 errors, 100% packet loss, time 14018ms

From 2001:470:7c:3c4::1 icmp_seq=14 Destination unreachable: Address unreachable
^C
--- netflix.com ping statistics ---
14 packets transmitted, 0 received, +12 errors, 100% packet loss, time 13033ms


thanks!

**Comment by ab77** [comment]
Yep, you've got a totally broken VPS. Blow it all way and start again. If you can't get it to work, pastebin `netflix-proxy.log` and the output from `build.sh`.

**Comment by kalenjin** [comment]
New Droplet or new DO account?

**Comment by ab77** [comment]
Droplet.

**Comment by kyle95wm** [comment]
Wow you beat me to that reply. I was about to say "preferably the latter" as in new droplet

**Comment by kalenjin** [comment]
Awesome. Works like a charm. Many thanx!

**Comment by ab77** [comment]
Good work!
