### ISSUE TITLE
Netflix causes Apple TV Reboots

### ISSUE THREAD

**Issue by i37** [ab77/netflix-proxy#132]
I've added the following to my Docker container to force all traffic for my apple tv to run though my VPS server. 

This works perfectly for Hulu! However 1 in 2 Netflix videos fail and I'm unsure why.

zone "." {
    type master;
    file "/data/db.override";
};

(Note you also need to add level3.net to your zones.override file to use Hulu in a browser.)

Is anyone else having an issue with the Apple TV and Netflix.

Select an affected title and the apple tv will blink 3 times then reboot.

It seems to be happening on my 2 Apple tv's in the house.

I think they are second gen Apple TVs.

**Comment by ab77** [comment]
I would not have expected Apple TVs to reboot (spontaneously?) when using a different DNS server. Seems like there is another problem in there somewhere.. Or maybe because your are proxying everything, including calls home to Apple, it is boor log because of timings, etc. Put a packet sniffer between it and the router and have a look at the last call it makes before a reboot. I've tested on my ATV3 and it works with the default `zones.override`.

**Comment by matty** [comment]
I wouldn't proxy everything with Apple TV, I bet Apple has some sort of verification where going through a proxy causes it to fail when calling home to Apple. (Apple software updates?)

**Comment by i37** [comment]
I'll look into packet sniffing... In the mean time anyway to log the dns queries?

**Comment by ab77** [comment]
Just pushed an update, if you rebuild, you should see the queries being logged when you run `docker logs -f bind`.

**Comment by i37** [comment]
rebuilding now...

**Comment by i37** [comment]
My apple tv is still rebooting after a power cycle when trying to select some titles. Other titles are fine. I'm starting to think its my apple tv itself...

BTW: **ib.huluim.com ** (which is a CNAME to akamai.net) is being used by Hulu. Adding them both made hulu work again on my Apple TV (I don't mind about data usage as I have 1TB on my VM).

Apple TV is talking to:

itunes.apple.com.edgekey.net
e905.e9.akamaiedge.net
dscg.netflix.com.edgesuite.net
a1015.dscg.akamai.net
a1015.dscg.akamai.net
webvtt.nflxvideo.net
pancake.apple.com
metrics.mzstatic.com
a1015.dscg.akamai.net
a248.e.akamai.net
appletv.app.hulu.com
play.hulu.com
t.hulu.com
firehose.hulu.com
secure.hulu.com
mozart.hulu.com
t2.hulu.com
s.hulu.com
pt.hulu.com
assets.huluim.com
ib.huluim.com

My wife come home and her iPhone connected to wifi so DNS log went crazy but just as the apple tv rebooted the following queries were made:

a1015.dscg.akamai.net
e6858.dscc.akamaiedge.net
init-p01st.push.apple.com
itunes.apple.com.edgekey.net
41-courier.push.apple.com
mesu.apple.com
mzuserxp.itunes-apple.com.akadns.net
e5153.a.akamaiedge.net
**api-glb-syd.smoot.apple.com** (concerns me as i'm in AU).
e2842.e9.akamaiedge.net
11-courier.push.apple.com
init.itunes.apple.com
p08-keyvalueservice-current.edge.icloud.apple-dns.net
play.itunes.apple.com
api.smoot.apple.com
p08-keyvalueservice-current.edge.icloud.apple-dns.net
p08-bookmarks.icloud.com
a4.da1.akamai.net
a5.da1.akamai.net
a3.mzstatic.com
a2.mzstatic.com

Will investigate more tomorrow.

**Comment by i37** [comment]
BTW - on my second apple tv I'm getting auth failure when loading that same title that is crashing my other apple tv now. It looks like it tried to connect to nflximg.net before auth failure.

**Comment by ab77** [comment]
OK, I've added `huluim.com` domain during this last last update, for posterity. I would do a full factory reset on that ATV and upgrade to latest firmware first and then do some testing with/without the custom DNS to see how it behaves. The device shouldn't spontaneously reboot in either case.

**Comment by ab77** [comment]
I am going to close this, please re-open if you discover anything new.
