### ISSUE TITLE
Problems with custom accounts

### ISSUE THREAD

**Issue by kyle95wm** [ab77/netflix-proxy#134]
Okay so I created a little shell script:

    #!/bin/bash
    USERNAME=
    PASSWORD=
    EXPIRES=
    PRIVILEGE=
    BUILD_ROOT=/opt/netflix-proxy
    SQLITE_DB=${BUILD_ROOT}/auth/db/auth.db

    echo "This script will assist in creating new users for the netflix-proxy admin page"
    echo "Please answer the following questions:"

    read -p "Please enter a username: " USERNAME
    read -p "Please enter a password: " PASSWORD
    read -p "Expiry date? (YYYY-MM-DD): " EXPIRES
    read -p "Please specify a PRIVILEGE level (0=user 1=admin): " PRIVILEGE

    pushd ${BUILD_ROOT} && \
      export HASH=`${BUILD_ROOT}/auth/pbkdf2_sha256_hash.py ${PASSWORD}` && \
      sqlite3 ${SQLITE_DB} "INSERT INTO USERS (privilege, expires, username, password) VALUES (${PRIVILEGE}, '${EXPIRES}', '${USERNAME}', '${HASH}');" && \
      popd

Anyways, TLDR, my "username" user with password "password" isn't working on the admin page. What did I miss?

**Comment by kyle95wm** [comment]
Okay so after trying something I got it working. I had to open the sql file and remove the "password" clear text above the hash:

so, 

password $pbkdf2-sha256$200000$2zuHEMLYG2OM0XqPkVIqBQ$B2txIHGVsT7pPjIJWMoXZfbD8Iy68XXqzTYdb11gSNc

has to be
$pbkdf2-sha256$200000$2zuHEMLYG2OM0XqPkVIqBQ$B2txIHGVsT7pPjIJWMoXZfbD8Iy68XXqzTYdb11gSNc

After that it works. This issue should still be opened, because I'm convinced there's a fix in order here. Not everyone feels like SFTP'ing into their server to edit the file themselves.

**Comment by ab77** [comment]
Fixed.

**Comment by kyle95wm** [comment]
Thanks. May wanna add a few words to the README.md about this.

**Comment by 0x4139** [comment]
` sqlite3 /root/netflix-proxy/auth/db/auth.db ` after that `UPDATE users SET password='admin' where ID =1;` and you can login with user admin and password admin
