### ISSUE TITLE
Problems Getting US Netflix as of tonight

### ISSUE THREAD

**Issue by kyle95wm** [ab77/netflix-proxy#138]
Okay so long story short, I was going to watch the series finale of Terra Nova. Whenever I go into Netflix I'm greeted by the Canadian version of the site. My DNS is setup properly, I've rebooted my computer and my TV as well as my game console, Ive done a "dig" when using the DNS and all comes back normal, or so I think.

What's going on here? 45.55.155.173 is my server IP. Feel free to provide me with a public key and I'll add it to my server the next time I'm on. I'm really confused as to why it was working today and now it's not.

**Comment by vango44** [comment]
Still working for me on my ipad.
Built with Digital Ocean on NY3 server.
This build is a couple weeks old already (first version using tunnel)

**Comment by kyle95wm** [comment]
I built mine the other night, then later yesterday (Monday) it jus stopped working.

**Comment by ab77** [comment]
Works fine. There may be network congestion, causing time-outs in your specific case. Try a different DC (doesn't have to be US) and also a different tunnel server.

**Comment by WeirdG** [comment]
Was still working for me last night.  I did my usual Star Trek DS9 test.

**Comment by kyle95wm** [comment]
Alright I rebuilt using the MASTER branch (the new tests branch git clone URL isn't the right one - might wanna fix that) and chose another tunnel on the website and it works (it takes a bit longer than usual to load Netflix for some reason)
