### ISSUE TITLE
Script dropping out ?

### ISSUE THREAD

**Issue by cjrowson** [ab77/netflix-proxy#139]
Hi Guys, 

I might be doing something completely stupid - but i think the install script is dropping out ?

Step 8 makes mention of the URL and U/P for the admin site ?

root@ubuntu-512mb-nyc3-01:~# git clone https://github.com/ab77/netflix-proxy /opt/netflix-proxy && cd /opt/netflix-proxy && ./build.sh -u ***********-p **********
Cloning into '/opt/netflix-proxy'...
remote: Counting objects: 2140, done.
remote: Compressing objects: 100% (180/180), done.
remote: Total 2140 (delta 109), reused 0 (delta 0), pack-reused 1957
Receiving objects: 100% (2140/2140), 3.58 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1252/1252), done.
Checking connectivity... done.
resolved params: clientip=1.1.1.1 ipaddr=2.2.2.2 extip=3.3.3.3
cmd: ./build.sh -r=1 -b=0 -s= -z=0 -n=1 -u=******** -p [secret] -k [secret]

 * disabling native IPv6 on eth0...                                                                                                                                       [ OK ]
 * installing XPath...                                                                                                                                                    [ OK ]
 * enabling he-ipv6 interface...                                                                                                                                          [ OK ]
 * bringing up IPv6 tunnel...                                                                                                                                             [ OK ]
 * testing IPv6 tunnel (this may take a while)...                                                                                                                         [ OK ]
 * enabling DNS recursion...                                                                                                                                              [ OK ]
 * authorising clientip=202.161.108.6 on iface=eth0...                                                                                                                    [ OK ]
 * adding IPv4 iptables rules...                                                                                                                                          [ OK ]
 * creating Docker and sniproxy configuration templates...                                                                                                                [ OK ]
 * checking IPv6 connectivity...                                                                                                                                                 
 * enabling sniproxy IPv6 priority...                                                                                                                                     [ OK ]
 * installing sipcalc...                                                                                                                                                  [ OK ]
 * enabling Docker IPv6 dual-stack support with fixed-cidr-v6=2001:470:d:a1f::/64...                                                                                      [ OK ]
 * adding IPv6 iptables rules...                                                                                                                                          [ OK ]
 * installing iptables|netfilter-persistent service...                                                                                                                    [ OK ]
 * socialising Docker with iptables-persistent service...                      
                                                                                                
-------------------------------------------------------------

**Comment by ab77** [comment]
Have a look what's in the `netflix-proxy.log` file towards the end..

**Comment by cjrowson** [comment]
DOCKER_OPTS='--iptables=false --ipv6 --fixed-cidr-v6="11111111111"'
Reading package lists...
Building dependency tree...
Reading state information...
iptables-persistent is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 27 not upgraded.
/bin/sed: can't read /etc/init/docker.conf: No such file or directory

So i`m assuming i need to install docker before running starting to run git clone ?

**Comment by kyle95wm** [comment]
What provider are you using? If DO, then Docker should've already been installed

**Comment by cjrowson** [comment]
Its DO. clean droplet with only apt-get update & apt-get install git being run before the git pull.
"512 MB Memory / 20 GB Disk / NYC3 - Ubuntu 14.04.4 x64"

**Comment by cjrowson** [comment]
Forgive my stupidity... Its working ! 
Thankyou for your very quick reply.
