### ISSUE TITLE
www.netflix.com sloow loading

### ISSUE THREAD

**Issue by lowprofileusername** [ab77/netflix-proxy#140]
Hi,
Thanks for the project. I set up dns (Digital Ocean SFO) on my machine(France). Everything is smooth. Pandora.com. spotify. ipinfo.io. pages loads in just few seconds. However when I try to open netflix.com something it will just stuck on loading page. no respone for a long time and suddently the netflix.com webpage loads. What do you think is the key issue that cause this problem? Thanks

**Comment by lowprofileusername** [comment]
However when I use the proxy I setup on the dns server(digital ocean SFO). netflix.com open in just seconds. Weird issue.

**Comment by ab77** [comment]
You may find rebuilding in a different DC, using a different tunnel server (you can have a max of 5) at a different time of day will sort this issue out. I believe it to be congestion at different points along the path.

**Comment by ab77** [comment]
Please re-open if still having issues..
