### ISSUE TITLE
when build, it exits on linode box

### ISSUE THREAD

**Issue by goog** [ab77/netflix-proxy#142]
```bash
root@qamain:/opt/netflix-proxy# ./build.sh -u googcheng -p abcdef
resolved params: clientip= ipaddr=103.3.60.141 extip=103.3.60.141
cmd: ./build.sh -r=1 -b=0 -s= -z=0 -n=1 -u=googcheng -p [secret] -k [secret]

 * disabling native IPv6 on eth0...                                                                                                                                   [ OK ] 
 * installing XPath...                                                                                                                                                [ OK ] 
 * enabling he-ipv6 interface...                                                                                                                                      [ OK ] 
 * bringing up IPv6 tunnel...                                                                                                                                         [ OK ] 
 * testing IPv6 tunnel (this may take a while)...   
```

then it returns to terminal

**Comment by ab77** [comment]
As it says in the readme, it has never been tested it on Linode. Please provide `netflix-proxy.log`, which may help in troubleshooting this issue..

**Comment by goog** [comment]
Setting up libxml-xpath-perl (1.13-7) ...
source-directory interfaces.d
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   320  100   320    0     0    364      0 --:--:-- --:--:-- --:--:--   364
<?xml version="1.0" encoding="UTF-8"?>
<tunnels>
 <tunnel id="331046">
  <description></description>
  <serverv4>74.82.46.6</serverv4>
  <clientv4>103.3.60.141</clientv4>
  <serverv6>2001:470:23:c51::1</serverv6>
  <clientv6>2001:470:23:c51::2</clientv6>
  <routed64>2001:470:24:c51::/64</routed64>
 </tunnel>
</tunnels>auto he-ipv6
iface he-ipv6 inet6 v4tunnel
        address 2001:470:23:c51::2
        netmask 64
        endpoint 74.82.46.6
        local 103.3.60.141
        ttl 255
        gateway 2001:470:23:c51::1
RTNETLINK answers: Permission denied
Failed to bring up he-ipv6.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Couldn't connect to server
net.ipv6.conf.eth0.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6=1
net.ipv4.ip_forward = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
Reading package lists...
Building dependency tree...
Reading state information...
libxml-xpath-perl is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
source-directory interfaces.d
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   320  100   320    0     0    387      0 --:--:-- --:--:-- --:--:--   387
<?xml version="1.0" encoding="UTF-8"?>
<tunnels>
 <tunnel id="331046">
  <description></description>
  <serverv4>74.82.46.6</serverv4>
  <clientv4>103.3.60.141</clientv4>
  <serverv6>2001:470:23:c51::1</serverv6>
  <clientv6>2001:470:23:c51::2</clientv6>
  <routed64>2001:470:24:c51::/64</routed64>
 </tunnel>
</tunnels>auto he-ipv6
iface he-ipv6 inet6 v4tunnel
        address 2001:470:23:c51::2
        netmask 64
        endpoint 74.82.46.6
        local 103.3.60.141
        ttl 255
        gateway 2001:470:23:c51::1
add tunnel "sit0" failed: No buffer space available
Failed to bring up he-ipv6.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Couldn't connect to server
net.ipv6.conf.eth0.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6=1
net.ipv4.ip_forward = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
Reading package lists...
Building dependency tree...
Reading state information...
libxml-xpath-perl is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
source-directory interfaces.d
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   320  100   320    0     0    394      0 --:--:-- --:--:-- --:--:--   393
<?xml version="1.0" encoding="UTF-8"?>
<tunnels>
 <tunnel id="331046">
  <description></description>
  <serverv4>74.82.46.6</serverv4>
  <clientv4>103.3.60.141</clientv4>
  <serverv6>2001:470:23:c51::1</serverv6>
  <clientv6>2001:470:23:c51::2</clientv6>
  <routed64>2001:470:24:c51::/64</routed64>
 </tunnel>
</tunnels>auto he-ipv6
iface he-ipv6 inet6 v4tunnel
        address 2001:470:23:c51::2
        netmask 64
        endpoint 74.82.46.6
        local 103.3.60.141
        ttl 255
        gateway 2001:470:23:c51::1
add tunnel "sit0" failed: No buffer space available
Failed to bring up he-ipv6.

**Comment by ab77** [comment]
Information is lost due to formatting. Can you pastebin it please, or enclose the output properly using three backtics.

**Comment by ab77** [comment]
But your issue is probably to do with:

```
add tunnel "sit0" failed: No buffer space available
Failed to bring up he-ipv6.
```

Make sure to remove all native IPv6 connectivity from the public network interface before you begin running in tunnel mode. If you can `ping6 google.com` form a fresh Linode install, do not proceed until native IPv6 is disabled.
