### ISSUE TITLE
Netflix US no longer working

### ISSUE THREAD

**Issue by Thinge** [ab77/netflix-proxy#143]
I had it working last week, but this week it no longer works as a way of accessing Netflix US in the UK. I've set up three different droplets on Digital Ocean from scratch and haven't had any luck. All instructions followed as I did originally (and deleting all existing tunnels & droplets). The DNS appears to work, but when I open the Netflix app it just shows me the UK version. No errors whatsoever at any point, just no longer showing me the US version, despite the Droplets being in New York or San Francisco. Also, I can confirm visiting ipinfo.io on the device (PS3) shows the New York IP (not my UK IP).

**Comment by ab77** [comment]
I am pretty sure this can be closed now :grimacing:
