### ISSUE TITLE
An approach to unblocking UK and US?

### ISSUE THREAD

**Issue by elbow** [ab77/netflix-proxy#144]
Hi,

I installed netflix-proxy on a Digital Ocean Droplet in the UK.  That's "closest" to me and I also thought it would help me access iPlayer.

I followed the setup README and therefore have a native IPv4 address that is in the UK and then an ipv6 address via the tunnel.

This works for Netflix - I didn't look in detail but I assume that sniproxy is proxying to/from Netflix via the ipv6 tunnel.

It work for iPlayer too - using tcpdump I see the media traffic coming from Akamai's CDN to my Droplet and then out to my client.

But Amazon isn't convinced - and I feel like I'm missing something....  I guess Amazon Video doesn't use ipv6 so they are seeing my ipv4 address which is geolocated in the UK.  So I'm not surprised that they block me.

Do I need a further ipv4 tunnel to the US in order to also have a US ipv4 address?  What do you suggest?

Thanks,
Elbow

**Comment by ab77** [comment]
Yes, you've done everything correctly for Netflix and iPlayer. If you wanted to proxy other services, like Amazon, which don't use IPv6, you will need to have a second netflix-proxy instance deployed to a US server. This one can just be IPv4 only, although if you set it up for IPv6 (with a second tunnel), you'll have backup in case the UK one goes down.

**Comment by elbow** [comment]
Hi,  Thanks for the reply.

I made a US Droplet and installed netflix-proxy.

As I see it now I have to configure the zone files on the US instance to point proxy iPlayer via the sniproxy in the UK, and the zone files on the UK instance to use the US sniproxy.

Looks like I need to split db.override into two files on each box - one for domains that must use the US proxy and one for those needing the UK proxy.

Am I on the right track?

Do I need to do something special to allow my home IP to access both proxies, or is that just a matter of authorising on both installs?

Thanks,
Elbow

**Comment by elbow** [comment]
Well - seems to work great.

I made a db.override.uk and db.override.us and modified the zones.override to use the zone file that seemed appropriate for the domain.  Synced up the changes on both droplets.

Thanks for the code and the assistance.

Elbow

**Comment by ab77** [comment]
No problem, great work!

Cheers,
-- ab1
