### ISSUE TITLE
Still getting proxy errors

### ISSUE THREAD

**Issue by elhu** [ab77/netflix-proxy#145]
Hello!

First of all, thanks for the great tool! Installation was a breeze, but I still get errors from Netflix detecting I'm behind a proxy.
As far as I can tell, I've done everything correctly (http://ipinfo.io/ shows the IP of my digital ocean droplet in the NY3 zone).
One thing I'm not a 100% sure off is whether or not I correctly whitelisted my IP addresses on the proxy admin interface (I can just keep adding the same, but I don't see a list of whitelisted IPs anywhere).

Is there any log file I could use to diagnose what the problem actually is?

Thanks a lot :)!

**Comment by ab77** [comment]
You could look at the `netlfix-proxy.log` to see what (if any) errors are present.

Ultimately it will most likely come down to IPv6 tunnel configuration. Do you get IPv6=Enabled or Disabled at the end of the build?

**Comment by elhu** [comment]
I got the following at the end of the script:

```
netflix-proxy-admin site=http://XXX.XXX.XXX.XXX:8080/ credentials=admin:REDACTED
WARNING: IPv6=Disabled
caching-resolver=Disabled
Hulu region(s) available to you: {'JP': false, 'US': true}
Change your DNS to XXX.XXX.XXX.XXX and start watching Netflix out of region.
Done!
```

No error as far as I can tell in netflix-proxy.log.

When I created the tunnel, I chose France as the location as it is the closest to me.
When I check the configuration of the tunnel on https://tunnelbroker.net, I see the IPv4 of my droplet in the Client section of the tunnel info.

If it's easier for you, I'm on IRC.

**Comment by elhu** [comment]
Thank you very much for your help, it's working now!
