### ISSUE TITLE
Possible updater?

### ISSUE THREAD

**Issue by kyle95wm** [ab77/netflix-proxy#146]
So I've been seeing a lot of commits here lately and am beginning to wonder if I'm missing out on anything earth shattering. It would be nice to have an updater script of sorts that way we don't have to keep rebuilding every time.

**Comment by ab77** [comment]
You are treating your servers as snow flakes. Every single one is unique.

My advice - don't do that. Assume they are all throw aways which can be destroyed and rebuilt from scratch.

Your life will be a lot happier if you follow this approach.

Cheers!
