### ISSUE TITLE
Netflix ok, hulu not ok

### ISSUE THREAD

**Issue by aminbolehvpn** [ab77/netflix-proxy#149]
I have setup the server correctly on native ipv6 and can view netflix without any issues but still face a proxy error for hulu. I was told that there are a few specific ip belonging to google that can cause this and one of them is google dns, 8.8.8.8/8.8.4.4. I noticed that google dns is being used as the recursive dns. Is it possible to install unbound outside of docker (in the vps main service) and use that as the recursive dns instead of google? Which file do I need to change if I want to use unbound as my recursive dns?

Thank you

**Comment by ab77** [comment]
It doesn't matter which DNS server you use, if your provider's IP is blacklisted by Hulu (most are), then you won't be able to watch it.

You need to find a provider that they haven't blacklisted yet and deploy on to that. No IPv6 is required, because Hulu doesn't use it.
