### ISSUE TITLE
VPS and Tunnel location

### ISSUE THREAD

**Issue by vango44** [ab77/netflix-proxy#150]
In the setup instructions it says to pick VPS/tunnel closest to me but I thought I needed to pick US?

I have a DO VPS on NY2 and tunnel through Denver but still flagged by Netflix. Should I be trying new VPS location or tunnel or both?

Which IP is actually exposed to Netflix?

Btw, thanks for your work on this!

Update: Seems it works at home but not from work. Is there a cfg file that holds the authorized IP's I can check? It does show correct location on ipinfo when I check from work.

**Comment by vango44** [comment]
Here's a traceroute to google:
`root@docker-512mb-nyc2-01:~# traceroute6 google.com
traceroute to google.com (2607:f8b0:4006:80e::200e) from 2001:470:39:438::2, 30 hops max, 24 byte packets
 1  44vango-1.tunnel.tserv1.den1.ipv6.he.net (2001:470:39:438::1)  41.515 ms  40.928 ms  40.876 ms
 2  ge3-20.core1.den1.he.net (2001:470:0:24b::1)  40.358 ms  45.955 ms  49.749 ms
 3  2605:6c00:303:303::3 (2605:6c00:303:303::3)  62.515 ms  62.322 ms  62.43 ms
 4  2001:4860::1:0:8831 (2001:4860::1:0:8831)  62.689 ms  62.505 ms  62.688 ms
 5  2001:4860::8:0:79e5 (2001:4860::8:0:79e5)  61.928 ms  61.96 ms  61.97 ms
 6  2001:4860::8:0:b0e3 (2001:4860::8:0:b0e3)  62.761 ms  77.004 ms  62.792 ms
 7  2001:4860::8:0:833f (2001:4860::8:0:833f)  62.326 ms  62.721 ms  62.557 ms
 8  2001:4860::8:0:4397 (2001:4860::8:0:4397)  78.315 ms  78.339 ms  78.269 ms
 9  2001:4860::1:0:6572 (2001:4860::1:0:6572)  78.757 ms  78.865 ms  78.627 ms
10  2001:4860:0:1::12d3 (2001:4860:0:1::12d3)  79.473 ms  79.54 ms  79.349 ms
11  lga25s40-in-x0e.1e100.net (2607:f8b0:4006:80e::200e)  79.197 ms  79.325 ms  79.183 ms
root@docker-512mb-nyc2-01:~#
`
Also, when I check data usage it doesn't seem to be using the tunnel. Is that normal?
![vnstat](https://cloud.githubusercontent.com/assets/18278026/14583660/e11c3bc0-03ed-11e6-98b6-1bd8f1e5fe86.JPG)

**Comment by ab77** [comment]
I've noticed that some tunnels are being flagged by Netflix as proxies. I've not looked into this a great deal, but if this is the case, that means they've started (selectively) blocking HE IPv6 ranges. My old tunnels seem to work, while new tunnels don't seem to.

The IP exposed to Netflix is a random address in the IPv6 routed /64 prefix. This will be randomised every time SNIProxy container is started.

You will need to authorise your work IP by hitting the web interface on :8080.

**Comment by vango44** [comment]
Ok thanks. Strangely, it now seems to work again for me. 

Thanks again for the info.

**Comment by zhangdailin** [comment]
```
root@sheldon:~# traceroute6 netflix.com
traceroute to netflix.com (2620:108:700f::36f4:f112) from 2001:470:1f18:25b::2, 30 hops max, 24 byte packets
 1  daige12-1.tunnel.tserv1.phx2.ipv6.he.net (2001:470:1f18:25b::1)  1.599 ms  1.072 ms  0.909 ms
 2  ge11-2.core1.phx2.he.net (2001:470:0:2b9::1)  2.828 ms  3.018 ms  0.586 ms
 3  100ge11-2.core1.lax2.he.net (2001:470:0:362::1)  9.323 ms  9.673 ms  16.075 ms
 4  100ge2-1.core1.lax1.he.net (2001:470:0:72::1)  9.632 ms  18.554 ms  9.708 ms
 5  asn-qwest-us-as209.10gigabitethernet5-5.core1.lax1.he.net (2001:470:0:2c0::2)  9.76 ms  9.748 ms  9.513 ms
 6  2001:428::205:171:3:199 (2001:428::205:171:3:199)  17.37 ms  17.246 ms  17.541 ms
 7  2001:428:7000:10:0:15:0:2 (2001:428:7000:10:0:15:0:2)  17.682 ms  17.459 ms  17.385 ms
 8  2620:107:3000::c (2620:107:3000::c)  37.849 ms  38.765 ms  37.192 ms
 9  2620:107:3000::e (2620:107:3000::e)  37.56 ms  37.304 ms  37.048 ms
10  2620:108:7000::6 (2620:108:7000::6)  42.108 ms  37.677 ms  37.107 ms
11  2620:108:7000::4 (2620:108:7000::4)  37.754 ms  37.108 ms  37.477 ms
12  2620:108:7000::7 (2620:108:7000::7)  37.113 ms  36.991 ms  36.766 ms
13  2620:108:7000::2 (2620:108:7000::2)  36.433 ms  36.347 ms  37.771 ms
14  2620:107:4000:4200:8000:0:6440:109c (2620:107:4000:4200:8000:0:6440:109c)  37.28 ms  36.975 ms  36.831 ms
15  2620:107:4000:4200::6440:22d5 (2620:107:4000:4200::6440:22d5)  37.061 ms  37.41 ms  37.119 ms
16  2620:107:4000:4200::6440:229d (2620:107:4000:4200::6440:229d)  37.773 ms  37.653 ms  37.854 ms
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
```
