### ISSUE TITLE
how to use my native ipv6???

### ISSUE THREAD

**Issue by zhangdailin** [ab77/netflix-proxy#151]
i think netflix blocked the tunnel's ip in usa, and shows proxy detected "you seem to be using an unblocker or peoxy.Please turn off any of those service and try again....." 
i want to use my native ipv6 to try i again, what i need to do

**Comment by zhangdailin** [comment]
and the hulu shows that" The operation couldn't be completed.(HUDeejayErrorDomain error 15.)

**Comment by kyle95wm** [comment]
No problems here. My usual Star Trek DS9 test works. Maybe I'm just lucky?

**Comment by zhangdailin** [comment]
which tunnel's line???

**Comment by zhangdailin** [comment]
Fremont, CA, US 64.62.134.130
Phoenix, AZ, US 66.220.7.82
i have tried these

**Comment by zhangdailin** [comment]
i have tried digitalocean and other provider like RamNode , all of them cannot work

**Comment by aminbolehvpn** [comment]
Most of the cloud and vps are blacklisted. You will be lucky to find one that can work for hulu. Even google cloud and amazon ecs are no longer working.

**Comment by ab77** [comment]
Destroy and rebuild if you want native IPv6. Build the server with provider's ipv6 support and run `build.sh` without username/password flags.
