### ISSUE TITLE
testing proxy (OpenSSL)

### ISSUE THREAD

**Issue by paranoidjack** [ab77/netflix-proxy#152]
Host: Vultr

The script hangs and terminates at: testing proxy (OpenSSL)

Pinging (v4) netflix.com from the VPS results in a timeout which seems to be the issue - this is even before the script is installed.

**Comment by zhangdailin** [comment]
you are unlucky netflix has blocked he tunnel's ip

**Comment by paranoidjack** [comment]
I don't believe it's the tunnel because I can ping6 netflix.com after the script has terminated. 

Log: http://pastebin.com/0dveq62q

**Comment by zhangdailin** [comment]
do you success???
