### ISSUE TITLE
Ignoring unknown interface he-ipv6=he-ipv6.

### ISSUE THREAD

**Issue by rafael31** [ab77/netflix-proxy#155]
i'm having this problem.
Ignoring unknown interface he-ipv6=he-ipv6.
curl: (7) Failed to connect to 2620:108:700f::36f5:fc55: Network is unreachable

I use a VM of 123systems openVZ, can you help me?

**Comment by ab77** [comment]
It won't work on OpenVZ, your need a proper virtual machine (e.g. KVM or Zen).
