### ISSUE TITLE
Question about the zones.override file

### ISSUE THREAD

**Issue by ogdans3** [ab77/netflix-proxy#158]
```
zone "nflxvideo.net." {
    type master;
    file "/data/conf/db.override";
};
```

Is it not correct that nflxvideo.net is the CDN for netflix?
Why is it redirected to the sniproxy, if i try to remove it and go back to www.netflix.com it gets stuck in a redirect loop

**Comment by ab77** [comment]
Sound like you've got a DNS miss-configuration somewhere.

**Comment by ogdans3** [comment]
Thanks for the fast response!

Just to specify, I do not use dnsmasq.

But in the configuration form github the zone "nflxvideo.net" is also specified.
It works fine if I do not remove that entry, but when I remove it I am stuck in a redirect loop.

I was just wondering why that entry is present in the configuration from github.

**Comment by ab77** [comment]
Why are you removing it? You need to proxy both media and API/web traffic in order to bypass Netflix proxy blocks..

**Comment by ogdans3** [comment]
I was reading some previous assues:
https://github.com/ab77/netflix-proxy/issues/53#issuecomment-172531026 
Here you say that you should not forward requests from nflxvideo.net.

Wouldnt removing it from the zone file achieve the same effect?

**Comment by ab77** [comment]
Well, if you want to unblock Netflix now (and not back in January), you need to proxy `nflxvideo.net` traffic as well. So, if it is working for you, just leave it in there. Please close if this sorts out your issue..

**Comment by ogdans3** [comment]
Does that mean that all the traffic needs to go through the VPS? Meaning it will basically be a proxy for all the traffic?

**Comment by ab77** [comment]
For Netflix media traffic, yes.

**Comment by ogdans3** [comment]
Alright, thanks
