### ISSUE TITLE
Script fails to complete?

### ISSUE THREAD

**Issue by mike548141** [ab77/netflix-proxy#159]
Following your instructions I get the following, I think the script is not completing properly (username, password and IP's sanitised).
`root@docker:~# 
root@docker:~# ping6 netflix.com
connect: Network is unreachable
root@docker:~# git clone https://github.com/ab77/netflix-proxy /opt/netflix-proxy && cd /opt/netflix-proxy && ./build.sh -u [my username] -p [my password]
Cloning into '/opt/netflix-proxy'...
remote: Counting objects: 2894, done.
remote: Compressing objects: 100% (115/115), done.
remote: Total 2894 (delta 47), reused 0 (delta 0), pack-reused 2769
Receiving objects: 100% (2894/2894), 51.82 MiB | 20.11 MiB/s, done.
Resolving deltas: 100% (1573/1573), done.
Checking connectivity... done.
resolved params: clientip=1.2.3.4 ipaddr=2.3.4.5 extip=2.3.4.5
cmd: ./build.sh -r=1 -b=0 -s= -z=0 -n=1 -u=[my username] -p [secret] -k [secret]

 * disabling native IPv6 on eth0...                                                                                                                      [ OK ] 
 * installing XPath...                                                                                                                                   [ OK ] 
 * enabling he-ipv6 interface...                                                                                                                         [ OK ] 
 * bringing up IPv6 tunnel...                                                                                                                            [ OK ] 
 * testing IPv6 tunnel (this may take a while)...                                                                                                        [ OK ] 
 * enabling DNS recursion...                                                                                                                             [ OK ] 
 * authorising clientip=1.2.3.4 on iface=eth0...                                                                                                  [ OK ] 
 * adding IPv4 iptables rules...                                                                                                                         [ OK ] 
 * creating Docker and sniproxy configuration templates...                                                                                               [ OK ] 
 * checking IPv6 connectivity...                                                                                                                                 
 * enabling sniproxy IPv6 priority...                                                                                                                    [ OK ] 
 * installing sipcalc...                                                                                                                                 [ OK ] 
 * enabling Docker IPv6 dual-stack support with fixed-cidr-v6=1:2:3:4::/64...                                                                  [ OK ] 
 * adding IPv6 iptables rules...                                                                                                                         [ OK ] 
 * installing iptables|netfilter-persistent service...                                                                                                   [ OK ] 
 * socialising Docker with iptables-persistent service...                                                                                                [ OK ] 
 * updating iptables-persistent init script...                                                                                                           [ OK ] 
 * saving iptables rules...                                                                                                                              [ OK ] 
 * creating zones.override from template...                                                                                                              [ OK ] 
 * updating db.override with extip=2.3.4.5 and date=20160427...                                                                                   [ OK ] 
 * installing python-pip and docker-compose...                                                                                                           [ OK ] 
 * configuring netflix-proxy-admin backend...                                                                                                            [ OK ] 
 * configuring netflix-proxy-admin reverse-proxy...                                                                                                      [ OK ] 
 * creating and starting Docker containers...                                                                                                            [ OK ] 
 * configuring upstart...                                                                                                                                [ OK ] 
 * reloading ipables rules...                                                                                                                            [ OK ] 
 * no specific steps to execute for Ubuntu at this time...                                                                                               [ OK ] 
 * testing DNS...                                                                                                                                        [ OK ] 
 * testing proxy (OpenSSL)...                                                                                                                                   
root@docker:/opt/netflix-proxy# 
`

**Comment by kyle95wm** [comment]
I looked at the readme and the build status has failed. @ab77 please look into this.

**Comment by ab77** [comment]
@mike548141: try creating a tunnel in another location. I've seen this happen from time to time due to congestion.

**Comment by mike548141** [comment]
I created another docker image in a different data centre and a new tunnel in a new region and the script completed properly, it is working now thanks

**Comment by ab77** [comment]
Good work!

**Comment by zlo29a** [comment]
same issue.
