### ISSUE TITLE
DNS on Digitalocean droplet stops working after a day

### ISSUE THREAD

**Issue by hmrtk** [ab77/netflix-proxy#16]
I have been playing around with Netflix-proxy for a week. I noticed that after setting up the droplet, it would stop working in less than a day. I haven't really investigated why this happens and instead I just destroy the droplet and create a new one. 

Is this expected? Or have I missed an instruction somewhere? 

For now I am relying on a Vagrantfile that I have put together [here](https://github.com/hmrtk/vagrant-digitalocean-netflix-dns-proxy) that would save me some time creating and destroying the droplet.

**Comment by ab77** [comment]
Does your public IP address change often? The build script configured iptables firewall to allow your IP address at build time, if it changes afterwards, you'll need to either re-create the VPS or update your iptables rules.

I am planning to add some logic to automate this as much as possible, but in the meantime, if this is your problem, you could try dynamic DNS solution I described [here](https://github.com/ab77/netflix-proxy/issues/9#issuecomment-117580338).

-- ab1

**Comment by hmrtk** [comment]
The public IP address doesn't change. I just verified. I created this particular droplet 17 hours ago and now its not functional. I can provide logs here if that helps.

**Comment by ab77** [comment]
Very weird, please do..

**Comment by hmrtk** [comment]
Is there any particular log file that could help?

**Comment by ab77** [comment]
Let's start with the full output of the `build.sh` run, together with `dig netflix.com; dig google.com` from your local PC at home as well as `dig netflix.com; dig google.com` from your local PC after it stops working.

-- ab1

**Comment by hmrtk** [comment]
The full out put of build.sh is here on [pastebin](http://pastebin.com/40Fa3V6Z)
## Running Locally without setting DNS Proxy

; <<>> DiG 9.8.3-P1 <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29766
;; flags: qr rd ra; QUERY: 1, ANSWER: 11, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		204	IN	A	74.125.226.130
google.com.		204	IN	A	74.125.226.132
google.com.		204	IN	A	74.125.226.131
google.com.		204	IN	A	74.125.226.142
google.com.		204	IN	A	74.125.226.134
google.com.		204	IN	A	74.125.226.128
google.com.		204	IN	A	74.125.226.133
google.com.		204	IN	A	74.125.226.135
google.com.		204	IN	A	74.125.226.136
google.com.		204	IN	A	74.125.226.137
google.com.		204	IN	A	74.125.226.129

;; Query time: 47 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Sun Aug  9 16:43:54 2015
;; MSG SIZE  rcvd: 204


## Running Locally after setting DNS proxy (at this point its now working)
; <<>> DiG 9.8.3-P1 <<>> netflix.com
;; global options: +cmd
;; connection timed out; no servers could be reached

**Comment by ab77** [comment]
Seems OK. Next, what is in `/etc/iptables/rules.v4`?

**Comment by hmrtk** [comment]
I setup the netflix-proxy on a new droplet 3 days ago. This time it lasted for 3 days and it just stopped working. I am going to put the Build.sh output and /etc/iptables/rules.v4 here:

### build.sh output
http://pastebin.com/DUL4PVsF

### /etc/iptables/rules.v4
```
# Generated by iptables-save v1.4.21 on Sun Aug  9 22:24:35 2015
*nat
:PREROUTING ACCEPT [2:128]
:INPUT ACCEPT [2:128]
:OUTPUT ACCEPT [71:5252]
:POSTROUTING ACCEPT [71:5252]
:DOCKER - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
COMMIT
# Completed on Sun Aug  9 22:24:35 2015
# Generated by iptables-save v1.4.21 on Sun Aug  9 22:24:35 2015
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [50:5063]
:DOCKER - [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -s 69.165.134.161/32 -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -s 69.165.134.161/32 -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
-A DOCKER -m state --state RELATED,ESTABLISHED -j ACCEPT
-A DOCKER -p icmp -j ACCEPT
-A DOCKER -s 69.165.134.161/32 -p udp -m udp --dport 53 -j ACCEPT
-A DOCKER -j REJECT --reject-with icmp-host-prohibited
COMMIT
# Completed on Sun Aug  9 22:24:35 2015
```

**Comment by ab77** [comment]
When it stops working and you've made absolutely sure your current public IP (Google `what is my ip`) is the same address as in the `/etc/iptables/rules.v4` on your Droplet, check if your Docker containers are still running: `docker ps -a` and if so, try doing testing it locally from your Droplet.

    dig netflix.com; "GET /" | openssl s_client -servername netflix.com -connect 104.131.12.106:443

-- ab1

**Comment by michaelhodges** [comment]
did you get this working?

i've noticed that the bind docker doesn't open port 53 on ipv4 anymore.

lsof -i 
shows only ipv6 open for port 53

mh

**Comment by ab77** [comment]
I just built an IPv4 only Droplet for a test and even though `lsof -i` doesn't show IPv4 domain socket, it is still is listening on IPv4. So my test is working as expected.

I think the host OS is getting confused by the docker-proxy, which is the bit that passes traffic between the host and the containers. The sniproxy container is configured to bypass this proxy all together and uses host OS networking, which is why it is showing up in the list, however the BIND DNS container still uses the docker-proxy.

-- ab1

**Comment by hmrtk** [comment]
I double checked again, my droplet's public IP address is still the same as the one that was returned after running build.sh (that is 45.55.83.199)

However, I could not find any occurences of my IP address in  `/etc/iptables/rules.v4`
```
# Generated by iptables-save v1.4.21 on Wed Aug 12 22:37:36 2015
*nat
:PREROUTING ACCEPT [2:128]
:INPUT ACCEPT [2:128]
:OUTPUT ACCEPT [91:6879]
:POSTROUTING ACCEPT [91:6879]
:DOCKER - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
COMMIT
# Completed on Wed Aug 12 22:37:36 2015
# Generated by iptables-save v1.4.21 on Wed Aug 12 22:37:36 2015
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [42:4423]
:DOCKER - [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -s 206.248.158.148/32 -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -s 206.248.158.148/32 -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
-A DOCKER -m state --state RELATED,ESTABLISHED -j ACCEPT
-A DOCKER -p icmp -j ACCEPT
-A DOCKER -s 206.248.158.148/32 -p udp -m udp --dport 53 -j ACCEPT
-A DOCKER -j REJECT --reject-with icmp-host-prohibited
COMMIT
# Completed on Wed Aug 12 22:37:36 2015
```

Running `docker ps -a`:

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                NAMES
9a63decab6f5        ab77/sniproxy       "/usr/sbin/sniproxy -"   5 days ago          Up 5 days                                sniproxy
cc0231e8c8a6        ab77/bind           "/usr/sbin/named -u n"   5 days ago          Up 5 days           0.0.0.0:53->53/udp   bind
```

Running `dig netflix.com; "GET /" | openssl s_client -servername netflix.com -connect 104.131.12.106:443`

```
; <<>> DiG 9.9.5-3ubuntu0.4-Ubuntu <<>> netflix.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51028
;; flags: qr rd ra; QUERY: 1, ANSWER: 12, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;netflix.com.			IN	A

;; ANSWER SECTION:
netflix.com.		5	IN	A	54.204.2.219
netflix.com.		5	IN	A	54.204.43.31
netflix.com.		5	IN	A	54.225.192.83
netflix.com.		5	IN	A	54.243.253.96
netflix.com.		5	IN	A	75.101.139.66
netflix.com.		5	IN	A	107.20.151.133
netflix.com.		5	IN	A	107.20.154.246
netflix.com.		5	IN	A	107.20.177.34
netflix.com.		5	IN	A	174.129.2.58
netflix.com.		5	IN	A	23.21.190.124
netflix.com.		5	IN	A	23.23.191.68
netflix.com.		5	IN	A	50.19.210.42

;; Query time: 21 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Aug 18 20:47:24 EDT 2015
;; MSG SIZE  rcvd: 232

-bash: GET /: No such file or directory
CONNECTED(00000003)
depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Certification Authority
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/OU=Domain Control Validated/OU=PositiveSSL Wildcard/CN=*.neocities.org
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
 1 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
 2 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFVTCCBD2gAwIBAgIRANEH+r4BDi01KVBYlSh3pUEwDQYJKoZIhvcNAQELBQAw
gZAxCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
-----END CERTIFICATE-----
subject=/OU=Domain Control Validated/OU=PositiveSSL Wildcard/CN=*.neocities.org
issuer=/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
---
No client certificate CA names sent
---
SSL handshake has read 5014 bytes and written 441 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 759A629D9898D5831A04B613916F8EFF2FA47E9DFD7A012471DE790E88313107
    Session-ID-ctx:
    Master-Key: F5326FDC9374F151DEA2682F067796DBEE9907E9EC10663165EBF0030C3770DFE7BC2015D7DC9F16EDEFD2BBE97E1670
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 5e ad 88 43 8b 3c c7 39-f6 44 92 6b 65 37 ba 86   ^..C.<.9.D.ke7..
    0010 - 74 13 28 19 36 28 a4 78-72 77 df 33 ad c1 8a ee   t.(.6(.xrw.3....
    0020 - 67 22 ec a7 79 fe 73 84-8d 5f 0f 30 8d ca 3d 3a   g"..y.s.._.0..=:

    Start Time: 1439945244
    Timeout   : 300 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
---
DONE
```

**Comment by ab77** [comment]
OK, I think I see where you are getting confused.

There are two relevant IP addresses:
(a) the Droplet IP; and
(b) your IP at home (the one your Teksavvy ISP gives you i.e. `206.248.158.148`)

The Droplet IP (a) e.g. `45.55.83.199` will never change until you re-build it.

You home IP (b) probably changes weekly, because it is assigned by DHCP.

Once your home IP at home changes, you'll need to get into your Droplet and update the iptables rules i.e. change all occurrences of 206.248.158.148/32 with the new home IP address you can obtain by Googling `what is my ip` from a PC at home.

Hope this helps..

-- ab1

**Comment by hmrtk** [comment]
Great! I am going to try this next time my public IP address changes again. Thanks!
