### ISSUE TITLE
4OD

### ISSUE THREAD

**Issue by simonhutchings** [ab77/netflix-proxy#162]
Great recipe, worked straight away, thanks!
Any ideas how i would go about adding other UK steaming services to this? 4od doesn't seem to work.

**Comment by simonhutchings** [comment]
Worked it out. But would like to know how I BIND to log so I can do some debugging

**Comment by ab77** [comment]
I added logging to the BIND container a while back, so you should just be able to run `docker logs bind` and it will show you what BIND has written to `stdout` and `stderr`.

**Comment by ab77** [comment]
Closed due to inactivity.
