### ISSUE TITLE
Support Spotify

### ISSUE THREAD

**Issue by haniag** [ab77/netflix-proxy#163]
Spotify is not included in zones.override file, but when I add "spotify.com" using the same template as others, the website opens fine and show US, but the app won't log in as it says service not available.

**Comment by ab77** [comment]
Run `docker logs -f bind` before you start Spotify client and see what domains it is requesting. Based on these, you should be able to work out which ones to add to `zones.override`.

**Comment by haniag** [comment]
I tried, but it didn't work so I could be doing something wrong. Either way, I realized you only need a US IP to login to Spotify, but afterwards, there is no geo check. So, i just used a VPN and its working fine.

**Comment by ab77** [comment]
Ok, very good.
