### ISSUE TITLE
Allow users to change their passwords

### ISSUE THREAD

**Issue by kyle95wm** [ab77/netflix-proxy#165]
This isn't really an issue, more of a suggestion. It would be nice to allow users to change their passwords via the web portal. On paper this doesn't sound too hard to implement since you're just modifying the DB. This unfortunately is beyond my capabilities. I can see this being useful in a variety of cases, whether it's for personal or commercial applications. If you think this isn't a good idea/not practical, I understand.

**Comment by ab77** [comment]
Yes, that sounds like a useful feature. If this is something you require and you'd like me to implement it, we can agree an hourly or a flat rate and go from there.

Cheers,
-- ab1

**Comment by kyle95wm** [comment]
This isn't something I need personally, just something that came to mind in general. So feel free to implement this whenever you feel like it
