### ISSUE TITLE
Modify the "Backend not available" message.

### ISSUE THREAD

**Issue by ahmednitul** [ab77/netflix-proxy#168]
Hello,

Is it possible to modify the "Backend not available" message?

Thanks.

**Comment by ab77** [comment]
Yes, you'll need to edit the source and rebuild the Docker container:
https://github.com/dlundquist/sniproxy/blob/f4bc05d729033170c9f389dc11dcaf1fcef5d430/src/http.c#L40

-- ab1

**Comment by ahmednitul** [comment]
Thank you so much :) I am n00b at programming and stuffs, so I was wondering that how should I set an iframe or redirect code replacing Backend not available message, as regular HTML code won't work there and would require string pharsing.

If its not possible to put html contents inside the file, I guess its easily possible to set a 303 Redirection Variable replacing the 503 Error, then kindly provide what should I replace in below codes?

--

static const char http_503[] =
    "HTTP/1.1 503 Service Temporarily Unavailable\r\n"
    "Content-Type: text/html\r\n"
    "Connection: close\r\n\r\n"
    "Backend not available";
