### ISSUE TITLE
DNS on Digitalocean blocking all connections 

### ISSUE THREAD

**Issue by beeriz** [ab77/netflix-proxy#17]
I'm using your no ip method as my IP address changes very often, and once I reboot my connection and my IP address change, I can no longer access to any website nor have the No IP DUC software update my new ip because the proxy is blocking the new ip. How to update the no ip and tell the server that I got a new IP?

Another question : 
I used another method before using this one, and it had some sort of configuration for using Google DNS when not connecting to Netflix, Amazon, Video, Hulu ect... I did some reading and couldn't figure out how to manage the same thing with your configuration. Is it possible to do it?

Any help is much appreciated !
And thank you for your awesome work.

Update #1:
This way works fine, but I have to change the rules.v4 manually and reboot the server before I can use the DNS otherwise I can't connect. Any idea how to automate the whole thing so the cron job can update the rules.v4 file with my new IP address ?

/etc/iptables/rules.v4 :
http://pastebin.com/tDgf4a6P

/opt/scripts/update-firewall.pl :
http://pastebin.com/2jEqAp0Z

crontab -e :
http://pastebin.com/XrvRTEMY

/etc/network/interfaces :
http://pastebin.com/MaZhDtQi

**Comment by ab77** [comment]
Try this variation of the `update-firewall.pl`:

    #!/usr/bin/perl -w
    # restart the firewall if the address of my-ip.dyndns.org has changed
    # /etc/sysconfig/iptables
    use strict;

    pAllow("myid.noip.me");

    sub pAllow {
      my ($aName) = @_;
      #print "aName: $aName\n";
      my $vAddress = readpipe("host $aName | cut -d \" \" -f4");
      chomp $vAddress;
      #print "vAdress: $vAddress\n";
      my $vName = readpipe("host $vAddress | cut -d \" \" -f5");
      chomp $vName;
      if ($vName =~ "SERVFAIL") {
        $vName = $vAddress;
      }
      #print "vName: $vName \n";
      if ($vName ne "") {
        if (system("/sbin/iptables -L -v | grep -i $vName > /dev/null ") != 0) {
          system "/sbin/iptables-restore < /etc/iptables.rules" ;
          system "/usr/bin/docker stop bind sniproxy" ;
          system "/usr/sbin/service docker restart" ;
          system "/usr/bin/docker start bind sniproxy" ;
        }
      }
    }


That should fix it, let me know how it goes..

-- ab1

**Comment by beeriz** [comment]
Thank you ab77

Should I replace /etc/iptables.rules by /etc/iptables/rules.v4 ?
Because I have /etc/iptables/rules.v4 on my machine and when I used /etc/iptables.rules in "/etc/network/interfaces" and "/opt/scripts/update-firewall.pl" , eth0 couldn't start.

**Comment by ab77** [comment]
Yeah, please adjust file names as required.

**Comment by beeriz** [comment]
I went and changed my addresse ip, updated noip and then rebooted the server and waited a few minutes for it to update rules.v4, but it didn't :http://pastebin.com/L62ZYBav 

Let me also point out that I did a fresh install on the Digitalocean droplet, I didn't add or remove anything. Thank you ab77 !

**Comment by ab77** [comment]
Try running the `update-firewall.pl` manually after your IP address changes and see what it actually does..

**Comment by beeriz** [comment]
I don't know if I'm doing this right: 

root@CaptainP:~# 
perl /opt/scripts/update-firewall.pl

sh: 1: Syntax error: "(" unexpected
bind
sniproxy
docker stop/waiting
docker start/running, process 2312
bind
sniproxy

root@CaptainP:~#
---
rules.v4 didn't change after this
and when I check my id.noip.me (ping test), the ip is of course differente from the one on my rules.v4

Thank you ab77, I really appreciate your help

**Comment by ab77** [comment]
Your script isn't executing, check its contents to make sure you haven't phat fingered anything there.

Also make sure to change `myid.noip.me` to your actual dynamic DNS hostname.

Finally make the script executable by `chmod +x update-firewall.pl`.

When you next run it from the command line `./firewall-update.pl`, it should not error, if it does, start from the top and troubleshoot until you find the offending line.

**Comment by beeriz** [comment]
I triple checked everything,
I still get the syntax error
I can't understand this : http://pastebin.com/6nbPzitg

**Comment by ab77** [comment]
If you can please share with me [privately](https://plus.google.com/+AntonBelodedenko/posts), the un-redacted contents of your `update-firewall.pl` script. I need to see what your dynamic host name is and what it resolves to in the DNS..

**Comment by ab77** [comment]
The dynamic host solution `update-firewall.pl` will only work with IP dynamic addresses assigned by the ISP, which also have a PTR (reverse DNS pointer). For example (using google.com):

	$ dig google.com
	;; ANSWER SECTION:
	google.com.             298     IN      A       216.58.208.46

	$ dig -x 216.58.208.46
	;; ANSWER SECTION:
	46.208.58.216.in-addr.arpa. 17750 IN    PTR     lhr08s07-in-f46.1e100.net.
	46.208.58.216.in-addr.arpa. 17750 IN    PTR     lhr08s07-in-f14.1e100.net.

However, if the reverse lookup results in an empty PTR answer, it means you are out of luck and need to speak to your ISP, change ISPs or get a static IP.

-- ab1
