### ISSUE TITLE
How to use it in a VPN server ?

### ISSUE THREAD

**Issue by mjsmnj** [ab77/netflix-proxy#172]
Hello, 

I live in a very restrict environment, I cant change my DNS. and the only protocol i can use to connect to a VPN is SSTP. 

I'm using Softether on my server on digitalocean. 

I installed softether then
I followed the steps in here: http://blog.belodedenko.me/2015/03/netflix-smart-dns-proxy-in-six-steps.html

 except for step 6 instead i tried to connect to the server but it is not working I couldnt even access it using SSH. 

Can you help me with that ?

**Comment by ab77** [comment]
Well, I am guessing you need to SSH to your server using the private VPN endpoint IP, if your network doesn't allow outbound SSH?

**Comment by mjsmnj** [comment]
I'm not sure what are you talking about, but I have been able to create a docker droplet and create a tunnel successfully. first thing i did was installing softether 

I tried to connect to it through softether, worked just fine. 

then I typed this command 

`root@docker-512mb-sfo1-01:~# git clone https://github.com/ab77/netflix-proxy /opt/netflix-proxy && cd /opt/netflix-proxy && ./build.sh -u *******-p **********
Cloning into '/opt/netflix-proxy'...
remote: Counting objects: 3225, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 3225 (delta 10), reused 0 (delta 0), pack-reused 3180
Receiving objects: 100% (3225/3225), 88.09 MiB | 10.46 MiB/s, done.
Resolving deltas: 100% (1679/1679), done.
Checking connectivity... done.
resolved params: clientip=****** ipaddr=******* extip=********
cmd: ./build.sh -r=1 -b=0 -s= -z=0 -n=1 -u=****** -p [secret] -k [secret]

 * disabling native IPv6 on eth0...                                      [ OK ]
 * installing XPath...                                                   [ OK ]
 * enabling he-ipv6 interface...                                         [ OK ]
 * bringing up IPv6 tunnel...                                            [ OK ]
 * testing IPv6 tunnel (this may take a while)...                        [ OK ]
 * enabling DNS recursion...                                             [ OK ]
 * authorising clientip=******** on iface=eth0...                  [ OK ]
 * adding IPv4 iptables rules...                                         [ OK ]
 * creating Docker and sniproxy configuration templates...               [ OK ]
 * checking IPv6 connectivity...                                                 * enabling sniproxy IPv6 priority...                                    [ OK ]
 * installing sipcalc...                                                 [ OK ]
 * enabling Docker IPv6 dual-stack support with fixed-cidr-v6=2001:470:d:1c0::/64...                                                                     [ OK ]
 * adding IPv6 iptables rules...                                         [ OK ]
 * installing iptables|netfilter-persistent service...                   [ OK ]
 * socialising Docker with iptables-persistent service...                [ OK ]
 * updating iptables-persistent init script...                           [ OK ]
 * saving iptables rules...                                              [ OK ]
 * creating zones.override from template...                              [ OK ]
 * updating db.override with extip=********* and date=20160519...   [ OK ]
 * installing python-pip and docker-compose...                           [ OK ]
 * configuring netflix-proxy-admin backend...                            [ OK ]
 * configuring netflix-proxy-admin reverse-proxy...                      [ OK ]
 * creating and starting Docker containers...                                   
root@docker-512mb-sfo1-01:/opt/netflix-proxy#

I think there was a problem completing the script, im not sure what is it. 

If you want I can email you the server login information 
`

**Comment by ab77** [comment]
Please have a look what is in `netflix-proxy.log` first, especially at the end..

**Comment by mjsmnj** [comment]
ERROR: for sniproxy  driver failed programming external connectivity on endpoint sniproxy (7171dcbb2c0c0aa1ae4404077601a68bb5c9a26d587ccaf3cc04a58ef4c2324a): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 63, in main
    log.error(e.msg)
AttributeError: 'ProjectError' object has no attribute 'msg'

**Comment by ab77** [comment]
There is already something listening on port 443, what OS are you deploying this on?

**Comment by mjsmnj** [comment]
I guess I know now what happened, 

as I said im using Softether it is like openVPN and it listens to 443 as this is the only protocol i can use to connect to a VPN. 

sorry my english is not that good so i didnt get your question, if you meant the server OS is ubuntu 14.04 and my laptop OS is windows 10

**Comment by ab77** [comment]
Right, can you move Softether to another port and still connect to it? For example 444 or 445 or 8443?

**Comment by mjsmnj** [comment]
how can i do that ? even I could im 99.99% sure it wont work, isnt there something else I can do?

**Comment by ab77** [comment]
There is, but it gets fairly complicated.  In principle, you will have to change the port SNIProxy container listens on from `443` to something else, like `8443` (this is set in `netflix-proxy.yaml`) and then use NAT on your box to re-write traffic from port `443` to `<vpn-ip-endpoint>:8443`. You don't have `iptables` in Windows, so you'll have to use `RRAS`, see [here](http://serverfault.com/questions/562278/iptables-alternative-for-nat-in-windows).

Alternatively, if IPv6 isn't blocked from your network, try to establish a tunnel directly to HE from your Windows box and use that.

**Comment by mjsmnj** [comment]
finally i found a port that works 9930, 

I installed softether on the server deleted 443 from the listening list add 9930. and everything worked fine. 

then installed your script it went without any errors, but once finished i couldn't connect to the server anymore through 9930 . does this project prevent any sort of VPN connection ?

**Comment by ab77** [comment]
Yep, iptables. Run `iptables -I INPUT -p tcp -m tcp --dport 9930 -j ACCEPT && iptables-save > /etc/iptables/rules.v4`

-- ab1

**Comment by mjsmnj** [comment]
It worked, but 

> You seem to be using an unblocker or proxy. Please turn off any of these services and try again. For more help, visit netflix.com/proxy.

**Comment by ab77** [comment]
Does browsing to http://ipinfo.io/ give you the IP of your Digital Ocean server?

What does `nslookup netflix.com` and `nslookup nflxvideo.net` return on your Windows PC?

**Comment by mjsmnj** [comment]
1 - yes 

2 - 

`Server:  UnKnown
Address:  192.168.30.1

Non-authoritative answer:
Name:    netflix.com
Addresses:  2620:108:700f::36d6:25bf
          2620:108:700f::36f4:5b82
          2620:108:700f::36d6:22b2
          2620:108:700f::36f4:58e3
          2620:108:700f::36d6:2889
          2620:108:700f::36d6:177c
          2620:108:700f::36d6:1cd2
          2620:108:700f::36f4:793e
          54.204.43.31
          107.20.154.246
          50.19.210.42
          23.23.191.68
          23.21.190.124
          54.225.192.83
          107.20.177.34
          174.129.2.58
          107.20.151.133
          54.204.2.219
          54.243.253.96
          75.101.139.66`

3 -

`Server:  UnKnown
Address:  192.168.30.1

Non-authoritative answer:
Name:    nflxvideo.net
Address:  69.53.236.21`

**Comment by ab77** [comment]
Well, these are wrong responses. You need to make sure you have configure your DNS resolver to point to the (VPN) IP address of your DO server. If this IP is `192.168.30.1`, then try a couple of different lookups.

On your DO server:
`dig netflix.com @<local-VPN-endpoint-ip>`

It should respond with only one A record, which will be pointing to the `local-VPN-endpoint-ip`.

On your Windows PC:
`nslookup netflix.com <local-VPN-endpoint-ip>` and `nslookup netflix.com 8.8.8.8>

the first response should be the same as the one on your server, the second will be the public response you in your previous test above.

**Comment by mjsmnj** [comment]
If i can change the dns i wouldnt go through the trouble of setting up a vpn server that can access netfix. and no the DO server ip is 45.55.150.65 , the 192.168.30 came from here I think
![capture](https://cloud.githubusercontent.com/assets/6514633/15429879/87a13040-1eab-11e6-9ad0-d3fc50c78651.PNG)
.1 

I dont really know what you mean by local vpn endpoint ip 

but i tried this : dig netflix.com @45.55.150.65 

it gave me 

; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> netflix.com @45.55.150.65
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8067
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;netflix.com.                   IN      A

;; ANSWER SECTION:
netflix.com.            86400   IN      A       45.55.150.65

;; AUTHORITY SECTION:
netflix.com.            86400   IN      NS      ns1.netflix.com.

;; ADDITIONAL SECTION:
ns1.netflix.com.        86400   IN      A       45.55.150.65

;; Query time: 8 msec
;; SERVER: 45.55.150.65#53(45.55.150.65)
;; WHEN: Fri May 20 09:57:18 EDT 2016
;; MSG SIZE  rcvd: 90

**Comment by ab77** [comment]
Run `ifconfig` on the server and it will list all the interfaces. If you see `192.168.30.1` in there, then that is your `server-VPN-endpoint-ip`.

**Comment by mjsmnj** [comment]
It's not there, even the name of the vps server is not there 

ifconfig
 
docker0   Link encap:Ethernet  HWaddr 02:42:dc:0a:23:c5                                                                  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0                                                          
          inet6 addr: fe80::42:dcff:fe0a:23c5/64 Scope:Link                                                              
          inet6 addr: 2001:470:1f07:b5e::1/64 Scope:Global                                                               
          inet6 addr: fe80::1/64 Scope:Link                                                                              
          UP BROADCAST RUNNING PROMISC MULTICAST  MTU:1500  Metric:1                                                     
          RX packets:625 errors:0 dropped:0 overruns:0 frame:0                                                           
          TX packets:591 errors:0 dropped:0 overruns:0 carrier:0                                                         
          collisions:0 txqueuelen:0                                                                                      
          RX bytes:54689 (54.6 KB)  TX bytes:113721 (113.7 KB)                                                           
                                                                                                                         
eth0      Link encap:Ethernet  HWaddr 04:01:ee:5d:1d:01                                                                  
          inet addr:45.55.150.65  Bcast:45.55.191.255  Mask:255.255.192.0                                                
          UP BROADCAST RUNNING PROMISC MULTICAST  MTU:1500  Metric:1                                                     
          RX packets:380044 errors:0 dropped:0 overruns:0 frame:0                                                        
          TX packets:372619 errors:0 dropped:0 overruns:0 carrier:0                                                      
          collisions:0 txqueuelen:1000                                                                                   
          RX bytes:667016496 (667.0 MB)  TX bytes:204559380 (204.5 MB)                                                   
                                                                                                                         
he-ipv6   Link encap:IPv6-in-IPv4                                                                                        
          inet6 addr: 2001:470:1f06:b5e::2/64 Scope:Global                                                               
          inet6 addr: fe80::2d37:9641/64 Scope:Link                                                                      
          UP POINTOPOINT RUNNING NOARP  MTU:1480  Metric:1                                                               
          RX packets:29108 errors:0 dropped:0 overruns:0 frame:0                                                         
          TX packets:3592 errors:0 dropped:0 overruns:0 carrier:0                                                        
          collisions:0 txqueuelen:0                                                                                      
          RX bytes:42623803 (42.6 MB)  TX bytes:314679 (314.6 KB)                                                        
                                                                                                                         
lo        Link encap:Local Loopback                                                                                      
          inet addr:127.0.0.1  Mask:255.0.0.0                                                                            
          inet6 addr: ::1/128 Scope:Host                                                                                 
          UP LOOPBACK RUNNING  MTU:65536  Metric:1                                                                       
          RX packets:9779 errors:0 dropped:0 overruns:0 frame:0                                                          
          TX packets:9779 errors:0 dropped:0 overruns:0 carrier:0                                                        
          collisions:0 txqueuelen:0                                                                                      
          RX bytes:4177171 (4.1 MB)  TX bytes:4177171 (4.1 MB)                                                           
                                                                                                                         
veth198f2c8 Link encap:Ethernet  HWaddr 82:ec:c0:52:77:a2                                                                
          inet6 addr: fe80::80ec:c0ff:fe52:77a2/64 Scope:Link                                                            
          UP BROADCAST RUNNING PROMISC MULTICAST  MTU:1500  Metric:1                                                     
          RX packets:52 errors:0 dropped:0 overruns:0 frame:0                                                            
          TX packets:108 errors:0 dropped:0 overruns:0 carrier:0                                                         
          collisions:0 txqueuelen:0                                                                                      
          RX bytes:9997 (9.9 KB)  TX bytes:21081 (21.0 KB)                                                               
                                                                                                                         
veth895b858 Link encap:Ethernet  HWaddr 4a:f5:cf:31:88:54                                                                
          inet6 addr: fe80::48f5:cfff:fe31:8854/64 Scope:Link                                                            
          UP BROADCAST RUNNING PROMISC MULTICAST  MTU:1500  Metric:1                                                     
          RX packets:9 errors:0 dropped:0 overruns:0 frame:0                                                             
          TX packets:77 errors:0 dropped:0 overruns:0 carrier:0                                                          
          collisions:0 txqueuelen:0                                                                                      
          RX bytes:726 (726.0 B)  TX bytes:13675 (13.6 KB)                                                               
                                                                                                                         
vetha2df7c4 Link encap:Ethernet  HWaddr 5e:4f:d1:28:34:4d                                                                
          inet6 addr: fe80::5c4f:d1ff:fe28:344d/64 Scope:Link                                                            
          UP BROADCAST RUNNING PROMISC MULTICAST  MTU:1500  Metric:1                                                     
          RX packets:383 errors:0 dropped:0 overruns:0 frame:0                                                           
          TX packets:437 errors:0 dropped:0 overruns:0 carrier:0                                                         
          collisions:0 txqueuelen:0                                                                                      
          RX bytes:40700 (40.7 KB)  TX bytes:85041 (85.0 KB)                                                             
                                                                                                                         
vethe539ddb Link encap:Ethernet  HWaddr ce:0f:10:3e:bc:7f                                                                
          inet6 addr: fe80::cc0f:10ff:fe3e:bc7f/64 Scope:Link                                                            
          UP BROADCAST RUNNING PROMISC MULTICAST  MTU:1500  Metric:1                                                     
          RX packets:165 errors:0 dropped:0 overruns:0 frame:0                                                           
          TX packets:224 errors:0 dropped:0 overruns:0 carrier:0                                                         
          collisions:0 txqueuelen:0                                                                                      
          RX bytes:10684 (10.6 KB)  TX bytes:40077 (40.0 KB)

**Comment by ab77** [comment]
Well, I am not sure how your VPN works, but since if looks like you can actually resolve using `45.55.150.65`, then you should specify this IP to hand out to VPN clients and not `192.168.30.1`.

**Comment by mjsmnj** [comment]
I couldnt do that , idk why but what I did was that , i have another VPN server located in netherlands. 

So I just changed the dns settings for that server to my dns server in US and it worked. 

was hoping I can access it directly though , but at least something better than nothing.

**Comment by ab77** [comment]
You can temporarily drop all iptables rules to see if it is blocking your traffic by running `iptables -F && iptables -t net -F`.

**Comment by mjsmnj** [comment]
i got this 

can't initialize iptables table `net': Table does not exist (do you need to insmod?)                   
Perhaps iptables or your kernel needs to be upgraded.

**Comment by ab77** [comment]
`iptables -F && iptables -t nat -F`

**Comment by mjsmnj** [comment]
first I did this (`iptables -F && iptables -t net -F `) when i got the error message and before seeing your post I tried netflix and it worked. 

then I did ( `iptables -F && iptables -t nat -F` ) and tried netflix didnt even open any kind of page, 

I restarted the server and tried netflix it worked just fine. 

not quite sure what happened!

**Comment by ab77** [comment]
Too many variables :)
