### ISSUE TITLE
Output error

### ISSUE THREAD

**Issue by skwertzke** [ab77/netflix-proxy#174]
Hi, I am getting some errors when executing the command :( Are you able to help?
I am getting Network Unreachable on Ping6 netflix.com
Requirements are all checked and made sure of.
The tunnel on tunnelbroker checks out with no issues...

 * disabling native IPv6 on eth0...                                                              [ OK ]
 * installing XPath...                                                                           [ OK ]
 * enabling he-ipv6 interface...                                                                 [ OK ]

no element found at line 1, column 0, byte 0:

^
 at /usr/lib/perl5/XML/Parser.pm line 187.

no element found at line 1, column 0, byte 0:

^
 at /usr/lib/perl5/XML/Parser.pm line 187.
 * tunnel endpoint clientv4= does not match

**Comment by skwertzke** [comment]
Also yes, I am using Ubuntu Docker 1.11.1 on 14.04

**Comment by ab77** [comment]
I think it can't login to HE portal using your details to retrieve tunnel config, make sure your username and password are correct..

**Comment by skwertzke** [comment]
Sorry for being an idiot.

**Comment by ab77** [comment]
No problem :grimacing:
