### ISSUE TITLE
Wrong netflix

### ISSUE THREAD

**Issue by dupuyol** [ab77/netflix-proxy#175]
I have setup the docker and smartdns.  All the script is executing right.  I am however using a tunnel from Singapore and testing from a system over in asia.  I can reach Netflix.com ok but it is always netflix singapore.  Don't know if this is due to the tunnel?  How can I troubleshoot find out why it is not going to Netflix US?

I have another windows system in the same location as the smartdns and I can access netflix US from there.

Any help would be greatly appreciated.

**Comment by ab77** [comment]
Can you try creating a tunnel on a different tunnel server (you have max. 3 on an account) and redeploy using this tunnel. You can specify a tunnel index as a parameter to  the build script, starting from 1 (first tunnel in the portal).

**Comment by dupuyol** [comment]
I already tried with Los Angeles, Seattle, Ashburn, and 1 of the Fremont but each time the build script will fail

at around "bringing up IPv6 tunnel" the error is along the line of "not being able to reach the tunnel"


Not sure which region to use since I have used 3 accounts already to change regions


If I were to change region now, can I just run build.sh or do I have make changes manually?


________________________________

**Comment by dupuyol** [comment]
Also I can only have 1 tunnel configured for 1 IPv4 (which is that of the VPS/Node correct?)

**Comment by ab77** [comment]
The best way is to destroy your VPS and start from scratch, providing the `-n` parameter with the index number of the required tunnel. For example `-n 2` for the second tunnel in the portal.

Correct, HE won't allow you to create multiple tunnels to the same IPv4 address.

**Comment by dupuyol** [comment]
Been destroying and rebuilding the whole day so far :) and since my VM only has 1 IP I can only create 1 tunnel.  My VM is in the US (Dallas) but the script has failed for the US regions I mentioned above except for Singapore.  Any suggestion for a region that would not crash the build script?

**Comment by ab77** [comment]
Do you have the `netflix-proxy.log` from the failed attempts?

**Comment by kyle95wm** [comment]
@ab77 forgive me but I was under the impression that HE was a pure US tunnel provider. From what you said, the only reason there are multiple locations is to reduce congestion on the path to our Netflix server/Netflix itself.

**Comment by dupuyol** [comment]
I don't have the logs, I wiped the VM and recreated but I am going to try to recreate again with a new region and give you the log if it fails.

**Comment by ab77** [comment]
HE are based in the US, but they have local POPs all over the world. However, the geo
-ip info for these local POPs is mainly messed up, which is why Netflix sometimes thinks you are in Switzerland or some other location, not corresponding with the actual tunnel server physical location.

**Comment by dupuyol** [comment]
is there any other tunnel broker that would be more reliable?

**Comment by ab77** [comment]
Not that I know of. I have the build automatically tested on a HE `NYC` tunnel with the Droplet running  in `nyc3`. It works.

**Comment by dupuyol** [comment]
OK, sorry for the delay in responding,  It seems that it working now.  My problem may have been setting up the DNS server at the router/DHCP level.  It seems to be working also from the Roku box I have (will be testing with xbox and chromecast to see) - Thanks

**Comment by ab77** [comment]
No problem. I can't say for sure about Xbox, but I know Gen1 ChromeCasts didn't support SNI.
