### ISSUE TITLE
tunnelbroker says IP is blocked - DigitalOcean

### ISSUE THREAD

**Issue by hellrokr** [ab77/netflix-proxy#179]
So, As per instruction, I tried to set this up. Went to https://tunnelbroker.net/new_tunnel.php and added my droplets IP in the field "IPv4 Endpoint (Your side):".
After that I got this error:
IP is blocked. (netflix proxy abuse)

I was not able to create a tunnel afterwards.

Screenshot attached.

So, can anyone help me?

![wpglbxp](https://cloud.githubusercontent.com/assets/9604538/15707410/3a29a710-2816-11e6-960c-206c9ac3a018.png)

Thanks

**Comment by ab77** [comment]
Destroy the Droplet and get a new one (different IP), or use a different hosting provider (e.g. Vultr).

**Comment by hellrokr** [comment]
ok, will try and report the results.

Thanks

**Comment by ab77** [comment]
Closing due to HE being permanently blocked.
