### ISSUE TITLE
Trying to pull images from https://registry-1.docker.io/v1/

### ISSUE THREAD

**Issue by NeSmo1** [ab77/netflix-proxy#18]
Starting Docker containers (from repository)
Unable to find image 'ab77/bind:latest' locally
Pulling repository ab77/bind
f291f16f6237: Pulling image (latest) from ab77/bind, endpoint: https://registry-1.docker.io/v1/

If fails after this on a time out.. Any ideas? :)

Thanks in advanced.

**Comment by ab77** [comment]
I have the same problem, I think Docker are having some [issues](https://status.docker.com/)

**Comment by NeSmo1** [comment]
Fixed the issue, i had to log into docker on the server to be able to access registry-1.docker.io

**Comment by ab77** [comment]
That seems to work for me also, although one shouldn't need to login to access the public repository.
