### ISSUE TITLE
Auth IP range

### ISSUE THREAD

**Issue by haniag** [ab77/netflix-proxy#182]
Is there anyway to authorize an IP range? My ISP keeps changing IPs on a regular basis, and the new IPs are only different in the last 2 subsets.

**Comment by ab77** [comment]
Doesn't your browser redirect you to the web interface when your IP changes?

**Comment by haniag** [comment]
Yes it does. But this happens almost every other day, and its a pain to keep logging in and adding new IP. I guess a workaround would be to keep me logged in, so then I would just have to add new IP.

**Comment by ab77** [comment]
https://github.com/ab77/netflix-proxy#automatic-ip-authorization

**Comment by haniag** [comment]
Yes, I am aware of that, but I wanted to try an IP range to be more secure rather than allowing everything. I'll just use that if it really becomes too much of a hassle.
