### ISSUE TITLE
Installation Stops

### ISSUE THREAD

**Issue by 2swae** [ab77/netflix-proxy#183]
I've tried several times and suddenly the installation stops before or after installation of docker, what would cause this?

Also, when this occurs, can I uninstall the script somehow?

Thanks.

**Comment by ab77** [comment]
I've seen this happen randomly during installation. The problem is with container start. I have a feeling something changed in a recent Docker engine version, but I've not had time to look into it. Try re-installing from scratch.

**Comment by 2swae** [comment]
OK, I had tried several times before it finally worked. But I only managed to setup one DNS server. I wanted two for backup, but no luck, just errors at various stages in installations on multiple providers.

**Comment by ab77** [comment]
The problem is that the `sniproxy` container can't start for some reason, randomly it seems. On some systems it works, but not on others.

The error in the logs is:

```
Jun 20 14:45:03 localhost docker[30313]: time="2016-06-20T14:45:03.954047732-05:00" level=error msg="Failed to start container 09d4622ab8d6717c443c63aa9133d638f472cb86363e6413ad4af6915201405f: rpc error: code = 6 desc = \"mkdir /run/containerd/09d4622ab8d6717c443c63aa9133d638f472cb86363e6413ad4af6915201405f: file exists\""
Jun 20 14:45:04 localhost docker[30313]: time="2016-06-20T14:45:04-05:00" level=error msg="containerd: notify OOM events" error="open memory.oom_control: no such file or directory"
Jun 20 14:45:04 localhost docker[30313]: time="2016-06-20T14:45:04-05:00" level=error msg="containerd: notify OOM events" error="open memory.oom_control: no such file or directory"
```

Workaround is to run `service docker restart` and recover the admin password from the DB, or just reset it using the instructions in the Wiki and/or README.

**Comment by 2swae** [comment]
Ok thanks, will give it a try.

Also, could we somehow configure this script to work with other services such as vudu?

**Comment by ab77** [comment]
See, https://github.com/ab77/netflix-proxy#supported-services
