### ISSUE TITLE
Replacing backend not available in the sniproxy's source code.

### ISSUE THREAD

**Issue by ahmednitul** [ab77/netflix-proxy#185]
Hello,

It's regarding a previous issue that you advised: (https://github.com/ab77/netflix-proxy/issues/168)

--

Thank you so much :) I am n00b at programming and stuffs, so I was wondering that how should I set an iframe or redirect code replacing Backend not available message, as regular HTML code won't work there and would require string pharsing.

If its not possible to put html contents inside the file, I guess its easily possible to set a 303 Redirection Variable replacing the 503 Error, then kindly provide what should I replace in below codes?

static const char http_503[] =
"HTTP/1.1 503 Service Temporarily Unavailable\r\n"
"Content-Type: text/html\r\n"
"Connection: close\r\n\r\n"
"Backend not available";

**Comment by ab77** [comment]
Sorry, I can't help you with modifying SNIProxy code.
