### ISSUE TITLE
How to resolv domains using a different DNS Server.

### ISSUE THREAD

**Issue by ahmednitul** [ab77/netflix-proxy#187]
Hello,

As my VPS's IP is blocked by Netflix, what I am trying to do is use other smart-dns provider like tunlr.com to connect netflix.

I mean my end-users will use my dnsproxy as their dns server and my server will connect to netflix using other dns provider then pass the contents to my end-users.

The reason for this is because these smart-dns providers mostly allow a single IP under a subscription to access their service, so by making my netflix-proxy a medium and register it's IP with the smart-dns-provider now I can share that smart-dns-proxies with my friends.

I tried editing r/docker-sniproxy/sniproxy.sh & named.conf.template and replaced 8.8.8.8 with smart-dns providers dns but it does not work, from terminal if I do nslookup, it usages smart-dns-provider's dns to resolve but when request are made from outside to the netflix-proxy service, they resolve using 8.8.8.8

Please do advice how can it be done.

Best wishes,
Ahmed Nitul.

**Comment by ab77** [comment]
See, http://serverfault.com/a/718162/137589.

edit `/opt/netflix-proxy/data/conf/zones.override` and define zones as follows:

```
zone "netflix.com." {
    type forward;
    forward only;
    forwarders { <tunlr-dns-ip>; };
};

zone "nflxvideo.net." {
    type forward;
    forward only;
    forwarders { <tunlr-dns-ip>; };
};
```

Then `docker restart bind`.

**Comment by hariesnurikhwan** [comment]
I've tried this but it doesn't work. When I check my IP on my provider site, sometimes it shows my real IP, sometimes my DNS IP.

**Comment by ab77** [comment]
Sounds like you have multiple DNS servers configured in your client. Direct requests using `dig` to various DNS servers long to forwarding chain will help you pin point where the issue is.

**Comment by ab77** [comment]
Please re-open if required.
