### ISSUE TITLE
US VPS / Cloud providers not blocked

### ISSUE THREAD

**Issue by i37** [ab77/netflix-proxy#188]
Does anyone know of any working VPS or Cloud providers that aren't blocked on Netflix?

**Comment by ab77** [comment]
I think Kamatera may work.

**Comment by iambak** [comment]
I set mine up yesterday it worked for a while then it stopped working

**Comment by iambak** [comment]
My bad it works on my computer but not my iPhone app

**Comment by ab77** [comment]
This is well documented. The iOS app may bypass DNS all together.

**Comment by iambak** [comment]
Oh okay 😊
