### ISSUE TITLE
DNS zones

### ISSUE THREAD

**Issue by 2swae** [ab77/netflix-proxy#189]
I'm using a roku TV and trying to use vudu, but it doesn't work, it tells me my country error instead of logging in. 

All the other services work and even on my phone, such as Spotify and Pandora. 

Any ideas? Maybe they changed their url?

**Comment by ab77** [comment]
Try something along the lines of https://github.com/ab77/netflix-proxy/wiki/Apple-TV-4,-Roku,-Google-Chromecast-and-any-other-device-with-hard-coded-DNS

**Comment by 2swae** [comment]
So I should  block Google DNS servers?

**Comment by ab77** [comment]
Yes, try that first if going blind. Otherwise put a packet sniffer between router and Roku and find out what it is actually doing..

**Comment by ab77** [comment]
Please re-open if required.
