### ISSUE TITLE
ERR_CONNECTION_TIMED_OUT When visiting netflix, hulu and amazon

### ISSUE THREAD

**Issue by beeriz** [ab77/netflix-proxy#19]
on server: 

root@CaptainP:~ ping netflix.com
PING netflix.com (54.243.253.96) 56(84) bytes of data.

--- netflix.com ping statistics ---
388 packets transmitted, 0 received, 100% packet loss, time 390088ms
_____________________________

root@CaptainP:~# ping amazon.com
PING amazon.com (176.32.98.166) 56(84) bytes of data.

--- amazon.com ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 2999ms

_____________________________
root@CaptainP:~# ping yahoo.com
PING yahoo.com (98.139.183.24) 56(84) bytes of data.
64 bytes from ir2.fp.vip.bf1.yahoo.com (98.139.183.24): icmp_seq=1 ttl=56 time=12.0 ms
64 bytes from ir2.fp.vip.bf1.yahoo.com (98.139.183.24): icmp_seq=2 ttl=56 time=9.88 ms
64 bytes from ir2.fp.vip.bf1.yahoo.com (98.139.183.24): icmp_seq=3 ttl=56 time=12.1 ms

--- yahoo.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 9.885/11.363/12.155/1.053 ms

___________________________
on PC : netflix.com
Page Web inaccessible
ERR_CONNECTION_TIMED_OUT
---

Did my machine got banned (I didn't really use it!) or the script stopped working? 
Thank you !

**Comment by ab77** [comment]
Try destroying your droplet and starting from scratch.
