### ISSUE TITLE
Cloud-init Digitalocean

### ISSUE THREAD

**Issue by thibaultmol** [ab77/netflix-proxy#190]
Hi

I'm not used to using providers like Digitalocean but I noticed a thing called cloud-init which would make it easier to setup a droplet. Is it possible someone could make a cloud-init 'script' for netflix-proxy so that you can set it up even easier. And also so that it's easier to quickly spin up and shutdown on (pay /hour)

Thanks in advance!

**Comment by ab77** [comment]
Take a look at https://github.com/ab77/netflix-proxy/blob/master/tests/testbuild.py#L138.
