### ISSUE TITLE
problems with dnsmasq

### ISSUE THREAD

**Issue by iambak** [ab77/netflix-proxy#191]
helle i need help with dnsmasq
what im trying to do is selectively send dns request to my vps, but every time i do that netflix detects that im using a proxy. but if i enter my vps ip address in my device's dns setting it works fine.

also hulu just works fine its netflix that has the problem only

what im i doing wrong 

thanks in advance

**Comment by iambak** [comment]
its alright i got it to work using one of your  tutorials 
https://github.com/ab77/netflix-proxy/wiki/setting-up-netflix-proxy-with-dd-wrt

**Comment by ab77** [comment]
Good work!
