### ISSUE TITLE
proxy detected

### ISSUE THREAD

**Issue by mpk99** [ab77/netflix-proxy#192]
Hi,

So i've got this running on a residential line, so it's definitely not blocked by Netflix.  If i point my DNS on a PC, browser works just fine for US Netflix.  My BD Player however (which can use SNI - I tested) keeps coming back with the unblocker or proxy detected method.  Now, if i sign up for one of the commercial providers that still exists, it works .  What step am i missing fromm making this work on my BD player that the commercial SmartDNS providers figured out?

thx

**Comment by ab77** [comment]
You can work out whether some additional domains are required to be proxied by simply using the default statement in `zones.override` (https://github.com/ab77/netflix-proxy#further-work)

If it works with that, then some other domain apart from `netflix.com` and `nflxvideo.net` need to be proxied. To work out which one, you'll need to put a packet sniffer (i.e. tcpdump) between the box and the proxy and see what DNS requests are being made.

**Comment by mpk99** [comment]
Ok i'll see if i can give that a shot -- i'm pretty sure i already took your advice by making it a "dumb" proxy and proxying everything thru the server, and still go the same error -- it's as if there's an extra step needed that isn't documented or made public by commercial providers that made their solutions work.

**Comment by ab77** [comment]
The device could be ignoring your DNS setting and making direct requests to IPs it gets via another mechanism (HTTPS) or using a hardcoded DNS server, but then I don't understand how your commercial provider can override all this by using the same approach...

**Comment by mpk99** [comment]
yeah exactly -- unless they've determined what those direct calls are and maybe they've modified them on their DNS servers and that's what's allowed me to continue uninterrupted?

**Comment by ab77** [comment]
Yes, definitely possible. If the device makes a fairly unobscured call to some API endpoint (resolved via DNS) and that endpoint returns a list of IPs to stream from, then it is possible to have a fake API returning IPs to redirect the device requests back via the proxy.

**Comment by mpk99** [comment]
So i haven't had time to look at this much yet, but i did get a response from one of these commercial providers.  They're basically saying what you did -- the netflix apps are no longer using host names, but are providing the IP's to the apps and it renders DNS resolution useless -- if i were to obtain those ips, i could possibly make this work -- time to figure out how to use tcpdump :)

**Comment by ab77** [comment]
If you (a) know someone in the USA willing to host a small Linux server for you and (b) interested in a trial of a new solution I am developing, which gets around all this unpleasantness, let me know and I'll set you up for a trial.

**Comment by mpk99** [comment]
Hi.

That would be awesome -- i have somebody that can help out and is willing.  Did you want me to contact you on irc to continue?  lemme know, i certain can.

thx for all your help! and looking forward to this!

**Comment by ab77** [comment]
Yep, please ping me on IRC tomorrow.
