### ISSUE TITLE
Kamatera stopped working

### ISSUE THREAD

**Issue by david4rogers** [ab77/netflix-proxy#194]
As of today, July 21st, Netflix identifies Kamatera as a proxy.

Anybody knows other cloud providers which are not blocked by Netflix?

**Comment by iambak** [comment]
what were you using coz mine still works in the web browser, but it dosnt work on my apple tv or the ios app

**Comment by david4rogers** [comment]
Was using browser.

**Comment by iambak** [comment]
try change your zone.override 
https://github.com/ab77/netflix-proxy#further-work

**Comment by david4rogers** [comment]
zones.override is ok. Can it get going on Apple TV?

**Comment by iambak** [comment]
nope it's not working on apple tv

**Comment by ab77** [comment]
Please register for updates on the mailing list (http://netflix-proxy.belodedenko.me/) RE: August update. An alternative (paid subscription based) unblocking solution is close to being completed and should be going to trial soon.
