### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by RomainBoulay** [ab77/netflix-proxy#195]
Hey @ab77 

First of all, thanks a lot for your work and to open source it, that's great. Been reading a bit the scripts and that's very interesting.
I've been trying to run your build script on a ubuntu 14 machine but I can't run it through.

It stops after:
``` * creating and starting Docker containers...```

I keep getting this log:

```
proxy / localhost:43867 {
    except /static
    proxy_header Host {host}
    proxy_header X-Forwarded-For {remote}
    proxy_header X-Real-IP {remote}
    proxy_header X-Forwarded-Proto {scheme}
}
Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

Would you have an idea how I can solve this?
Thanks again

**Comment by ab77** [comment]
Thank you. Does Docker actually install correctly on this system? Try running everything prior to `build.sh` and before running the build, see if Docker is installed by running `docker ps`.

If that works, then we need to start looking at what steps in `build.sh` break it...

**Comment by RomainBoulay** [comment]
`docker ps` gives:

```
FATA[0000] Get http:///var/run/docker.sock/v1.18/containers/json: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 
```

**Comment by RomainBoulay** [comment]
And docker logs:

```
WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit status 1 
invalid CIDR address: 1:0/125
INFO[0000] -job init_networkdriver() = ERR (1)          
FATA[0000] Shutting down daemon due to errors: invalid CIDR address: 1:0/125
```

**Comment by RomainBoulay** [comment]
Hey @ab77, I'm following-up. 

I tried to debug my issue, it seems `get_docker_ipv6_subnet` does not work as expected: it returns `1:0/125` which may be incorrect.
I saw the `build.sh -s` option but I could not find an ip mask that worked.

I'm stuck and would love your help!
Thanks.

**Comment by ab77** [comment]
There is an easy way to fix this and a harder way. The easy way is to disable IPv6 on the host if you don't need it and this issue will go away.

If you do need IPv6, then the script needs to be debugged.

**Comment by ab77** [comment]
Basically, the build script only works wth /64 prefix. If your VPS assigns anything other than that, you need to partition that prefix manually into two segments, assign the upper one to Docker via the `-s` switch and update `/etc/network/interfaces' file with the lower one. You'll also need to NAT everything out the main IP of the server using `ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE`.
