### ISSUE TITLE
only the configured domains get resolved?

### ISSUE THREAD

**Issue by opetznick** [ab77/netflix-proxy#2]
hey there

i just installed the docker image on a digital ocean vps.. the setup looks pretty good no errors so far... if i execute ```dig netflix.com @mynewserver``` everything resolves perfectly... but lets say i exec ```dig facebook.com @mynewserver``` it doesnt resolve anything at all?

thanks for help.

**Comment by ab77** [comment]
Hi there, the DNS setup has recursion disabled, which means it will only
answer queries for domains it is authoritative for (e.g. netflix.com).

If you are planning to use this DNS for everything, which isn't
recommended, you'll have to get into the DNS config and change it manually
as follows:

SSH to your Droplet and run:

# docker exec -i -t bind bash
[root@abcd1234 /]# vi /etc/named.conf

Change the following lines as follows:

        allow-recursion { trusted; };
        recursion yes;
        additional-from-auth yes;
        additional-from-cache yes;

Save and exit file

[root@abcd1234 /]# exit
# docker restart bind
# dig facebook.com @localhost

<should return a recursive DNS response>

# exit

However, the recommended approach is to use this DNS selectively only for
sites you want to proxy (e.g. netflix.com) using something like DNSmasq.

Let me know how you go..

Cheers!

**Comment by opetznick** [comment]
oh alright - your explanation sounds obvious to me... apple tv is restricted to just one dns server so the easiest way to get there would be to open it up for everything
