### ISSUE TITLE
Assistance with install on Azure

### ISSUE THREAD

**Issue by scavern** [ab77/netflix-proxy#20]
I have netflix-proxy running on an Ubuntu VM in Microsoft Azure.

I have setup portforwarding for DNS. DNS queries resolve correctly when I use the VM as my DNS server, however neither Netflix nor Crackle will load. They both resolve to the public IP of the VM which I assume is correct.

Any suggestions?

**Comment by scavern** [comment]
Whoops nevermind! I had to forward port 80 and 443 as well. I didn't know this proxied that traffic as well? I always thought it was only DNS that was the requirement.

**Comment by ab77** [comment]
No worries. The key is in the name "Smart DNS **Proxy**" :)

-- ab1
