### ISSUE TITLE
PSN (This is a DNS error)

### ISSUE THREAD

**Issue by fatsmack** [ab77/netflix-proxy#200]
Hey guys,

Thanks for making this awesome service. Recently on my PS3 I have been getting a 

An error occured during communication with the server.
This is a DNS error.

When trying to login to the PSN.

Remove my DNS and it works fine again. Any suggestions?

**Comment by ab77** [comment]
Does the PS3 support SNI? Test in the built-in browser using the link in the readme.

**Comment by techlantis** [comment]
Yup, it used to work fine and I suspect an upgrade on their servers have changed something.

**Comment by fatsmack** [comment]
Yes, It comes back that it works. This worked fine just recently. Weird.

**Comment by ab77** [comment]
Could you get a tcpdump from your router: `tcpdump -i <lan-interface> -vvv -s 0 -l -n port 53` with the fudged DNS and one without to see what the difference is perhaps?

**Comment by ab77** [comment]
Please register for updates on the mailing list (http://netflix-proxy.belodedenko.me/) RE: August update. An alternative (paid subscription based) unblocking solution is close to being completed and should be going to trial soon.
