### ISSUE TITLE
Ramnode ends up with S7111-1331-5059

### ISSUE THREAD

**Issue by freestylemaster** [ab77/netflix-proxy#201]
Ramnode KVM NY region fresh installation of Ubuntu 14.04 x86_64 Server Minimal. Ramnode IP6 note applied meaning I converted from 64 to 80 and ip6tables rules added. 

Please see below it pings google successfully;
`64 bytes from lga15s45-in-x0e.1e100.net: icmp_seq=1 ttl=57 time=0.643 ms`

Also script finished fine;
```
netflix-proxy-admin site=http://***:8080/ credentials=admin:***
IPv6=Enabled
caching-resolver=Disabled
Hulu region(s) available to you: {'JP': false, 'US': true}
Change your DNS to *** and start watching Netflix out of region.
Done!
```

Current IP also added to authorized IPS.

However I end up with 
`Error Code: S7111-1331-5059 `
Cleared dns, caches databases of the browser on Macbook but still same output.

What do you think is the problem?

Many thanks in advance.

**Comment by ab77** [comment]
RamNode has been blocked by Netflix for ages. I've updated the README.
