### ISSUE TITLE
Exclude Netflix in zone

### ISSUE THREAD

**Issue by freestylemaster** [ab77/netflix-proxy#202]
Even though the original idea was to prevent geoblocking of netflix and so on, I still love the idea to use my vps as my external ip to prevent localisation of some sites like youtube.

I still want to watch Netflix in local region and I am working on to exclude netflix in zone file so netflix sees my real IP but whatever I tried, it still detects my setup and gives me proxy warning.

What am I doing wrong here? 

```
zone "netflix.com." IN {
    type forward;
    forward only;
    forwarders { 8.8.8.8; };
};

zone "nflxvideo.net." IN {
    type forward;
    forward only;
    forwarders { 8.8.8.8; };
};

zone "." {
    type master;
    file "/data/conf/db.override";
};
```

**Comment by ab77** [comment]
Just remove the two Netflix zone blocks all together and restart the bind container.

**Comment by freestylemaster** [comment]
Thanks for your reply.
Actually what I am trying to do is all requests to hit the dns server except Netflix. When I try to access Netflix, the dns server should forward to google dns or whatever. Do you know how I can achive this?

**Comment by ab77** [comment]
Once the DNS request is already on your server, regardless where you then forward it to, Netflix will see the network address of your server. I am not aware of how to specifically exclude domains from BIND, once you've configured a default `dot` zone.

Can you run `dnsmasq` on your local network and and perform DNS "routing" there?

**Comment by freestylemaster** [comment]
I see. I think I will go that way thank you
