### ISSUE TITLE
Run errors on 32bit architecture

### ISSUE THREAD

**Issue by neiliid** [ab77/netflix-proxy#203]
Hi,

This is a noob question apologies to all in advance. I receive the following error when running the build on a 32bit architecture:

proxy / localhost:43867 {
    except /static
    proxy_header Host {host}
    proxy_header X-Forwarded-For {remote}
    proxy_header X-Real-IP {remote}
    proxy_header X-Forwarded-Proto {scheme}
}
Starting 241fec7cbb_241fec7cbb_caddy
**rpc error: code = 2 desc = "oci runtime error: exec format error"**

Not sure if it is a 32bit issue or something else.

Thanks

**Comment by ab77** [comment]
Please register for updates on the mailing list (http://netflix-proxy.belodedenko.me/) RE: August update. An alternative (paid subscription based) unblocking solution is close to being completed and should be going to trial soon.
