### ISSUE TITLE
Failed testing proxy (OpenSSL)...       

### ISSUE THREAD

**Issue by lerhum** [ab77/netflix-proxy#204]
from netflix-proxy.log
```
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;netflix.com.			IN	A

;; ANSWER SECTION:
netflix.com.		86400	IN	A	185.101.98.153

;; AUTHORITY SECTION:
netflix.com.		86400	IN	NS	ns1.netflix.com.

;; ADDITIONAL SECTION:
ns1.netflix.com.	86400	IN	A	185.101.98.153

;; Query time: 1 msec
;; SERVER: 185.101.98.153#53(185.101.98.153)
;; WHEN: Wed Sep 07 14:13:52 BST 2016
;; MSG SIZE  rcvd: 90

Failure! Retrying in 10..
Failure! Retrying in 20..
Failure! Retrying in 40..
Failure! Retrying in 80..
Failure! Retrying in 160..
You've failed me for the last time! (/usr/bin/timeout 10 /usr/bin/openssl s_client -CApath /etc/ssl/certs -servername netflix.com -connect 185.101.98.153:443)
```

Does this mean that hosting is banned? 
Or it's a configuration issue?

**Comment by ab77** [comment]
Iv'e had issues where the `sniproxy` Docker container won't start intermittently due to an error I've not had time to look into. The best workaround is to `Ctrl-Z` out of build.sh, restart the `sniproxy` container manually and return to setup by running `fg %1`.

**Comment by lerhum** [comment]
while it started to display ` * testing proxy (OpenSSL)...    ` i `Ctrl-z`then i `docker restart sniproxy`and after `fg %1`. But build.sh take a long time and never complete.

when i check the log i get 
```
;; Query time: 1 msec
;; SERVER: 185.101.98.153#53(185.101.98.153)
;; WHEN: Thu Sep 08 12:03:23 BST 2016
;; MSG SIZE  rcvd: 90

Failure! Retrying in 10..
Failure! Retrying in 20..
Failure! Retrying in 40..
Failure! Retrying in 80..
Failure! Retrying in 160..

You've failed me for the last time! (/usr/bin/timeout 10 /usr/bin/openssl s_client -CApath /etc/ssl/certs -servername netflix.com -connect 185.101.98.153:443)
```
should i interupt before build.sh testing the proxy ?

**Comment by ab77** [comment]
Does the `sniproxy` container actually run? If so, can you run the test manually? (i.e. `/usr/bin/openssl s_client -CApath /etc/ssl/certs -servername netflix.com -connect 185.101.98.153:443`?

**Comment by lerhum** [comment]
The problem is that `openssl s_client -connect` by default uses TSL v1. But i have SSLV3.

So you have to use

`/usr/bin/openssl s_client -CApath /etc/ssl/certs -servername netflix.com -connect localhost:443 -ssl3`

What do i need to change knowing that for the proxy works ?

**Comment by lerhum** [comment]
it return `CONNECTED(00000003)`

**Comment by ab77** [comment]
Try to see if containers on the box have access to the Internet via IPv4 and also IPv6. There are notes in the README on how to do this.

**Comment by ab77** [comment]
Please register for updates on the mailing list (http://netflix-proxy.belodedenko.me/) RE: August update. An alternative (paid subscription based) unblocking solution is close to being completed and should be going to trial soon.
