### ISSUE TITLE
Digital Ocean IP blocked by both BBC Iplayer and Netflix

### ISSUE THREAD

**Issue by elbow** [ab77/netflix-proxy#205]
Hi,

Just thought I'd drop it to say that my Digital Ocean IP in the 138.68 range is blocked by both BBC Iplayer and Netflix.

I confirmed by actually installing a dockerized Chrome browser (https://hub.docker.com/r/siomiz/chrome/) and trying to access them from that browser.

Regards,
Steve

**Comment by ab77** [comment]
Thanks for the update.

**Comment by kloknibor** [comment]
what is the message you get when your ip is blocked? Tried to acces netflix and returns a streaming error about a proxy, does this mean the ip is blocked? SInce I can normally acces netflix otherwise

**Comment by ab77** [comment]
Does [this](https://github.com/ab77/netflix-proxy/wiki/On-how-Netflix-enforces-geographical-boundaries-in-the-Information-Age..) help?

**Comment by kloknibor** [comment]
@ab77 Thank you! That helped a lot! Indeed the ip is blocked because it's known as cloudhoster ;)!

**Comment by ab77** [comment]
I am sure there are still providers out there, which Netflix hasn't blocked yet. But Digital Ocean is definitely not one of those :)
