### ISSUE TITLE
Zone Websites unavailable

### ISSUE THREAD

**Issue by Scharmen** [ab77/netflix-proxy#207]
Hi, 

Iam sure i did something worng, but i need help :)

My DNS is working i can reach netflix.com. But the bad thing is netflix.com is the only Websites from the zone.override Websites i can reach. 

For example hulu.com doesn't work, my browser say the Websites is unavailable.
If Iam dig hulu.com on my local host it shows the ip of my DNS. 

Any ideas ? 
Thank you!

**Comment by ab77** [comment]
Not sure. Maybe try other sites. What does http://ifconfig.co return?

**Comment by Scharmen** [comment]
It returns the public IP address of my Home Network.

**Comment by ab77** [comment]
Sorry, try http://ipinfo.io

**Comment by Scharmen** [comment]
No problem :). 
Mhm intressting, if Iam using the US DNS i can't reach the Website. Without my (US) DNS i see my public ip.

**Comment by ab77** [comment]
Rebuild from scratch.

**Comment by Scharmen** [comment]
Yes a rebuild fixed the problem!
