### ISSUE TITLE
502 Bad Gateway after build from scratch

### ISSUE THREAD

**Issue by amizzo87** [ab77/netflix-proxy#208]
Everything seems to be building correctly, docker installing etc but build.sh stalls at "testing netflix-proxy admin site...". Looks like it's getting a 502 bad gateway error, which is the same error I get if I try to set my DNS to the external IP of my VPS and load any web page.

Any ideas or logs I could provide to help diagnose this issue? Thanks!

**Comment by ab77** [comment]
`netflix-proxy.log` should give some clues...

**Comment by amizzo87** [comment]
Nothing is standing out in the log. The tests for DNS, OpenSSL, and cURL all say `[OK]` yet "testing netflix-proxy admin site..." results in:
`curl: (22) The requested URL returned error: 502 Bad Gateway Failure! Retrying in 10..`

Is there anything in particular I should be looking for? It seems to be going fine up until curl is returning the 502 error

**Comment by ab77** [comment]
Try starting `netflix-proxy-admin` service manually (run: `service netflix-proxy-admin start').

It probably fails to start for one reason or another (most likely something else already grabbed the port).

**Comment by amizzo87** [comment]
Doesn't seem to help. Here is the result from netstat -anp | grep 8080:

`tcp        0      0 182.160.160.64:39752    182.160.160.64:8080     TIME_WAIT   -               
tcp        0      0 182.160.160.64:39756    182.160.160.64:8080     TIME_WAIT   -               
tcp6       0      0 :::8080                 :::*                    LISTEN      4047/caddy `

**Comment by ab77** [comment]
Check if `netflix-proxy-admin` service is running.

**Comment by amizzo87** [comment]
![screen shot 2016-09-27 at 12 56 36 pm](https://cloud.githubusercontent.com/assets/5224781/18889458/ecf6b6e2-84b1-11e6-9f8b-45330e76950f.png)

It must have something to do with my provider's networking settings or something, as the same configuration works on digital ocean no problem. I'll make a ticket and see if they have any suggestions.

**Comment by ab77** [comment]
Please register for updates on the mailing list (http://netflix-proxy.belodedenko.me/) RE: August update. An alternative (paid subscription based) unblocking solution is close to being completed and should be going to trial soon.

**Comment by Bechrissed** [comment]
@amizzo87  I have the same issue and you already gave the answer yourself. You probably have caddy server running which is using port 8080. How can we change port 8080 for the netflix-proxy @ab77 ?

**Comment by Bechrissed** [comment]
aaaah wait sorry. netflix-proxy is using caddy server lol. I already have a instance of caddy running :p

**Comment by ab77** [comment]
😬
