### ISSUE TITLE
Netflix-proxy in other region (Germany)

### ISSUE THREAD

**Issue by rosch100** [ab77/netflix-proxy#209]
I set up a netflix-proxy in a host in Germany. However, DNS resolution seems not to work correctly. An address (e.g. zdf.de) configured in zones.override does not resolve. If it is not configured in zones.override (e.g. ard.de), it does resolve.
I have both zdf.de and ard.de configured in OSX in /etc/resolver with the same dns IP address of my server in Germany.

How can I debug/investigate further, where the problem is?

By the way, I am running a similar server in the US which works fine for the US hosts.

**Comment by ab77** [comment]
Perhaps start by doing some lookups on the server itself? (e.g. `dig foo.bar @localhost`).

**Comment by ab77** [comment]
Please register for updates on the mailing list (http://netflix-proxy.belodedenko.me/) RE: August update. An alternative (paid subscription based) unblocking solution is close to being completed and should be going to trial soon.
