### ISSUE TITLE
Netflix-proxy in other region (Germany) (ex #209)

### ISSUE THREAD

**Issue by rosch100** [ab77/netflix-proxy#210]
Referring to issue #209:

The dns server on localhost does not resolve the target dns name, if it is in the zones.override.

```
dig www.zdf.de @localhost

; <<>> DiG 9.9.5-9+deb8u7-Debian <<>> www.zdf.de @localhost
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 22970
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.zdf.de.			IN	A

;; Query time: 0 msec
;; SERVER: ::1#53(::1)
;; WHEN: Wed Oct 12 19:53:33 UTC 2016
;; MSG SIZE  rcvd: 39

```
If the name is not in zones.override, everything looks good.

**Comment by rosch100** [comment]
Re-installation (running build.sh) resolved the issue.

**Comment by ab77** [comment]
Try `docker logs -f bind` while you are doing queries against `localhost` and see what gets printed in the logs. I suspect you have a typo in your `zones.override` file.
