### ISSUE TITLE
auth/settings.py doesn't take effect

### ISSUE THREAD

**Issue by Huskion** [ab77/netflix-proxy#211]
I attempted to change the port for the admin auth page to listen on 8081, after which I ran
service netflix-proxy-admin restart

and then swapped the ports in /etc/iptables/rules.v4 from 8080 to 8081 accordingly. The auth system still listens on port 8080 regardless.

**Comment by ab77** [comment]
`https://github.com/ab77/netflix-proxy/blob/master/Caddyfile.template`.

There is a reverse proxy called `Caddy server` running in from on the Python web app. Change the port in `Caddyfile`.
