### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by evildani** [ab77/netflix-proxy#212]
Hello,

I have an isue where my US machine has IPv4 but I have IPv6. When I try to access the web admin console I do see an IPv4, which I added. But when I tryed to stream Hulu I got the Geo Error. 

Should I ask my ISP for an IPv6 I think I can. The tricky part is that I am already runnig a openVPN client on that machine for other purposes and I dont want to break that functionality.

Thanks.

Daniel

**Comment by ab77** [comment]
Where are you hosting this? Hulu is blocked on pretty much everything.

**Comment by evildani** [comment]
Hello,

My company has a spare linux server in florida. 

I checked and the resolution for DNS is correct, if I ask for netflix or hulu I get the my own IP. At least on hulu I get the GEO error. What can I troubleshoot?

Thanks,

Daniel

**Comment by evildani** [comment]
Update: I just checked it works perfectly from a computer. But does not work from Apple TV. I need to check on my Roku.

**Comment by ab77** [comment]
For Apple TV you need to route the device through a VPN, since the app doesn't use DNS to resolve media host names.
