### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by anthonysomerset** [ab77/netflix-proxy#214]
how can i uninstall netflix-proxy if i've decided i no longer wish to use it?

**Comment by ab77** [comment]
Destroy the server or go through the script to see what it does and undo it all manually.

**Comment by anthonysomerset** [comment]
yeah destroying server isn't really an option in my case

was hoping for a high level set of steps, so far i've just assumed stopping and destroying the relevant docker containers and removing the couple of startup services that are created

**Comment by ab77** [comment]
If you kill Docker containers and remove the iptables rules, you should be OK. Also stop `netflix-proxy-admin` service.
