### ISSUE TITLE
Help Installing...

### ISSUE THREAD

**Issue by papacrown** [ab77/netflix-proxy#215]
I'm having trouble running this, I'm trying to get it to run on a Raspberry Pi 3 with Raspbian Jessie installed. I am currently in Mexico, trying to set it up and take the Pi to the US and set it up in a residential IP address. 

I am running the commands in this order:

```
echo net.ipv6.conf.all.disable_ipv6=1 > /etc/sysctl.d/disableipv6.conf
reboot
apt-get update && apt-get -y install vim dnsutils curl sudo git && curl -sSL https://get.docker.com/ | sh && git clone https://github.com/ab77/netflix-proxy /opt/netflix-proxy && cd /opt/netflix-proxy && ./build.sh  
```

When it gets to running ./build.sh, I get a few green OK's then a red Fail for IPv6 Connectivity check, then it just hangs indefinitely at `creating and starting Docker containers... ` then sends me back to the command prompt.

I've tried running ifconfig and looking for a inet6 addr but there aren't any. I've gone to check the log and the error I am getting is: 
_ERROR: for dnsmasq Cannot start service dnsmasq: driver failed programming ext$ Encountered errors while bringing up the project._

My other alternative is running a VPN, which is currently working fine with PiVPN but I would much rather use a Smart DNS. Any hints as to what might be going wrong?

**Comment by ab77** [comment]
Not supported. Different architecture entirely.

Subscribe to the mailing list http://netflix-proxy.belodedenko.me/ to be notified when the subscription service is available (based on RPi3 hardware).
