### ISSUE TITLE
netflix-proxy + vpn/proxy/socks = be awesome again!

### ISSUE THREAD

**Issue by ahmednitul** [ab77/netflix-proxy#223]
hello,

its been long since netflix-proxy stopped working on most of server/hostings, so here i am putting an idea how netflix-proxy can starts working again...

the idea is to use netflix-proxy by connecting thru vpn, proxy and socks services- I do have few thousand US, Canada & UK IP Address which are accessible using pptp vpn protocol, https proxy and socks tunnelling, there are also sellers available who sells these access to private IP addresses for about $0.20 to $3 USD (If this plan can be implemented then I will write a detailed tutorial for 'how to get private usa socks/proxy and vpn accesses' and  also point to the directions of the community/marketplace where such credentials are available for purchase)

so, it would be awesome if admin/developer of this project can create a build/version where users would be able to install netflix-proxy and simply choose which kind of connections they would like to use, like:

1. direct = netflix and other outbound connections would be established using direct internet access.

2. vpn = then user would provide ip/user/pass of the vpn server and netflix-proxy will use it to access netflix.com and other sites.

3. proxy/socks = like vpn, users would just provide IP Address & Ports Number then netflix-proxy will use it to access the services.

---

so, how it would really work is... like as usual netflix-proxy's DNS service would access the services using vpn or proxies and serves to the end-users thru dns.

do let know if its possible and i think it would be really great if netflix-proxy can be used like this :)

thanks.

**Comment by ab77** [comment]
Everything is possible, given enough resources. Happy for anyone to develop the functionality and submit a pull request.
