### ISSUE TITLE
Listen on a different IP address on the same interface

### ISSUE THREAD

**Issue by chasgames** [ab77/netflix-proxy#224]
Having trouble with this, I have an interface ens3 with IP_A and ens3:0 with IP_B.

I want to get the script(mainly the proxy) working on IP_B.

I've done a complete reinstall and edited the build.sh file and changed the IPADDR EXTIP to point to IP_B.

Everything seems OK ..except for it working!, DNS is listening on IP_B, everything tests OK and is built OK, but there is no DNS resolution from my client (even after adding my client IP).

Interestingly if i change my DNS settings on my client to the default IP_A, then everything works fine. Could SNIProxy only be working on the default IP_A? Does IPADDR and EXTIP cover everything?

I can ping in and out OK from IP_B and the iptables is no different.

I can also access IP_B:8080 but i just can't DIG out when my DNS is set to IP_B

**Comment by ab77** [comment]
It should bind to all external IPs, but check with `netstat -a -n -p` to see

**Comment by chasgames** [comment]
The DNS does seem to listen on both IP_A and IP_B, but an ipinfo.io shows the proxy traffic goes out of IP_A by default, so I am wondering how to change the IP address for the proxy traffic

**Comment by ab77** [comment]
Look into how to use `iptables` to do `SNAT` on the outgoing traffic. You can use it to rewrite one source IP to another.

**Comment by chasgames** [comment]
Cool thanks for putting me in the right direction i'll take a look, i just thought perhaps this was a common configuration that was already built into the script.
