### ISSUE TITLE
caching-resolver is ignored

### ISSUE THREAD

**Issue by danielschonfeld** [ab77/netflix-proxy#225]
I could be wrong, but i believe from reading the `build.sh` code that `caching-resolver` if selected on, is ignored as the sniproxy `resolver {}` defaults to always going to `8.8.8.8`

I'll be happy to submit a PR if i'm correct.  Double check me please?

**Comment by ab77** [comment]
It's a bit more involved than that, in `docker-sniproxy/sniproxy.sh` there is some logic to either write out `8.8.8.8` to `sniproxy.conf` or, if the dnsmasq container is linked during `build.sh` (-z option), then use the IP of the linked container. So, no PR necessary, should just work (inspect sniproxy.conf` in the Docker container after build).
