### ISSUE TITLE
Error starting userland proxy: listen udp 0.0.0.0:53: bind: address already in use

### ISSUE THREAD

**Issue by almooj** [ab77/netflix-proxy#226]
new error occur maybe occured by new docker version apparenlty

any hint on that ?

Error starting userland proxy: listen udp 0.0.0.0:53: bind: address already in use

seems to be detailed here
https://github.com/docker/docker/issues/8714

**Comment by ab77** [comment]
Have you checked what other processes on the machine are already bound to port 53/UDP?
