### ISSUE TITLE
How to remove?

### ISSUE THREAD

**Issue by cibban** [ab77/netflix-proxy#227]
I accidentally lost connection with my VPS and installed it on my own Ubuntu PC. How to remove it?

**Comment by 3djake** [comment]
Did you also accidentally install docker from git?
 
You will want to go through the build script and undo unwanted changes made to your computer
https://github.com/ab77/netflix-proxy/blob/master/build.sh

Mainly you will want to undo the changes made your computers firewall(iptables) and disable/remove the docker and netflix-proxy service.

and remove /opt/netflix-proxy
