### ISSUE TITLE
Reduce repo size? Now stands at 114 MiB 

### ISSUE THREAD

**Issue by MinimaxHeadroom** [ab77/netflix-proxy#228]
Would it be possible to drastically reduce the repo size? (For instance, removing objects which are no longer being referenced.)

Upon cloning the repository I was surprised to find it's over 114 MiB in size:

```
$ git count-objects -vH
count: 0
size: 0 bytes
in-pack: 3724
packs: 1
size-pack: 114.09 MiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes
```

Note that the bulk of this is in `.git/objects`.

Considering that the repo appears to mostly be a collection of scripts and config files, is there a need or reason for it to be any more than a few megabytes?

**Comment by ab77** [comment]
If you download the ZIP from GitHub, you'll find it is only 3.2M. You only have to adjust the build instructions slightly to use this, rather than using the `clone` function.
