### ISSUE TITLE
Support for primevideo.com? 

### ISSUE THREAD

**Issue by newsera** [ab77/netflix-proxy#229]
Support for primevideo.com? 

Amazon's Prime Video is now available in more than 200 countries

It would be awesome for this to support primevideo

**Comment by 3djake** [comment]
You mean amazom prime? It does work with amazon, at least it did the last time I used it with digitalocean.

**Comment by ab77** [comment]
You need to look at the actual domain(s) the video comes from by streaming it, while watching the HTTP traffic (e.g. Chrome Dev. Tools).

If a new domain needs to be proxied, just add to the relevant config file and restart. All the info is in the docs.

Cheers!
