### ISSUE TITLE
Iptables help

### ISSUE THREAD

**Issue by txt3rob** [ab77/netflix-proxy#23]
Hi sorry it's not a direct issue but need some help.

what would the best way to allow all BT and Sky ISP to access my server?

i am doing 

```
sudo iptables -I FRIENDS -s 79.0.0.0/24 -j ACCEPT

```

something like that at the moment

**Comment by ab77** [comment]
Hi there, you would have to allow every single BT and Sky IP access to your server, but I wouldn't recommend doing that, as you are opening up your box to denial of service attacks.

In case you still want to do this for some reason, you can get all the ranges for specific ASNs as follows:

    whois -h riswhois.ripe.net -- '-i origin ASN' | grep -Eo "([0-9.]+){4}/[0-9]+"

where `ASN` is either `AS2856` (BT) or `AS5607` (Sky).

However you are still best to authorise individual IPs.:

    sudo iptables -I FRIENDS -s x.x.x.x/32 -j ACCEPT
    iptables-save > /etc/iptables/rules.v4 || iptables-save > /etc/iptables.rules

You could also look into dynamic DNS, but that is a bit messy.

Best solution - request static IP(s) from your ISP, although I am consious BT and Sky don't often do these on consumer connections.

-- ab1

**Comment by nrj** [comment]
Somewhat related question: what is the best way to preserve and revert back to the original iptables configuration? Essentially an uninstall script.

**Comment by ab77** [comment]
There maybe a backup file in /etc/iptables/ or /etc/rules.*

If not, just create a new droplet, take a look at this file and copy and paste the contents.

Cheers!

**Comment by txt3rob** [comment]
http://www.cyberciti.biz/tips/linux-iptables-how-to-flush-all-rules.html

That should help

**Comment by ab77** [comment]
Flushing rules `iptables -F` deletes everything.

If you want to revert back to default ruleset shipped with the distribution, simply copy the relevant file from the vanilla build.

For example:

	Using username "root".
	Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-58-generic x86_64)

	root@test:~# iptables -L
	Chain INPUT (policy ACCEPT)
	target     prot opt source               destination

	Chain FORWARD (policy ACCEPT)
	target     prot opt source               destination
	DOCKER     all  --  anywhere             anywhere
	ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
	ACCEPT     all  --  anywhere             anywhere
	ACCEPT     all  --  anywhere             anywhere

	Chain OUTPUT (policy ACCEPT)
	target     prot opt source               destination

	Chain DOCKER (1 references)
	target     prot opt source               destination

	
	root@test:~# mkdir /etc/iptables

	root@test:~# iptables-save > /etc/iptables/rules.v4

	root@test:~# cat /etc/iptables/rules.v4
	# Generated by iptables-save v1.4.21 on Thu Sep  3 03:32:49 2015
	*nat
	:PREROUTING ACCEPT [4:291]
	:INPUT ACCEPT [4:291]
	:OUTPUT ACCEPT [13:929]
	:POSTROUTING ACCEPT [13:929]
	:DOCKER - [0:0]
	-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
	-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
	-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
	COMMIT
	# Completed on Thu Sep  3 03:32:49 2015
	# Generated by iptables-save v1.4.21 on Thu Sep  3 03:32:49 2015
	*filter
	:INPUT ACCEPT [477:39010]
	:FORWARD ACCEPT [0:0]
	:OUTPUT ACCEPT [368:42876]
	:DOCKER - [0:0]
	-A FORWARD -o docker0 -j DOCKER
	-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
	-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
	-A FORWARD -i docker0 -o docker0 -j ACCEPT
	COMMIT
	# Completed on Thu Sep  3 03:32:49 2015

-- ab1

**Comment by nrj** [comment]
Perfect. Thanks!

**Comment by txt3rob** [comment]
is it possible to do 80.0.0.0 - 188.0.0.0 in one command?
i found some of the ASN for sky was not up to date.

**Comment by ab77** [comment]
Yes, but you'll have to edit the iptables rules manually.

Have a look at iptables [iprange](http://www.cyberciti.biz/tips/linux-iptables-how-to-specify-a-range-of-ip-addresses-or-ports.html) option..
