### ISSUE TITLE
Lost connectivity after editing zones.override file

### ISSUE THREAD

**Issue by jeffe13th** [ab77/netflix-proxy#230]
I was successfully able to get everything to work and even updated the zones.override file for a couple new channels that I unblocked.  After a few days I was editing the zones.override file and must have hit the wrong keyboard combination because I saw  message that said something like "split save" or something with the work "split" in it.  After saving the zones.override and taking a quick peek in the resolve.dnsmask file and then running the docker restart bind command, everything stopped working and my devices lose all connectivity to internet if I use the DNS of my server.

Any ideas of what might be wrong or how to fix it?  Obviously I can just start all over again, which isn't hard.  However, I thought it might be good to figure out what's wrong and learn how to troubleshoot the problem if possible.

Thanks.

**Comment by ab77** [comment]
Try tailing the BIND container logs after restarting it, to see what BIND might be complaining about. There is probably a syntax issue in the `zones.override` file.

Run `docker logs -f bind`.

If all else fails, rebuild.

**Comment by jeffe13th** [comment]
Thank you.  That worked.
