### ISSUE TITLE
How to monitor/manage the sharing with friends (IPs and accounts)

### ISSUE THREAD

**Issue by jeffe13th** [ab77/netflix-proxy#231]
I'd like to share my DNS proxy server with some friends and family but don't necessarily want to service all of their friends and families, etc.  Is there a way that I can easily (or even not so easily) monitor/mange the usage of my DNS proxy server?   I know that I can create the user accounts with expiration dates that I can share with friends/family, which is great.  Is there a way to limit those user accounts to 1 IP so that they don't share their account and it gets out of control?  Also, is there a way that I can tell what IP addresses have been authorized by what accounts and clean that up if necessary?  I want to avoid having the list of authorized IPs grow beyond the current IP addresses of the friends whom I've shared this with.  

I've really enjoyed this netflix-proxy and the service has been great at home!  Thank you to all who have helped put this together and shared it with the rest of us.  I really appreciate it, especially since I live overseas and have missed a lot of the programming from back home.

**Comment by ab77** [comment]
What you are talking about here is certainly possible, but unfortunately not without a major re-write of the auth backend, which was originally never meant to be very sophisticated.

Some of the features you are proposing also require network level authentication, which I don't think is the right domain for SNI Proxy. A VPN (e.g. OpenVPN) might be a better candidate here.

So in short - yes, all possible, but will require an almost complete re-development of the current solution.

-- ab1
