### ISSUE TITLE
Wildcards or ways to unblock all variations of a specific domain

### ISSUE THREAD

**Issue by jeffe13th** [ab77/netflix-proxy#233]
Is it possible to use wildcards to unblock all levels of a specific domain rather than having to create a new entry for each one in the zones.override file?  For example, if I needed to unblock several different subdomains for akamai.net...

a112.w23.akamai.net.
a766.w23.akamai.net.
a65.w23.akamai.net.

Could I just use:

zone "akamai.net." {
    type master;
    file "/data/conf/db.override";
};

or

zone "*.akamai.net." {
    type master;
    file "/data/conf/db.override";

I've tried using the specific video feed domain but then it will change a few days later to have a different subdomain.  I'd like to simplify the management of the server as much as possible to account for these subtle changes if possible without having to login and check the network traffic each time.

Thanks for your advice.

**Comment by ab77** [comment]
I am pretty sure that is how it works already. Defining `zone "akamai.net."...` will cover `*.akamai.net`. Try it.

**Comment by carlrygart** [comment]
Yes, indeed that's correct. However, it would be great if it would be possible to use regex for defining the zones. For example: You would not want to add the whole domain akamaihd.net. Some streaming sites do not geocheck origin akamaihd.net and some do. For example, in Sweden tv4play.se does not geocheck akamaihd.net, but svtplay.se does (they both use the same streaming provider). Unfortunately, SVT use several servers at akamaihd.net, which means that either have to add all of them (hard to know them all) or just add whole akamaihd.net (which is not good).

So to my question: Is it any possiblity to use regex like this?
"(.*svt.*).akamaihd.net."
to cover
svtplay9p-f.akamaihd.net.
svtplay5i-f.akamaihd.net.
svt01-lh.akamaihd.net.
etc.

**Comment by svempa434** [comment]
carlrygart: I think you can do it by implementing your own dns server in perl using http://search.cpan.org/dist/Net-DNS/lib/Net/DNS/Nameserver.pm .

**Comment by ab77** [comment]
Agreed, because: http://serverfault.com/questions/133707/is-it-possible-to-have-regular-expression-cname-record-in-dns

**Comment by carlrygart** [comment]
Okay, I will probably look into that later. Thanks 👍
