### ISSUE TITLE
OpenSSL error

### ISSUE THREAD

**Issue by CryogenicPilot** [ab77/netflix-proxy#234]
Hi,

I am getting this error on openssl test phase after launching build.sh:

CONNECTED(00000003)
140040142341792:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:795:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 315 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE

How can I fix it?

Thanks

**Comment by ab77** [comment]
Try without IPv6, try a different server, different provider, etc. If you are deploying on a box with IPv6, the script is brittle and may configure Docker with faulty network stack.

**Comment by CryogenicPilot** [comment]
Why is this happening?

**Comment by ab77** [comment]
`docker exec -ti sniproxy bash` and go from there. Try `ping google.com` and `ping6 google.com` first.
