### ISSUE TITLE
HBO Go Support?

### ISSUE THREAD

**Issue by majksner** [ab77/netflix-proxy#235]
Can't get it even with the zone editing, is this way blocked or I'm doing something wrong?

**Comment by ab77** [comment]
Could be blocked. I have no experience with HBO Go. Try a few different USA hosts and if you still get the same issue, try http://www.belodedenko.me/black.box/.

-- ab1

**Comment by ab77** [comment]
You could try the following domains `hbo.com, hbogo.com, go.com, hbonow.com`. This is what I am using with `black.box` and it seems to work, although I can't verify fully since I don't have a subscription.

**Comment by adrianmihalko** [comment]
@ab77 how can I add new domains?
