### ISSUE TITLE
dynamic ip auth

### ISSUE THREAD

**Issue by dzebrys** [ab77/netflix-proxy#236]
hi, great project. i'm using it on aftv and when my isp change my ip then box is unusable until i re-authenticate client.
is there a way to authorize range of ip addresses (defined by mask or wildcard) or to auth dns domain updated via ddns instead of ip address? is such change contradicts with current design and is major rework or it's doable?

regards

**Comment by ab77** [comment]
The only way to do this is to have a DDNS client somewhere update a host record pointing to your current public IP and to have a script on the proxy box constantly check it and update iptables rules (or fire off a HTTP request to authenticate the IP automatically).

**Comment by Balls0fSteel** [comment]
You could use "no-ip.com" (free AFAIK, very small few KB client), and use a Cron script on the server to update the IP every ...few minutes. (It's not much resources, and would run only for a few moments each time.)

**Comment by dzebrys** [comment]
thank you! I'm going to test it on my vc proxy soon.


pozdrawiam piotr On Tue, Jan 17, 2017 at 10:36pm, Duke < notifications@github.com [notifications@github.com] > wrote:
So it's my first time to use this script (it's a great script/product ab77, by the way, very well made.)
It seems like my IP is in netflix-proxy/data/conf/db.override

And it's the last three lines.
I wrote a quick and dirty script to do this. (I know it will make you nauseous.)

 1. Replace "MYHOST" on top
 2. Put this script into your cron.

#!/bin/bash

# STATIC
TARGET="/opt/netflix-proxy/data/conf/db.override"

# Add your dynamic host here - get one for free at no-ip.com
MYHOST="www.insertyourdynamicdomainhere.com"

# Get new ip
NEWIP=`dig +short $MYHOST`
# Generate date for serial
TDATE=`date +"%Y%m%d"`

# Remove last 3 lines from auth file
# head -n -2 /opt/netflix-proxy/data/conf/db.override

# Better method, we will build up the file from sratch (failsafe)
rm -f $TARGET

# Content
echo "$TTL  86400" >> $TARGET
echo "" >> $TARGET
echo "@   IN  SOA ns1 root (" >> $TARGET
echo "            $TDATE  ; serial" >> $TARGET
echo "            604800      ; refresh 1w" >> $TARGET
echo "            86400       ; retry 1d" >> $TARGET
echo "            2419200     ; expiry 4w" >> $TARGET
echo "            86400       ; minimum TTL 1d" >> $TARGET
echo "            )" >> $TARGET
echo "" >> $TARGET
echo "    IN  NS  ns1" >> $TARGET
echo "ns1 IN  A   $NEWIP" >> $TARGET
echo "@   IN  A   $NEWIP" >> $TARGET
echo "*   IN  A   $NEWIP" >> $TARGET

# Done!

**Comment by Balls0fSteel** [comment]
Yeah I didn't have the chance, because Netflix is blocked on Vultr and Linode.
Also tried to deploy an AWS (EC2) machine, but the tests fail at the end.

**Comment by ab77** [comment]
Get a Raspberry Pi and [http://bit.ly/2jBafcd](http://bit.ly/2jBafcd). Currently free, use Testnet coins to activate. Netflix and Hulu both work.

**Comment by dzebrys** [comment]
my deployment is on aws (and i'm proxing amazon product). in db.override there is not client IP but vc instance external ip (= dns ip)

the only files that matches my client ip are:
from netflix-proxy: auth/db/auth.db
from sys: /etc/iptables/rules.v4

it would be easiest to modify iptable rule by cron script with sed and apply it with iptables-apply.

so i made such script:

```
#!/bin/bash

# iptables file
TARGET="/etc/iptables/rules.v4"

# Add your dynamic host here
MYHOST="yourhost.ddns.net"

OLDIP=`cat $TARGET | grep 'PREROUTING -s' | cut -f4 -d" " | cut -f1 -d"/"`
NEWIP=`dig +short $MYHOST`

# modify iptables rules
sed -i s/$OLDIP/$NEWIP/g $TARGET

# apply iptables modification
iptables-apply $TARGET
```

and then copied it to /etc/cron.hourly

@ab77, also i've spot this iptables.v4 seems have duplicates both in first section as in second. it just keep the history of my ip addresses at least :) meybe it's because web interface does not provide the list of last added ip addresses.

**Comment by Balls0fSteel** [comment]
Yeah I am truly sorry. I was in a hurry and I also deployed on a blocked service first. Only yesterday did I see that iptables is used. Don't know how my ip only ended up there.

@dzebrys: Thank you for the script.
How did you install the proxy on Amazon though?
For me, it gets stuck at the testing. Ab77 said its due to the iptables rules (security group thing on Amazon isn't compatible with it).
But then how do I apply those? How did you fix the script?

**Comment by Balls0fSteel** [comment]
I mean my IP was only found in that file, so that's where I got the idea about where to put the IP .

**Comment by dzebrys** [comment]
those are my notes from installing. i remember test was not working but if i'm correct it does not affect service. i'm using it for amazon prime so can't say if it works for netflix, doubt as aws does not support ipv6.

=========================================================

auto deploy from
https://github.com/ab77/netflix-proxy/tree/new-auth

aws ec2 instance t2.micro
aws region n.virgini, us-east-1a
using ubuntu img

to fix locale settings:

locale-gen en_US en_US.UTF-8 pl_PL pl_PL.UTF-8 && dpkg-reconfigure locales

apt-get update && apt-get -y install vim dnsutils curl sudo git 
curl -sSL https://get.docker.com/ | sh 
git clone -b new-auth https://github.com/ab77/netflix-proxy /opt/netflix-proxy 
cd /opt/netflix-proxy 
./build.sh -c <your client ip address>

test with:
curl -H "host: netflix.com" <your ec external address> -v -L

or going to sites 
http://ipinfo.io
https://sni.velox.ch

redeployment/cleanup
  sudo docker stop bind sniproxy && \
  sudo docker rm bind sniproxy && \
  sudo iptables -F && \
  sudo iptables -F -t nat && \
  sudo ip6tables -F && \
  sudo ip6tables -F -t nat && \
  sudo iptables -X ALLOW && \
  sudo iptables -X FRIENDS && \
  sudo ip6tables -X ALLOW
  sudo service docker restart && \
  sudo cd / && \
  sudo rm -rf /opt/netflix-proxy

**Comment by Balls0fSteel** [comment]
Thank you @dzebrys, pure awesomeness! 👍

**Comment by jeffe13th** [comment]
I created the script posted by @dzebrys and scheduled a cronjob to run every 15 minutes to run the script and update the IP address.  For some reason my cronjob is running just fine but the IP rules.v4 file isn't getting updated.  Any ideas??

**Comment by drallgood** [comment]
@jeffe13th I think this happens because iptables-apply asks for confirmation (which it never receives) and then rolls back the changes.
You can change the line to `echo "y" | iptables-apply $TARGET` and it will work

**Comment by drallgood** [comment]
btw: I'm working on a better solution, that will allow for multiple DDNS entries and automatic updates.
Haven't used python in a while so what I come up with might not be the most elegant solution ever, but it'll work

**Comment by drallgood** [comment]
@ab77 Is there a mechanism for updating the database schema?
I would need to add a new table for this to work.

**Comment by ab77** [comment]
Please Google `SQLite schema update`.

**Comment by drallgood** [comment]
@ab77 I know how to update schemas in SQLite. I was asking about how this is handled in this project ;)
Guess there is no such process yet.

**Comment by ab77** [comment]
@drallgood: from memory I created that DB a long time ago and it has never had an update, until now. I'll try to get my head around your PR and kick the tyres a bit. Looks like you've done a bit of work, thank you!

-- ab1
