### ISSUE TITLE
Enable TCP

### ISSUE THREAD

**Issue by carlrygart** [ab77/netflix-proxy#237]
So I got some problems getting answer from my VPS for domains like images.apple.com (and several others). Dig said:
~~~
dig images.apple.com
;; Truncated, retrying in TCP mode.
;; Connection to ***.***.***.*** #53(***.***.***.***) for images.apple.com failed: connection refused.
~~~
So I enabled TCP by adding following rules to iptables:
~~~
sudo iptables -t nat -A PREROUTING -i ${IFACE} -p tcp --dport 53 -j REDIRECT --to-port 5353 && \
sudo iptables -A INPUT -p tcp -m tcp --dport 5353 -j ACCEPT && \
sudo iptables -A INPUT -p tcp -m tcp --dport 53 -j ACCEPT && \
~~~
Inserted them on position INPUT 6 and INPUT 8 respectively. 

And then enabled TCP port 53 for the bind container by adding following in docker-compose/netflix-proxy.yaml.template:
~~~
    - "53:53/tcp"
~~~

Now everything works like a charm. Is there anything that I might have missed out on? Anything that makes this insecure regarding DDoS etc?

**Comment by ab77** [comment]
Is there any reason you want to run DNS over TCP rather than default (and arguably faster) UDP?

**Comment by carlrygart** [comment]
Yes, as I wrote in my first post: When querying the server for some particular adresses (i.e. images.apple.com), I get no answer because of the size of the message. Or have I missed something?

**Comment by ab77** [comment]
Do you get the same when you `dig images.apple.com @8.8.8.8`?

**Comment by carlrygart** [comment]
No, 8.8.8.8 does answer correctly.

**Comment by ab77** [comment]
I just built a fresh proxy on a Digital Ocean server:

```
$ dig images.apple.com @138.68.x.y

; <<>> DiG 9.8.3-P1 <<>> images.apple.com @138.68.x.y
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27324
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 13, ADDITIONAL: 0

;; QUESTION SECTION:
;images.apple.com.              IN      A

;; ANSWER SECTION:
images.apple.com.       1177    IN      CNAME   images.apple.com.akadns.net.
images.apple.com.akadns.net. 299 IN     CNAME   images.apple.com.edgesuite.net.
images.apple.com.edgesuite.net. 19603 IN CNAME  images.apple.com.edgesuite.net.globalredir.akadns.net.
images.apple.com.edgesuite.net.globalredir.akadns.net. 3599 IN CNAME a199.dscgi3.akamai.net.
a199.dscgi3.akamai.net. 19      IN      A       104.86.110.240
a199.dscgi3.akamai.net. 19      IN      A       104.86.110.226
...
;; Query time: 1699 msec
;; SERVER: 138.68.x.y#53(138.68.x.y)
;; WHEN: Sat Jan 28 17:19:07 2017
;; MSG SIZE  rcvd: 446
```

Works fine. Could there be something between your client and the proxy fiddling with network traffic, like a (miss-configured?) firewall?

-- ab1

**Comment by carlrygart** [comment]
Hmm, that's strange. I don't think there's any firewall in between. Anyway, it doesn't really matter if some queries once in a while are handled with TCP. But back on topic, is there anything that makes this insecure regarding DDoS etc?

**Comment by ab77** [comment]
Well, you've opened an extra ports, so the attack surface increased. Something to thing about. Also, DNS TCP is used for zone transfers. Make sure you can not do a zone transfer from an unauthorised IP, just to be sure. Lookup how to do it with `dig`.

**Comment by carlrygart** [comment]
Zone transfers seems to be blocked. This is the output:
~~~
$ dig axfr @xx.xx.xx.xx svtplay.se +tcp

; <<>> DiG 9.9.5-9+deb8u9-Debian <<>> axfr @xx.xx.xx.xx svtplay.se +tcp
; (1 server found)
;; global options: +cmd
; Transfer failed.
~~~

**Comment by ab77** [comment]
Looks good then.

**Comment by carlrygart** [comment]
Perfect! Thanks! Let's close this issue then.
