### ISSUE TITLE
Host a webserver on the same VPS

### ISSUE THREAD

**Issue by griffon56** [ab77/netflix-proxy#239]
Hi

First I would like to thank the developper of this great tool.
I have created a VPS on DigitalOcean, using the provided link.
The smartvpn feature is working great !

Just - I would like to mutualize this VPS to host my webserver.

I configured sniproxy.conf file to redirect http to the local IP,

```
user daemon
pidfile /var/tmp/sniproxy.pid

listener 80 {
    proto http
    table
    fallback 127.0.0.1:8080
}

listener 443 {
    proto tls
}

table {
    MYWEBSITEURL MY_VPS_IP:WEBSERVER_PORT
    .* *
}

resolver {
  nameserver 8.8.8.8
```
It works with a netflix-proxy-registered IP but any public IP that is not registred is redirected to port 8080 login page. 

What would be the good way to go ?

Many thanks for your help.

**Comment by ab77** [comment]
This is by design. Unless you want to open your proxy up for the world, I would suggest not mixing the two workloads together.

-- ab1

**Comment by griffon56** [comment]
Thanks for the feedback.
