### ISSUE TITLE
help

### ISSUE THREAD

**Issue by crisluda** [ab77/netflix-proxy#243]
I have set my DNS ip to de Droplets ip but can visit any sit
![netf](https://cloud.githubusercontent.com/assets/25713340/22858004/b3abb31a-f0a9-11e6-99c1-3ad1b859e387.png)
![netf1](https://cloud.githubusercontent.com/assets/25713340/22858005/b3e340e6-f0a9-11e6-9afe-9ad79f4a8860.png)

**Comment by ab77** [comment]
Your build failed, check log.
