### ISSUE TITLE
Refusing to proxy to socket address literal x.x.x.x in request - Azure Ubuntu VM

### ISSUE THREAD

**Issue by sandeeprawat** [ab77/netflix-proxy#245]
Unable to run it on a new azure VM even though I have another instance of proxy running from a year on the classic azure VM. Tried with latest snapshot as well as same commit hash as the one in my working machine but it fails on my new VM. 

Following are the log entries from sniproxy container 
Setting sniproxy resolver to 8.8.8.8
Command line is not complete. Try option "help"
2017-02-22 17:17:15 Parsed .* *
2017-02-22 17:21:30 Refusing to proxy to socket address literal x.x.x.x in request
2017-02-22 17:21:30 Refusing to proxy to socket address literal x.x.x.x in request
2017-02-22 17:21:40 Refusing to proxy to socket address literal x.x.x.x in request
2017-02-22 17:21:41 Refusing to proxy to socket address literal x.x.x.x in request
2017-02-22 17:22:42 recv(): Connection reset by peer, closing connection
2017-02-22 17:29:22 recv(): Connection timed out, closing connection
2017-02-22 17:41:42 Refusing to proxy to socket address literal x.x.x.x in request
2017-02-22 17:41:43 Refusing to proxy to socket address literal x.x.x.x in request

**Comment by ab77** [comment]
This commit is from `30 Nov 2015` and a lot of things changed since then, especially in the `iptables` space. Azure VMs do not have public IPs assigned directly to the network interfaces since there is NAT happening on the firewall in front of the server(s). The entire IP auth logic needs to be re-written to support this mode of operation (i.e AWS and Azure).

You can manually drop all the `iptables` rules on the host and control access solely by the Azure firewall instead.

-- ab1

**Comment by sandeeprawat** [comment]
sorry. My initial observations were incorrect. Updated the topic/body. It wasn't working even with old snapshot on new VM and client was falling back to secondary dns hence the incorrect observation. 
I iptables from the build script and dropped all the rules too so it shouldn't be an issue. What should I look for? I also have public IP assigned to my VM which looks correct in the db.override

**Comment by sandeeprawat** [comment]
Bind logs

> 22-Feb-2017 18:09:57.341 client 172.17.0.1#51154 (github.com): query: github.com IN A + (172.17.0.2)
> 22-Feb-2017 18:09:58.789 network unreachable resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 2001:4860:4860::8844#53
> 22-Feb-2017 18:09:58.947 client 172.17.0.1#51096 (v10.vortex-win.data.microsoft.com): query: v10.vortex-win.data.microsoft.com IN A + (172.17.0.2)
> 22-Feb-2017 18:09:58.947 network unreachable resolving 'v10.vortex-win.data.microsoft.com/A/IN': 2001:4860:4860::8844#53
> 22-Feb-2017 18:09:59.102 client 172.17.0.1#51096 (v10.vortex-win.data.microsoft.com): query: v10.vortex-win.data.microsoft.com IN A + (172.17.0.2)
> 22-Feb-2017 18:09:59.353 client 172.17.0.1#51154 (github.com): query: github.com IN A + (172.17.0.2)
> 22-Feb-2017 18:10:00.105 client 172.17.0.1#51096 (v10.vortex-win.data.microsoft.com): query: v10.vortex-win.data.microsoft.com IN A + (172.17.0.2)
> 22-Feb-2017 18:10:00.252 network unreachable resolving 'v10.vortex-win.data.microsoft.com/A/IN': 2001:4860:4860::8888#53
> 22-Feb-2017 18:10:00.389 network unreachable resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 2001:4860:4860::8888#53
> 22-Feb-2017 18:10:02.118 client 172.17.0.1#51096 (v10.vortex-win.data.microsoft.com): query: v10.vortex-win.data.microsoft.com IN A + (172.17.0.2)
> 22-Feb-2017 18:10:02.287 network unreachable resolving 'github.com/A/IN': 2001:4860:4860::8888#53
> 22-Feb-2017 18:10:02.288 network unreachable resolving './NS/IN': 2001:4860:4860::8888#53
> 22-Feb-2017 18:10:03.357 client 172.17.0.1#51154 (github.com): query: github.com IN A + (172.17.0.2)
> 22-Feb-2017 18:10:04.891 network unreachable resolving 'E.ROOT-SERVERS.NET/AAAA/IN': 2001:4860:4860::8844#53
> 22-Feb-2017 18:10:06.117 client 172.17.0.1#51096 (v10.vortex-win.data.microsoft.com): query: v10.vortex-win.data.microsoft.com IN A + (172.17.0.2)
> 22-Feb-2017 18:10:09.412 network unreachable resolving './NS/IN': 2001:4860:4860::8888#53

sni log

> 2017-02-22 17:45:15 recv(): Connection reset by peer, closing connection
> 2017-02-22 17:46:10 recv(): Connection reset by peer, closing connection
> 2017-02-22 17:55:05 recv(): Connection reset by peer, closing connection
> 2017-02-22 18:08:17 recv(): Connection reset by peer, closing connection
> 2017-02-22 18:08:32 recv(): Connection reset by peer, closing connection
> 2017-02-22 18:11:22 Refusing to proxy to socket address literal x.x.x.x in request
> 2017-02-22 18:11:22 Refusing to proxy to socket address literal x.x.x.x in request

**Comment by ab77** [comment]
Your Docker container thinks it has IPv6 access and is using IPv6 IPs to resolve root DNS servers, but it looks like your IPv6 stack isn't working (network unreachable).

Does the build script detect IPv6?

**Comment by sandeeprawat** [comment]
Think it did. I ried to disable IP6 on the machine and now i cant log back in. Let me build a new machine and try from scratch. Will update the thread.

**Comment by sandeeprawat** [comment]
Rebuilding from scratch worked. Probably I messed up something in the previous attempt. 
Still have some entries for like this in bind logs but I don't think they are causing any issues

> 
> 22-Feb-2017 20:46:43.690 network unreachable resolving 'prod-na.reverseproxy-onenote.com.akadns.net/A/IN': 2001:4860:4860::8888#53
> 22-Feb-2017 20:46:43.691 network unreachable resolving 'prod-na.reverseproxy-onenote.com.akadns.net/A/IN': 2001:4860:4860::8844#53
> 22-Feb-2017 20:46:43.843 client 172.17.0.1#35997 (mtalk.google.com): query: mtalk.google.com IN A + (172.17.0.3)
> 22-Feb-2017 20:46:43.843 network unreachable resolving 'mtalk.google.com/A/IN': 2001:4860:4860::8888#53
