### ISSUE TITLE
Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by Huskion** [ab77/netflix-proxy#246]
I am running `netflix-proxy` on a Linode (UK data centre) using Ubuntu 14.04 LTS as per instructions.

As of a couple of days ago, an update has prevented Docker from working properly.

any interaction with Docker results in 

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Re-imaging the Linode and installing `netflix-proxy` using the `build.sh` script from scratch (after commenting out the netflix and openSSL checks which cause the script to hang) does not help.

Any suggestions?

**Comment by ab77** [comment]
Build log (i.e netflix-proxy.log)?

**Comment by Huskion** [comment]
[netflix-proxy.txt](https://github.com/ab77/netflix-proxy/files/796850/netflix-proxy.txt)

**Comment by ab77** [comment]
First, are you running as root? Second, Linode public IP i bound to the box or to the firewall?

**Comment by Huskion** [comment]
Yes, I'm running as root - and the public IP is bound to the machine. 

It's literally a fresh deployment of the 14.04 LTS image, no user accounts made, log in as root and run the commands you have listed in the guide, so no other data or modifications to the VPS.

However, in `build.sh` I commented out "testing DNS", "testing proxy (OpenSSL)" and "testing proxy (cURL)" lines because they will fail anyway (Netflix blocks Linode). Without doing this the script hangs during these checks.

**Comment by ab77** [comment]
Couple of things to try.  Build without IPv6 stack on the box. If that works, try again with IPv6, but when the script starts running the tests, suspend it and run `ip6tables -t nat -A POSTROUTING -o eth0  -j MASQUERADE` (substitute actual public iface if not eth0).

-- ab1

**Comment by Huskion** [comment]
With ipv6 disabled on the host, it builds fine - I haven't tried suspending the script during the testing phase. Is ipv6 necessary for use with BBC iPlayer? Most British household ISPs do not use ipv6 yet.

**Comment by ab77** [comment]
IPv6 is not necessary. It is a hang-over from the Netflix/Tunnelbroker saga.

**Comment by Huskion** [comment]
Then, as I have no use for ipv6 for the moment, and only need the system for BBC iPlayer/ITV/Channel4 access, I think it's better to keep it off!
Thanks for the help.
