### ISSUE TITLE
Netflix error.

### ISSUE THREAD

**Issue by qasimakhan** [ab77/netflix-proxy#247]
Hi i have successfully installed and run this proxy, I can see US content on netflix but when i try to play something it gives error that you are using DNS Proxy and fails to load video? Do i need to update something else for it to work?

**Comment by ab77** [comment]
You are a bit late. Netflix blocked all of the known hosting providers. If you find one that still works, keep in to yourself.

**Comment by unlocKing** [comment]
Should this still work for other geo-blocked tv channels?

**Comment by ab77** [comment]
Depends. You mileage may vary.

**Comment by sandeeprawat** [comment]
You should probably change the repository name to something more generic (probably at the cost of reducing hit count)

**Comment by ab77** [comment]
Yeah, this idea does come up once every so often, but it's too difficult to change now - too many links in place all over the place. If you look in zones.override, there are a ton of services in there, some of which work and some don't. Some I've not even heard of.

**Comment by qasimakhan** [comment]
I guess all big names in Hosting providers must be blocked. I wonder if there is some other way for them to know if we are using Proxy service.

**Comment by ab77** [comment]
Put your public IP into `http://www.ip2location.com/demo`. If it says anything other than "Fixed line ISP", it's probably blocked or will be blocked as soon as you start using it. Providers use these databases together with their own business logic to work out IPs/ranges to block.

**Comment by sandeeprawat** [comment]
I have this weird issue where even though I have removed netflix entries from my zones.override and I am expecting Netflix to use my local region it's still giving me Proxy error. For some reason netflix app believes I am trying to circumvent the block even though I am not. How can I debug this?

**Comment by ab77** [comment]
Check you are getting the correct (unmodified) response from your DNS server when you query netflix.com domain. Also check DNS cache (OS/browser), etc.
