### ISSUE TITLE
Not working after VPS rebuild

### ISSUE THREAD

**Issue by JamesK852** [ab77/netflix-proxy#250]
I had this working great for about a day but then I decided to start from scratch and rebuild my VPS. After which I can't seem to get it running correctly, every time I try to access www.pandora.com I sometimes get "Backend not available" or 

www.pandora.com uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

from chrome. Netflix will get the same error if I use https:// but will also sometimes load inconsistently. Any help would be appreciated. 

Log Output Attached

[netflix-proxy.txt](https://github.com/ab77/netflix-proxy/files/847449/netflix-proxy.txt)

**Comment by ab77** [comment]
See if you have curl, if not install it.

**Comment by JamesK852** [comment]
I didn't have curl, I installed it and reran build.sh but I have the same problem :(

**Comment by JamesK852** [comment]
Removed docker containers, removed images, rm -rf /opt/netflix-proxy. Re-cloned the git, and ran build.sh again still with the same problem however I do note that when running build.sh "Configuring upstart" fails.

**Comment by JamesK852** [comment]
I've done another rebuild, not entirely sure what the problem was but seems to work now (I suspect it might have been my IPtables conf). Thanks for your help

**Comment by JamesK852** [comment]
Redid everything from scratch, with curl installed before clone and build, with the same error. This is such a weird problem, I'm going to give it a few days to see if its my VPS provider problem.

**Comment by mikeyjk** [comment]
I'm having this issue as well on DO, docker + ubuntu 16 one click app.

**Comment by JamesK852** [comment]
Who is your VPS provider? I'm still stuck unfortunately, really regret rebuilding my VPS because it was working flawlessly before. 

I'm wondering if its to do with this

/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting dnspython (from -r /opt/netflix-proxy/auth/requirements.txt (line 1))
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
[netflix-proxy2.txt](https://github.com/ab77/netflix-proxy/files/853891/netflix-proxy2.txt)

**Comment by ab77** [comment]
Can you try on a known working provider like Digital Ocean, just to rule out a few things?

**Comment by JamesK852** [comment]
Vps provider moved me to a different node, fixed the problem

**Comment by andresmorago** [comment]
hello
im having the same issue after a fresh install on an ec2 instance. Once i try to access pandora.com i get "SSL_ERROR_NO_CYPHER_OVERLAP". also, when i go to ec2IP:443, i will get the same error.
I have curl installed
