### ISSUE TITLE
How to update old version

### ISSUE THREAD

**Issue by IkenHuub** [ab77/netflix-proxy#252]
Hi,

I still have a version without the update.sh script. How can I update to the latest version?

Thank you.

**Comment by ab77** [comment]
Easiest way is to re-build on a fresh server.

**Comment by IkenHuub** [comment]
Haha ok clear. The old version still works btw. Should I update? And does the new version autoupdate?

Thanks!

**Comment by ab77** [comment]
There are no auto-updates, apart from the ddns stuff. Should you update? That is entirely up to you.

**Comment by IkenHuub** [comment]
Ah ok so if you update something you basically have to re-build on a fresh server if you want it?
All clear. Everything still works so for now I'll leave it as is.

Thanks for answering and also for creating this. :)

**Comment by ab77** [comment]
You are very welcome.
