### ISSUE TITLE
Will it work on 16.04.2 LTS ?

### ISSUE THREAD

**Issue by IkenHuub** [ab77/netflix-proxy#253]
What the subject says, will it work on 16.04.2 LTS ?

**Comment by ab77** [comment]
It depends. Some provider images may work out of the box, some not so. Try it and see what happens.

**Comment by dzebrys** [comment]
i've deployed it on ubuntu 16.04 on aws and need to modify build.sh a little.

main change is to replace docker daemon cmd with dockerd
```
-      printf '[Service]\nEnvironmentFile=-/etc/default/docker\nExecStart=\nExecStart=/usr/bin/docker daemon $DOCKER_OPTS -H fd://\n' | \
+      printf '[Service]\nEnvironmentFile=-/etc/default/docker\nExecStart=\nExecStart=/usr/bin/dockerd $DOCKER_OPTS -H fd://\n' | \
```

also commented out testing steps as were hanging a lot 
```
log_action_begin_msg "testing DNS"
  [...]
printf "\nnetflix-proxy-admin site=http://${EXTIP}:8080/ credentials=\e[1madmin:${PLAINTEXT}\033[0m\n"
```
note: keep the last line above active to be able to see admin credentials!

seems in those testing steps the timeout or skip on error is not working as expected and the script just hang out if anything wrong (like ipv6 not available, docker down, etc.). maybe it's worth to add option to safely skip those and verify deployment manually?

**Comment by ab77** [comment]
I've pushed an update to auto-detect `dockerd` vs. the `docker daemon`.

Regarding tests - they will break on servers where the external IP of the server is not physically assigned to the local interface. A few providers do NAT on their networking stack in front of the hosted kit. In this case, the tests will currently fail.

**Comment by ab77** [comment]
I've also decreased the retry timeout and moved the print statements before the tests, so at least the info will be available.
