### ISSUE TITLE
How to allow firewall access for different port?

### ISSUE THREAD

**Issue by ahmednitul** [ab77/netflix-proxy#254]
Hello,

It seems that after installing netflix-proxy, it re-writes iptable rules and all other services except netflix-proxy and SSHD (22) stops working.

Say, I'm running ftpd on the main server on port 21 and I would like to allow public/firewall access to that port, how do I do that?

Thanks.

**Comment by ahmednitul** [comment]
Anyone can please follow-up on this?

**Comment by ab77** [comment]
Don't need do it on the same server, separate the services onto different machines or work out how to patch the firewall rules manually after installing.
