### ISSUE TITLE
ddns updater not working

### ISSUE THREAD

**Issue by crackers8199** [ab77/netflix-proxy#257]
the cron job for the ddns updater isn't working...it never updates the IPs.  it appears to be running, i can see lines in the syslog for the script running every five mins, but the IP is never updated.  it just stays blank.

the script itself does work, if i run it manually from the command line it works and updates the IPs...but it just isn't working via cron.  any idea how to resolve this?

**Comment by crackers8199** [comment]
can anyone help me with this?  i really would like to get this working, but the ddns just isn't updating...

**Comment by ab77** [comment]
Maybe put some debug into the script to see what it does when run from cron?
