### ISSUE TITLE
stuck on installation

### ISSUE THREAD

**Issue by inet45** [ab77/netflix-proxy#258]
using Ubuntu 14.04 64bit
everything runs with no error until this part:
installing python-pip and docker-compose

it takes very long time and usually i end up with re-establishing the ssh session and the proxy not working, tried to do the installation many time but no luck

**Comment by ab77** [comment]
Might want to check the log file..

**Comment by inet45** [comment]
as per the log file, this will be the last thing:

status: Downloaded newer image for abiosoft/caddy:latest
Pulling bind (ab77/bind:latest)...
latest: Pulling from ab77/bind

**Comment by ab77** [comment]
If it is getting stuck at that step, it is most likely a problem with the connectivity between the host and DockerHub. Try a different host/region?
