### ISSUE TITLE
Help with Docker

### ISSUE THREAD

**Issue by steviedeehook** [ab77/netflix-proxy#259]
Hi,
It stops here:

 * creating and starting Docker containers...                            [ OK ]
 * configuring upstart...                                                [ OK ]
 * reloading ipables rules...                                            [ OK ]
 * no specific steps to execute for Ubuntu at this time...               [ OK ]
 * testing DNS...                                                        [ OK ]
 * testing proxy (OpenSSL)...

and in the log:

`Failure! Retrying in 10..
Failure! Retrying in 20..
Failure! Retrying in 40..
Failure! Retrying in 80..
Failure! Retrying in 160..
You've failed me for the last time! (/usr/bin/timeout 10 /usr/bin/openssl s_client -CApath /etc/ssl/certs -servername netflix.com -connect 191.96.43.84:443 -tls1_2)`

and in my browser I get:
`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/web/wsgiserver/__init__.py", line 1245, in communicate
    req.respond()
  File "/usr/local/lib/python2.7/dist-packages/web/wsgiserver/__init__.py", line 775, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python2.7/dist-packages/web/wsgiserver/__init__.py", line 2018, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/web/httpserver.py", line 306, in __call__
    return self.app(environ, xstart_response)
  File "/usr/local/lib/python2.7/dist-packages/web/httpserver.py", line 274, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 279, in wsgi
    result = self.handle_with_processors()
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 249, in handle_with_processors
    return process(self.processors)
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 246, in process
    raise self.internalerror()
  File "./auth.py", line 258, in internalerror
    return web.internalerror(str(render.__500()))
  File "/usr/local/lib/python2.7/dist-packages/web/template.py", line 1017, in __getattr__
    t = self._template(name)
  File "/usr/local/lib/python2.7/dist-packages/web/template.py", line 1014, in _template
    return self._load_template(name)
  File "/usr/local/lib/python2.7/dist-packages/web/template.py", line 1001, in _load_template
    raise AttributeError, "No template named " + name
AttributeError: No template named __500`

I am using Ubuntu 14.04.5 LTS

I tried to comment out those lines from build.sh - then it finished running the script so I could get my password for the admin, but now any nslookups I do resolve to the proxy's IP. That's not right :D

If I:
`/opt/netflix-proxy# /usr/bin/openssl s_client -CApath /etc/ssl/certs -servername netflix.com -connect 191.96.43.84:443`

Then I get:
```
CONNECTED(00000003)
140199287260832:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:770:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 315 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---
```

I can't ping or ping6 netflix.com - I don't think they respond? The requests just time out.
 
I can lynx netflix.com

**Comment by ab77** [comment]
Do you have IPv6 connectivity on the box before you try to install? (i.e. ping6 google.com)

**Comment by steviedeehook** [comment]
nope,
my eth0 only has ipv4 addresses and
root@steveflix:~# ping6 google.com
connect: Network is unreachable
Kind Regards
Steven

**Comment by ab77** [comment]
You might want to try to CTRL-Z out of the script once it starts on a step that fails and have a look to see what is happening. For example, `docker ps` will tell you if the containers are even running.

You can then try to get inside the `sniproxy` container to see if it has connectivity.

**Comment by steviedeehook** [comment]
Nope, the docker doesn't seem to have connectivity:

root@steveflix:~# docker exec -it sniproxy bash
root@1ad33e757f47:/# ping google.com
ping: unknown host google.com
root@1ad33e757f47:/# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
^C
--- 8.8.8.8 ping statistics ---
164 packets transmitted, 0 received, 100% packet loss, time 164302ms

the docker and the vps seem to have matching up adapters:

In the docker
eth0      Link encap:Ethernet  HWaddr 02:42:ac:11:00:02
          inet addr:172.17.0.2  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:17 errors:0 dropped:0 overruns:0 frame:0
          TX packets:188 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1157 (1.1 KB)  TX bytes:17544 (17.5 KB)

In the VPS
docker0   Link encap:Ethernet  HWaddr 02:42:c3:3b:fe:60
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:190 errors:0 dropped:0 overruns:0 frame:0
          TX packets:19 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:15058 (15.0 KB)  TX bytes:1329 (1.3 KB)
