### ISSUE TITLE
Anybody got it working with sling?

### ISSUE THREAD

**Issue by madd86** [ab77/netflix-proxy#263]
I set it up as instructed.

Edited `zones.override` located on `data/conf`.

Added the following:

    zone "sling.com." {
        type master;
        file "/data/conf/db.override";
    };

Restarted with `docker restart bind`.

Now I see a solid black page on sling.com.

What else can I do here?

**Edit**: Sometimes I get this: `ERR_SSL_VERSION_OR_CIPHER_MISMATCH`

**Edit2**: Upon further examination of the console [I noticed these](https://i.snag.gy/R2u81D.jpg).

Also getting random erros on netflix such as `Unable to send the Widevine license request.` and `net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH`.

So, it seems to be working sometimes randomly.

**Comment by ab77** [comment]
Can you replay the failing WV request using cURL? Do you get the same issue?

**Comment by rpavez** [comment]
Tried this and worked perfectly the website opens normally however the osx app doesn't work...

**Comment by ab77** [comment]
You can try to proxy everything through your `zone.override` file using "." zone. Some of the domains Sling uses, may not be in the `zones.override`.
