### ISSUE TITLE
TCP ports get blocked

### ISSUE THREAD

**Issue by andresmorago** [ab77/netflix-proxy#265]
Hello
I have just installed netflix-proxy on a fresh Amazon EC2 instance. Before installation i had some services running on port 8000 and 1723.
After installation (netflix proxy works ok), TCP ports on 8000 and 1723 got blocked somehow. Is this related with docket being installed and overwriting iptables? how can i have both docker and instance services work altogether?

Thanks

**Comment by ab77** [comment]
Just insert the rules allowing ports 8000 and 1723 before the block all rule (`-A INPUT -j REJECT --reject-with icmp-host-prohibited`).

**Comment by andresmorago** [comment]
thanks!
