### ISSUE TITLE
SSL errors

### ISSUE THREAD

**Issue by andresmorago** [ab77/netflix-proxy#266]
hello
im having the same issue reported on #250. after a fresh install on an ec2 instance, Once i try to access pandora.com i get "SSL_ERROR_NO_CYPHER_OVERLAP". also, when i go to https://EC2-ip, i will get the same error.
I have curl installed

**Comment by ab77** [comment]
From the error, `SSL_ERROR_NO_CYPHER_OVERLAP`, it sounds like the client (browser/curl) and server (pandora) do not have any cryptographic cyphers in common.

**Comment by andresmorago** [comment]
Hello ab77
im still having issues with this. it only happens when i try to load pandora through the sni proxy. i will get this error pretty much all the time. i have to reload the website until it finally opens. this happens on all the devices that make dns requests to my dns server.
i tried to load the site but connected to a us vpn and the error doesnt show at all which makes me think that there is something related to the docker image.
is there anything i could check from my side?

thanks

**Comment by ab77** [comment]
Is IPv6 enabled on the host? Regardless, try putting `ipv4_only` into `sniproxy.conf`. Find it under `data/conf`. See, [this](https://github.com/dlundquist/sniproxy/blob/master/sniproxy.conf) for reference.

**Comment by andresmorago** [comment]
hello ab77
yes! apparently adding the ipv4 switch fixed my issue. i will report back in a few hours

```
resolver {
  nameserver 8.8.8.8
  mode ipv4_only
}
```

**Comment by ab77** [comment]
I'll push a change later this week to force this flag on IPv4 only installs.
