### ISSUE TITLE
DigitalOcean

### ISSUE THREAD

**Issue by jw2804** [ab77/netflix-proxy#268]
Hi there,

First off before doing anything checked Nextflix for US content, nothing. Followed the instruction an setup using Digitalocean, all seemed straight forward enough and went through as per the instructions. set the DNS server IP address as instructed. logged in to Nextflix and hey presto I see US content however when I try playing it I get the ooops yo must be using a proxy message. Any suggestions ?

Thanks

**Comment by ab77** [comment]
What you are seeing is correct. Your setup is working as intended, but Netflix blocked most of the hosting provider IP blocks, so unless yo can find one not yet blocked, you will get that message.
