### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR & ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by brave3d** [ab77/netflix-proxy#271]
I have done DigitalOcean steps and most of the websites are working well including Netflix,
But for other websites I got ERR_SSL_PROTOCOL_ERROR and ERR_CONNECTION_RESET.
For example I got ERR_CONNECTION_RESET from wikipedia.org !!

**Comment by andresmorago** [comment]
check #266

**Comment by brave3d** [comment]
I checked it out. The `sniproxy.conf` file  under `data/conf` already has 
```
resolver {
  nameserver 8.8.8.8
  mode ipv4_only
}
```
And still the same problem!

**Comment by ab77** [comment]
Builds on DO ipv6 and ipv4-only without any issues on DigitalOcean. Not sure hats going on with your build/provider.
