### ISSUE TITLE
issue with bare domain redirection

### ISSUE THREAD

**Issue by yrk2yrk** [ab77/netflix-proxy#273]
Hi,

I am facing an issue where https://www.netflix.com opens and works fine on desktop browser but if you type netflix.com it won't redirect to https://www.netflix.com. 

Also it won't work with Netflix mobile app. Video keeps loading on mobile app but doesn't give proxy error. May be due to the redirection issue. If the redirection issue is fixed then I feel it will work.

Thanks.

**Comment by ab77** [comment]
I don't believe DNS/proxy solutions work reliably on mobile apps anymore.

**Comment by yrk2yrk** [comment]
Oh I see. Anyway, thanks a lot for this amazing script. :)
