### ISSUE TITLE
Can I separate sniproxy from the DNS server

### ISSUE THREAD

**Issue by rami84** [ab77/netflix-proxy#275]
I want to install multiple sniproxies for BBC, Amazon UK and US content but using one DNS IP is this possible with your script?
I tried to install sniproxy on another VPS then changed zones.override and db.override in the DNS server but always get an error opening websites

**Comment by rami84** [comment]
Got it :)
I had to enable sniproxy in /etc/default/sniproxy

**Comment by rami84** [comment]
Hello,
I set up 3 VPSes 1 for Netflix SNIProxy (the one I have that still working with Netflix and it is OpenVZ) the 2nd is for BBC SNIProxy the 3rd is for DNS
Now I want to limit access to both SNIProxies to my DNS server but when I set up firewall and allow access to DNS IP only nothing work as it want clients IPes as well, Is there any way to do this?

**Comment by ab77** [comment]
The end clients need access to port 53/udp on the DNS server and ports 80/443/tcp on the proxies. 

You DNS server is configured to hand out the relevant proxy IP based on the domain name requested.

As long as you do that, everything will work.

**Comment by rami84** [comment]
I have another issue
I'm trying to allow only Netflix in SNIProxy in one of my servers to prevent abuses as it can't be lock to only the DNS server's IP
I used this config for SNIProxy but it look like I'm missing something
<pre>
user daemon
pidfile /var/run/sniproxy.pid

error_log {
    filename /var/log/sniproxy/sniproxy.log
    priority notice
}

listen 80 {
    proto http
    table http_hosts
    access_log {
        filename /var/log/sniproxy/http_access.log
        priority notice
    }
}

listen 443 {
    proto tls
    table https_hosts
    access_log {
        filename /var/log/sniproxy/https_access.log
        priority notice
    }
}

table {
    netflix\.com *
    netflix\.net *
    nflximg\.net *
    nflxvideo\.net *
    nflxso\.net *
    nflxext\.com *
    tvegolf-i\.akamaihd\.net *
    tvenbcsn-i\.akamaihd\.net *
    tveusa-vh\.akamaihd\.net *
    pga-lh\.akamaihd\.net *
    besmenabs-s\.akamaihd\.net *
    besmenaas-s\.akamaihd\.net *
    besmenacs-s\.akamaihd\.net *
    besmenads-s\.akamaihd\.net *
    besmenaes-s\.akamaihd\.net *
    besmenafs-s\.akamaihd\.net *
    maxmind\.com  *

}
<pre/>

**Comment by ab77** [comment]
Please do not do this. Restrict your proxy (and DNS) using iptables firewall to trusted IPs only to prevent abuse. Do not try to do with with ACLs on the proxy/DNS.

**Comment by rami84** [comment]
This VPS only host SNIProxy no DNS on it and I only point Netflix to it and all other sites pointed to other VPSes
Anyway I got it working by editing it to this:
<pre>
user daemon
pidfile /var/run/sniproxy.pid

error_log {
    filename /var/log/sniproxy/sniproxy.log
    priority notice
}

listen 80 {
    proto http
    table http_hosts
    access_log {
        filename /var/log/sniproxy/http_access.log
        priority notice
    }
}

listen 443 {
    proto tls
    table https_hosts
    access_log {
        filename /var/log/sniproxy/https_access.log
        priority notice
    }
}

table http_hosts {
    netflix\.com *
    netflix\.net *
    nflximg\.net *
    nflxvideo\.net *
    nflxso\.net *
    nflxext\.com *

}

table https_hosts {
    netflix\.com *
    netflix\.net *
    nflximg\.net *
    nflxvideo\.net *
    nflxso\.net *
    nflxext\.com *

}


table {
    netflix\.com *
    netflix\.net *
    nflximg\.net *
    nflxvideo\.net *
    nflxso\.net *
    nflxext\.com *

}
<pre/>
