### ISSUE TITLE
I always get "Could not resolve host: ifconfig.co Failure!"

### ISSUE THREAD

**Issue by nxtreaming** [ab77/netflix-proxy#279]
root@vps158284:/relay/dev/netflix# vim docker-sniproxy/functions 
root@vps158284:/relay/dev/netflix# ./build.sh 
Command line is not complete. Try option "help"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    13  100    13    0     0     23      0 --:--:-- --:--:-- --:--:--    23
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: ifconfig.co
Failure! Retrying in 5..
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: ifconfig.co
Failure! Retrying in 10..
^C

but when I try  

curl http://ifconfig.co

I can get my public IP correctly.

**Comment by nxtreaming** [comment]
I find the error is caused by:

function get_ext_ip6addr() {
    local extip6=$(with_backoff curl -6 --connect-timeout ${TIMEOUT} --max-time $((${TIMEOUT}*2)) http://ifconfig.co)
    echo $(echo ${extip6} | awk '{print $1}')
}
why? 

curl -6 http://ifconfig.co 

the command will report error.

**Comment by ab77** [comment]
The script attempts to detect IPv6 connectivity, this is why. the message can be routed to `/dev/null` if required.

**Comment by nxtreaming** [comment]
Must I provide an IP v6 VPS?

**Comment by ab77** [comment]
Not strictly required, but also depends on what you are trying to achieve.

**Comment by nxtreaming** [comment]
How to disable IP v6?

**Comment by thomasbeaumont** [comment]
hi lads, I have the same issue. It seems to come from the fact that ifconfig.co does not respond on v6 anymore. You might want to change the code to ifconfig.io? 

curl -6 https://ifconfig.io/
2001:470:X:XXX::2
curl -6 https://ifconfig.co/
curl: (6) Could not resolve host: ifconfig.co

**Comment by ab77** [comment]
Good point, updated.
