### ISSUE TITLE
get_iface6

### ISSUE THREAD

**Issue by thomasbeaumont** [ab77/netflix-proxy#280]
function get_iface6() {
    local iface6=$(ip -6 route | grep default | awk '{print $5}')
    echo ${iface6} | awk '{print $1}'
}

On my system (Ubuntu 14 AWS) this returns 1024 (metric). It is fixed if you replace $5 by $3

**Comment by ab77** [comment]
Ths is what the output should look like:

```# ip -6 route
2a03:b0c0:1:d0::/64 dev eth0  proto kernel  metric 256
fe80::/64 dev eth0  proto kernel  metric 256
fe80::/64 dev docker0  proto kernel  metric 256
fe80::/64 dev vethd517b4c  proto kernel  metric 256
default via 2a03:b0c0:1:d0::1 dev eth0  metric 1024```

**Comment by thomasbeaumont** [comment]
root@ip-XXX:~# ip -6 route | grep default
default dev he-ipv6  metric 1024

**Comment by thomasbeaumont** [comment]
root@ip-172-31-26-123:~# ip -4 route | grep default
default via 172.31.16.1 dev eth0

**Comment by thomasbeaumont** [comment]
and thank you so much for the work by the way ;)

**Comment by ab77** [comment]
No problem. This is not an ethernet interface (tunnel), so I guess it won't work with the current code.

**Comment by ab77** [comment]
All that tunnel code needs to be removed really, it isn't of much use anymore and is very specific to HE. I would prefer to keep it outside of this project.
