### ISSUE TITLE
bind not finding zones.override and does not start

### ISSUE THREAD

**Issue by rosch100** [ab77/netflix-proxy#281]
With the latest update of bind, it does not start anymore.
`ab77/bind:latest           "/bin/sh -c ./run.sh"    6 hours ago         Restarting (1) 20 seconds ago `
The output of 
`sudo docker logs -f bind`
`drwxr-sr-x   2 root bind 4096 Dec  5 16:18 .

drwxr-xr-x 121 root root 4096 Dec  5 16:20 ..
-rw-r--r--   1 root root 3954 Nov  8 13:00 bind.keys
-rw-r--r--   1 root root  237 Nov  8 13:00 db.0
-rw-r--r--   1 root root  271 Nov  8 13:00 db.127
-rw-r--r--   1 root root  237 Nov  8 13:00 db.255
-rw-r--r--   1 root root  353 Nov  8 13:00 db.empty
-rw-r--r--   1 root root  270 Nov  8 13:00 db.local
-rw-r--r--   1 root root 3171 Nov  8 13:00 db.root
-rw-r--r--   1 root bind  463 Nov  8 13:00 named.conf
-rw-r--r--   1 root bind  490 Nov  8 13:00 named.conf.default-zones
-rw-r--r--   1 root root  268 Dec  5 16:15 named.conf.local
-rw-r--r--   1 root root 2431 Dec  5 16:15 named.conf.logging
-rw-r--r--   1 root root 1214 Dec  5 16:15 named.conf.options
-rw-r--r--   1 root root  130 Dec  5 16:15 named.recursion.conf
-rw-r-----   1 bind bind   77 Dec  5 16:17 rndc.key
-rw-r--r--   1 root root 1317 Nov  8 13:00 zones.rfc1918
/etc/bind/named.conf.local:14: open: /etc/bind/zones.override: file not found`

It used to be working before and zones.override is still in
`/opt/netflix-proxy/data/conf`

How can I configure bind to use the zones.override file again?

Thanks!

**Comment by rami84** [comment]
I agree with you
Something is not right with this update, I did a new install and edited bind files but it does not work

**Comment by ab77** [comment]
The file(s) are now located in `~/netflix-proxy/docker-bind/`.

**Comment by ab77** [comment]
```root@ubuntu-512mb-nyc3-01:~/netflix-proxy# pwd
/root/netflix-proxy
root@ubuntu-512mb-nyc3-01:~/netflix-proxy# head docker-bind/zones.override
zone "netflix.com." {
    type master;
    file "/etc/bind/db.override";
};

zone "netflix.net." {
    type master;
    file "/etc/bind/db.override";
};

root@ubuntu-512mb-nyc3-01:~/netflix-proxy# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS               NAMES
e114d19e6134        andyshinn/dnsmasq   "dnsmasq -k --log-fa…"   About a minute ago   Up 54 seconds                           caching-resolver
ddf84762b3a6        abiosoft/caddy      "/usr/bin/caddy --co…"   About a minute ago   Up 54 seconds                           caddy
25c0a889b6c9        ab77/bind           "/bin/sh -c ./run.sh"    About a minute ago   Up 54 seconds                           bind
0c79112a486a        ab77/sniproxy       "/bin/sh -c ./run.sh"    About a minute ago   Up 54 seconds                           sniproxy
b81695d2d69c        andyshinn/dnsmasq   "dnsmasq -k --port=5…"   About a minute ago   Up 54 seconds                           dnsmasq
root@ubuntu-512mb-nyc3-01:~/netflix-proxy#```

**Comment by ab77** [comment]
In addition, bind is being replaced with dnsmasq. So all the domain config will shortly be defined in `dnsmasq.conf`.

**Comment by rami84** [comment]
I sure know that it is now ~/netflix-proxy/docker-bind/ and I pointed it at my other SNIProxies (for Netflix and BBC) and it wasn't working

**Comment by rosch100** [comment]
OK, I had to remove docker and do a complete reinstall. This solved it.
However, now it seems that you just moved to a new setup as you mentioned a couple of hours ago (dnsmasq beeing now the only docker containers). How do I configure zones.override now?
Thanks!

**Comment by ab77** [comment]
The project has now moved to `dnsmasq` to provide DNS services. BIND was a complete overkill and highly inflexible for this specific purpose.

You need to edit `dnsmasq.conf` followed by `docker restart dnsmasq`.

**Comment by rosch100** [comment]
Thank you! However, I cannot seem to find a dnsmasq.conf in the netflix-proxy directory. Where could I find it?

**Comment by ab77** [comment]
Try re-building on a clean image and check `~/netflix-proxy`

**Comment by rosch100** [comment]
Thanks! It’s working fine again!

Just one more question: I submitted a number of DynDNS names and the proxy resolved their IP-Adresses. However, when I tried to connect from one of these IP-Adresses, I got the admin screen.
Is there a problem with DynDNS? 

Thanks,
Roland

**Comment by ab77** [comment]
Not sure, check iptables, etc.

**Comment by ab77** [comment]
Please create a new issue descibing the problem in detail @drallgood so it can be tracked separately.

It is possible something in the new build affected DDNS, but I've not tested it.
