### ISSUE TITLE
Install script does not honour existing configuration

### ISSUE THREAD

**Issue by Tanami** [ab77/netflix-proxy#286]
The build tool will destroy a server which does not use ssh default ports, or has a web server running on it. This behaviour is also not described anywhere.

**Comment by ab77** [comment]
Yes, the build script makes some assumptions, which work in most cases. There are always going to be edge cases I am afraid.

**Comment by Tanami** [comment]
Well it would be sensible to at least provide a disclaimer in the documentation. There was no warning at all!
