### ISSUE TITLE
Cant't find username and password after running the script

### ISSUE THREAD

**Issue by synetalsolutions** [ab77/netflix-proxy#287]
Hi I followed your instructions but I am not able to find username and password and also not able to access netflix.com, previously it was working very fine.

**Comment by ab77** [comment]
Take a look at the log and see where the script stops.

**Comment by synetalsolutions** [comment]
* unable to resolve and authorise client ip...                                  
* adding IPv4 iptables rules...                                                   [ OK ]
 * adding IPv6 iptables rules...                                                  [ OK ]
 * creating Docker and sniproxy configuration templates...     [ OK ]
 * disabling Docker iptables control...                                       [ OK ]
 * configuring sniproxy and Docker...                                        [ OK ]
 * installing iptables|netfilter-persistent service...                      [ OK ]
 * socialising Docker with iptables-persistent service...             [ OK ]
 * saving iptables rules...                                                            [ OK ]
 * creating dnsmasq.conf from template...                                [ OK ]
 * updating dnsmasq.conf extip=35.194.107.1...                       [ OK ]
 * installing python-pip and docker-compose...                        [ OK ]
 * configuring netflix-proxy-admin backend...                           [ OK ]
 * configuring netflix-proxy-admin reverse-proxy...                   [ OK ]
 * creating cron scripts...                                                             [ OK ]
 * creating and starting Docker containers...                              [ OK ]
 * configuring init system...                                                
  /sbin/init: unrecognized option '--version'
                                                                                                    [ OK ]
 * reloading ipables rules...                                                          [ OK ]
 * testing DNS...                                                                           [ OK ]
 * testing proxy (OpenSSL)...                                                   
**root@server:~/netflix-proxy#**


===================================
**Log Showing this:-** 

/var/log# tail auth.log
Jan  5 17:04:55 smartdns1 sudo: pam_unix(sudo:session): session opened for user                                                                root by rsa-key-20171013(uid=0)
Jan  5 17:04:55 smartdns1 sudo: pam_unix(sudo:session): session closed for user                                                                root
Jan  5 17:04:55 smartdns1 sudo:     root : TTY=pts/0 ; PWD=/root/netflix-proxy ;                                                                USER=root ; COMMAND=/usr/sbin/service netfilter-persistent reload
Jan  5 17:04:55 smartdns1 sudo: pam_unix(sudo:session): session opened for user                                                                root by rsa-key-20171013(uid=0)
Jan  5 17:04:55 smartdns1 sudo: pam_unix(sudo:session): session closed for user                                                                root
Jan  5 17:05:01 smartdns1 CRON[11896]: pam_unix(cron:session): session opened fo                                                               r user root by (uid=0)
Jan  5 17:05:01 smartdns1 sudo:     root : TTY=unknown ; PWD=/root ; USER=root ;                                                                COMMAND=/usr/bin/sqlite3 /root/netflix-proxy/scripts/../auth/db/auth.db SELECT                                                                domain,last_ipaddr FROM DDNS
Jan  5 17:05:01 smartdns1 sudo: pam_unix(sudo:session): session opened for user                                                                root by (uid=0)
Jan  5 17:05:01 smartdns1 sudo: pam_unix(sudo:session): session closed for user                                                                root
Jan  5 17:05:01 smartdns1 CRON[11896]: pam_unix(cron:session): session closed fo                                                               r user root

**Please help me**

**Comment by ab77** [comment]
What do you have in `netflix-proxy.log`?

**Comment by synetalsolutions** [comment]
root@smartdns1:~/netflix-proxy# tail netflix-proxy.log
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1515171930
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---

**Comment by ab77** [comment]
Please use something like pastebin and learn how to format markdown.

**Comment by synetalsolutions** [comment]
Ok what can i do now it is not working..

**Comment by synetalsolutions** [comment]
Don't know what is it

**Comment by damanb1** [comment]
hi am also struggling to login to the portal. 

auth.log
root@SmartDNS:/var/log# tail -f auth.log
Jan  5 17:50:01 SmartDNS CRON[3541]: pam_unix(cron:session): session opened for user root by (uid=0)
Jan  5 17:50:01 SmartDNS sudo:     root : TTY=unknown ; PWD=/root ; USER=root ; COMMAND=/usr/bin/sqlite3 /root/netflix-proxy/scripts/../auth/db/auth.db SELECT domain,last_ipaddr FROM DDNS
Jan  5 17:50:01 SmartDNS sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Jan  5 17:50:01 SmartDNS sudo: pam_unix(sudo:session): session closed for user root
Jan  5 17:50:01 SmartDNS CRON[3541]: pam_unix(cron:session): session closed for user root
Jan  5 17:55:01 SmartDNS CRON[3816]: pam_unix(cron:session): session opened for user root by (uid=0)
Jan  5 17:55:01 SmartDNS sudo:     root : TTY=unknown ; PWD=/root ; USER=root ; COMMAND=/usr/bin/sqlite3 /root/netflix-proxy/scripts/../auth/db/auth.db SELECT domain,last_ipaddr FROM DDNS
Jan  5 17:55:01 SmartDNS sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Jan  5 17:55:01 SmartDNS sudo: pam_unix(sudo:session): session closed for user root
Jan  5 17:55:01 SmartDNS CRON[3816]: pam_unix(cron:session): session closed for user root
Jan  5 18:00:01 SmartDNS CRON[4088]: pam_unix(cron:session): session opened for user root by (uid=0)
Jan  5 18:00:01 SmartDNS sudo:     root : TTY=unknown ; PWD=/root ; USER=root ; COMMAND=/usr/bin/sqlite3 /root/netflix-proxy/scripts/../auth/db/auth.db SELECT domain,last_ipaddr FROM DDNS
Jan  5 18:00:01 SmartDNS sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Jan  5 18:00:01 SmartDNS sudo: pam_unix(sudo:session): session closed for user root
Jan  5 18:00:01 SmartDNS CRON[4088]: pam_unix(cron:session): session closed for user root

**Comment by damanb1** [comment]
or if possible let me know where to add the ip manually.

**Comment by synetalsolutions** [comment]
You can access it with your public ip but ... after adding ip manually you can't access netflix.com

**Comment by damanb1** [comment]
How and where to add my public ip address.  Please let me know the file location as admin portal is not acceptingthe credentials. 
Even creating new user and add them to docker group.

**Comment by ab77** [comment]
@synetalsolutions when running a commercial venture, please see https://github.com/ab77/netflix-proxy#license

@damanb1  try Wiki: https://github.com/ab77/netflix-proxy/wiki/Changing-Admin-Password-For-Auth-Version

Thanks.
