### ISSUE TITLE
Azure with Ubuntu image

### ISSUE THREAD

**Issue by gviddy** [ab77/netflix-proxy#29]
Hey there,

This is a great setup you have created however I am having problems on Azure. From what i can tell everything installed OK and I can issue dig commands on the server OK.

However I just cannot connect to it from my PC or iPad.. My browser just doesnt work when I change the DNS.. So I am thinking would Azure somehow be blocking the DNS and I am missing something i need to turn on/off ?? I'm really stumped as to what to try next to get it going....

Any ideas on what I can test to narrow down the problem would help me a lot... :)

**Comment by ab77** [comment]
Hi there, have you allowed the relevant ports (53/UDP and 80,443/TCP) on your Azure cloud service?

-- ab1

**Comment by gviddy** [comment]
Did that now... and yes its working... Awesome!! Thanks heaps for your setup and quick reply.. :)

For others using Azure, you need to go into the Azure Portal, select your Ubuntu VM and then add the endpoints as ab77 has mentioned in his reply.... :) :)

Again, thank YOU !!!! :)

**Comment by ab77** [comment]
No worries, I was working on another [project](https://github.com/ab77/cloud-harness) to try to automate Azure VM creation and configuration. You may be able to use it to automate all of the steps, including creating of the Azure VMs, firewall rules, etc.

 -- ab1

**Comment by gviddy** [comment]
Oh that project sounds really good... Thanks for being so proactive and helping all us newbies out... haha... :)
