### ISSUE TITLE
No user

### ISSUE THREAD

**Issue by kevin25** [ab77/netflix-proxy#290]
Hello, I had issue after installing it on Ubuntu 16 using Google Clouding.

<img width="1662" alt="screen shot 2018-01-29 at 05 00 07" src="https://user-images.githubusercontent.com/2909982/35504638-90ffd9fa-04b1-11e8-9388-abb7df63ee7f.png">

<img width="689" alt="screen shot 2018-01-29 at 04 59 41" src="https://user-images.githubusercontent.com/2909982/35504600-78e5593a-04b1-11e8-868e-9fa00cb3e6d0.png">

**Comment by kevin25** [comment]
I created a droplet on DO and it works for me. I checked the ip and everything is fine. However, i got this error while playing movie on netflix.

> We're Having Trouble Playing This Title Right Now.

**Comment by ab77** [comment]
DO are long blocked by Netflix, don't bother.

**Comment by kevin25** [comment]
Oh that is news. Any recommendation?

**Comment by ab77** [comment]
There are a few small providers that still work, but it's all trial and error. Also (not-free) is unzoner.com, which came as a result of this project.
