### ISSUE TITLE
how to route all traffic to vps

### ISSUE THREAD

**Issue by andresmorago** [ab77/netflix-proxy#291]
hello ab77

with the older versions of your proxy, i used to change the "zones.override" file on the vps so i could route all the traffic from my router to the vps.
```
zone "." {
	type master;
	file "/data/db.override";
	};
```

since youre now using dnsmasq, could you please provide me some infor about how can i configure your image so everything that receives from my router gets routed properly?
i would like to have only one dnsmasq file, on my home router

thanks so much

**Comment by ab77** [comment]
You'll want to locate `dnsmasq.conf` on the system and adjust it as per:
http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html

**Comment by andresmorago** [comment]
thanks
