### ISSUE TITLE
DNS works but cannot reach websites in proxy-domains 

### ISSUE THREAD

**Issue by nakiru** [ab77/netflix-proxy#295]
Hi, I installed everything on a personal server (Ubuntu machine with broadband access and static public IP). The installation was successful and I can access the admin page and authorize IPs. When using the public IP as DNS server on computers outside the network, I am able to navigate to websites, proving that the router/network setup is ok. However, I am not able to reach websites listed in proxy-domains  (I get a timeout in the browser when trying to reach them). I tried with several websites (if I add them to proxy-domain.txt I cant reach them, if I remove them from the file, I can reach them out). Any idea of what that could be?

**Comment by ab77** [comment]
You could start by testing underlying connectivity to the public IP of the server from the machine in question on ports 80 and 443. You can use plain telnet for that to see if the socket opens. Also try doing a pointed DNS request against the server IP using dig or nslookup.
