### ISSUE TITLE
SSL issues with VPN

### ISSUE THREAD

**Issue by CharlieBashford** [ab77/netflix-proxy#301]
I have setup netflix-proxy on my raspberry pi within my local network based in the USA.

This works well and I can connect my laptop or Apple TV and I see the Netflix packets going to the raspberry pi via Wireshark.

This obviously doesn't give me any benefits as it has the same external IP. I have a L2TP VPN server setup in the UK. I then connected the raspberry pi to the L2TP VPN server and set all traffic to go over the VPN interface.

The laptop or Apple TV seem to work fine for all for all traffic not using SSL. But there are issues with some domains that use SSL.

With netflix.com, ichnaea.netflix.com, api-global.netflix.com and pd.itunes.apple.com, the raspberry pi completes the SSL handshake and send the first application data packet but the only response back is a TCP Window Update, and then the raspberry pi continues to retransmit the same application data packet.

But vod-hls-uk-live.akamaized.net works fine, the raspberry pi completes the SSL handshake, sends the first application data packet and then receives back multiple response packets. I assume this domain is the content delivery network for BBC, as iPlayer works well on the Apple TV.

Also, if I send a curl request to https://www.netflix.com with the DNS set as the raspberry pi, then I get the web page back and I can see the response packets from netflix after the application data packet is sent.

At this point I am a stuck why this setup doesn't work for some domains, or why it works for requests sent via curl but not via a browser (tried Safari, Chrome, Firefox) or Apple TV apps.

**Comment by ab77** [comment]
You might be hitting HTTP/2 coalescing issue, but it's difficult to tell wfrom where I am sitting.

Can you try Netflix in Chrome, with dev. tools enabled and shoeing the `networks` tab. See what happens when you load netflix.com.

**Comment by CharlieBashford** [comment]
Not a lot happens, chrome tries to load the webpage three times (takes about a minute each time to timeout).

<img width="1434" alt="loading netflix" src="https://user-images.githubusercontent.com/1292841/39610927-a6664fda-4f21-11e8-9f66-0a04ba0fdd49.png">

**Comment by CharlieBashford** [comment]
I ran the following curl and openssl commands from my PC (with DNS set to RPi) and on the RPi:

curl --dump-header - https://www.netflix.com
openssl s_client -connect netflix.com:443 -servername www.netflix.com
echo -ne "GET / HTTP/1.1\r\nHost: www.netflix.com\r\n\r\n" | openssl s_client -connect netflix.com:443 -servername www.netflix.com -ign_eof

And they all seemed to respond correctly, with a response being received.

But still https://www.netflix.com won't load in the browser.

Any other suggestions?
