### ISSUE TITLE
Netflix-proxy not working

### ISSUE THREAD

**Issue by Kamayen** [ab77/netflix-proxy#302]
Hello,
Using the script gives back an error E: unable to locate package.
It seems to work when I insert the commands line by line. I get the ok from the test page on all items but don’t receive any credentials for the admin page. Browser can’t even find the admin page.
Any proposed solution?

**Comment by Kamayen** [comment]
Thanks for your reply.
I managed to get everything working right. Followed the the YouTube tutorial, created a tunnel but seems that the ./build.sh -u username -p password is not recognized by the build command.
Does the latest version requires a tunnel broker or doesn’t needed.
Sorry for all my questions.
Cheers,
SAS.

**Comment by ab77** [comment]
All the tunnelling support has been taken out since HE is blocked. That tutorial is out of date.

**Comment by Kamayen** [comment]
Figured that out and tried it without the tunnel. It worked for some services but Netflix detected me. Can’t it be that my server’s IP is blacklisted by Netflix? My server is hosted by OVH in France.

Cheers,
SAS.

**Comment by ab77** [comment]
Yes, your server/provider is already blocked.
