### ISSUE TITLE
netflix not working

### ISSUE THREAD

**Issue by digital-nexus** [ab77/netflix-proxy#305]
Hi,
I have tried netflix-proxy with a server in US and it shows that I'm using an unblocker, I know, nothing new here, but If I use openvpn or squid in the same server I can use netflix without issues... any pointer?

Thanks!

**Comment by ab77** [comment]
Have a look in your browser dev. tools console as your start the stream. You'll see what addresses your browser is resolving various endpoints to.

**Comment by digital-nexus** [comment]
I will test this weekend and provide some screenshots

**Comment by ab77** [comment]
Screenshots aren't particularly useful I am afraid, just compare between a VPN session and proxy to see what the differences are.

**Comment by digital-nexus** [comment]
got it, I will do as suggested and update, thanks @ab77

**Comment by digital-nexus** [comment]
It seems the issue is when trying to open the websocket with https://push.prod.netflix.com/ws
Firefox can’t establish a connection to the server at wss://push.prod.netflix.com/ws.
With the VPN I don't receive that error and streaming is ok

**Comment by ab77** [comment]
WebSockets won't work through a transparent proxy like this. If this is the issue, you can try excluding the hostname from the config.

**Comment by digital-nexus** [comment]
I did what you suggested without luck, also tried forcing all domains with same results.
Prime video works flawlessly.
As mentioned before with squid or openvpn works ok, so that makes me wonder what is the real issue.
I have tested the same script on other server (from my US office) and it works, so the issue is not related to netflix-proxy.
@ab77 Any chance I can contact you privately?

**Comment by ab77** [comment]
@digital-nexus sure, are you on the black.box MailChimp list(s)? If so, just reply to the last email.

**Comment by tcjew** [comment]
same error here since 2 weeks.
