### ISSUE TITLE
The proxy only works for one client

### ISSUE THREAD

**Issue by cciecm** [ab77/netflix-proxy#308]
The netflix-proxy works fine with the first client attached, but cannot unlock netflix for the other nodes.

Is there a client number limit?

**Comment by ab77** [comment]
You need to authorize IP of the other client(s).

**Comment by cciecm** [comment]
I did authorise all clients. I suspect that the authorizationv isn't working properly.
  

  
I have two other proxies, which do not have this problem.
  

  
  

  
  
>

**Comment by ab77** [comment]
There should be an iptables rule for each authorized client. You can check by running `iptables-save` and inspecting the output.

**Comment by cciecm** [comment]
198.13.39.xx/32 is working. I cannot spot any difference...

_# iptables-save | grep /32
-A PREROUTING -s 139.162.105.xx/32 -i eth0 -j ACCEPT
-A PREROUTING -s 198.13.39.xx/32 -i eth0 -j ACCEPT
-A PREROUTING -s 101.180.162.xx/32 -i eth0 -j ACCEPT_

**Comment by ab77** [comment]
It's probably the order of the rules. All of these need to be in the chain before the `-j REDIRECT` entries.

**Comment by cciecm** [comment]
On this proxy (I just have removed 101.180.162.xx/32, but I still can see it in iptables)

> :DOCKER - [0:0]
> -A PREROUTING -s 139.162.105.xx/32 -i eth0 -j ACCEPT
> -A PREROUTING -s 198.13.39.xx/32 -i eth0 -j ACCEPT
> -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
> -A PREROUTING -s 101.180.162.xx/32 -i eth0 -j ACCEPT
> -A PREROUTING -i eth0 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8080
> -A PREROUTING -i eth0 -p tcp -m tcp --dport 443 -j REDIRECT --to-ports 8080
> -A PREROUTING -i eth0 -p udp -m udp --dport 53 -j REDIRECT --to-ports 5353
> -A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
> -A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
> -A POSTROUTING -o eth0 -j MASQUERADE
> -A POSTROUTING -o eth0 -j MASQUERADE
> -A DOCKER -i docker0 -j RETURN
> COMMIT

On another proxy that works for all clients

> -A PREROUTING -s 103.102.5.xx/32 -i eth0 -j ACCEPT
> -A PREROUTING -s 103.102.5.xx/32 -i eth0 -j ACCEPT
> -A PREROUTING -s 38.106.20.xx/32 -i eth0 -j ACCEPT
> -A PREROUTING -s 103.209.101.xx/32 -i eth0 -j ACCEPT
> -A PREROUTING -s 103.209.101.xx/32 -i eth0 -j ACCEPT
> -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
> -A PREROUTING -s 101.180.162.xx/32 -i eth0 -j ACCEPT
> -A PREROUTING -i eth0 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8080
> -A PREROUTING -i eth0 -p tcp -m tcp --dport 443 -j REDIRECT --to-ports 8080
> -A PREROUTING -i eth0 -p udp -m udp --dport 53 -j REDIRECT --to-ports 5353
> -A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
> -A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
> -A POSTROUTING -o eth0 -j MASQUERADE
> -A POSTROUTING -o eth0 -j MASQUERADE
> -A DOCKER -i docker0 -j RETURN
> COMMIT

**Comment by ab77** [comment]
Next step is probably a packet sniffer.

**Comment by cciecm** [comment]
Attached file include tcpdump on both the server and the client

During the packet capture, I opened facebook as well as Netflix on the client.

**Comment by cciecm** [comment]
problem addressed. A silly "copy-and-paste" redirected traffic to another proxy, which didn't allow the 2nd and 3rd clients.
