### ISSUE TITLE
Issue finishing the installer script, stops after installing python-pip

### ISSUE THREAD

**Issue by kysersoze79** [ab77/netflix-proxy#311]
* creating dnsmasq.conf from template...                   [ OK ]
 * updating dnsmasq.conf extip=xxx.xxx.xxx.xxx...        [ OK ]
 * installing python-pip and docker-compose...             

root@ubuntu:~/netflix-proxy#

This is in the log:

Installing collected packages: chardet, certifi, urllib3, idna, requests, dockerpty, PyYAML, backports.ssl-match-hostname, ipaddress, docopt, docker-pycreds, $
  Found existing installation: chardet 2.0.1
Cannot uninstall 'chardet'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a pa$

Earlier, it notes this: 

Collecting chardet<3.1.0,>=3.0.2 (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.19,>=2.6.1->docker-compose)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl

On another server (same provider, but fresh install) it has a similar issue, but complains about urrlib3 instead (probably just the order of things).

Any ideas?

**Comment by ab77** [comment]
Broken image/dependencies probably. Try a different OS image (version?), different provider. Try removing `chardet` and `urrlib3` manually first, the re-run the install.

**Comment by kysersoze79** [comment]
I don't have other providers right now to test with, but it has worked with that provider with this ubuntu 14 image multiple times before. I'll try their debian 8 image.

**Comment by kysersoze79** [comment]
I wasn't sure how to remove chardet and urrlib3, but apparently you just delete them from the python folder:

root@ubuntu:/usr/lib/python2.7/dist-packages# rm -rf char*
root@ubuntu:/usr/lib/python2.7/dist-packages# rm -rf urllib*
root@ubuntu:/usr/lib/python2.7/dist-packages# rm -rf requests*

This allowed the script to finish on both installs (Ubuntu-14.04.1-LTS-64bit)
