### ISSUE TITLE
Proxy Everything option still?

### ISSUE THREAD

**Issue by kysersoze79** [ab77/netflix-proxy#312]
I'd like to proxy everything that gets sent to this proxy server. I don't use this for netflix, but use it for locally  blacked out things like baseball/etc.

I manually add mlb.com to the dnsmasq.conf like so:

address=/mlb.com/64.137.221.236
address=/bamgrid.com/64.137.221.236
address=/mlbstatic.com/64.137.221.236

But I often find myself testing and messing, so I'd just as soon proxy anything sent to this VPS. I'll selectively send requests from home via dnsmasq on my pi-hole install: https://www.reddit.com/r/pihole/comments/5xuu3x/how_can_i_redirectchangeetc_specific_urletc/

Is it still possible to remove the "smart" part of this? Alternatively, can it function as a raw DNS server without needing sniproxy/etc? Not sure I should be making an "open" DNS server in the cloud though.

Sorry for the multiple questions today, but I just happen to be trying to get the streams using the proxy a little more fluid (they buffer more than i'd like). Thanks!!!

**Comment by ab77** [comment]
`address=/#/<ipaddr>` is dnsmasq for "proxy-everything. Check out http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html
