### ISSUE TITLE
Could able to install on DigitalOcean Droplet with docker

### ISSUE THREAD

**Issue by kabindra** [ab77/netflix-proxy#313]
While running build script, following exception was occurred.

* installing python-pip and docker-compose...                           [fail] 
* configuring admin backend...                                          [fail] 
 * testing netflix-proxy admin site...                                   [fail] 
WARNING: IPv6=Disabled

**Comment by ab77** [comment]
logs?

**Comment by kabindra** [comment]
just run the following command and it worked. Probably build was failed because locale was not set for pip.
`$ export LC_ALL=C`
