### ISSUE TITLE
Does the proxy support load balancing?

### ISSUE THREAD

**Issue by cciecm** [ab77/netflix-proxy#314]
i'm wondering if the server could load balance the traffic. I have two servers running netfix-proxy. What will happen when 
Both servers employ the same dnsmasq.conf configurations like:
> address=/netflix.com/server_a
> address=/netflix.com/server_b
> ...

and all clients have DNS pointing to the two servers?

Will the traffic be redirected to server_a only, or 50% of them will go to server_b?

**Comment by ab77** [comment]
No reason why it can't. Have a look at `dnsmasq` docs on how round-robin DNS is implemented and got from there.
