### ISSUE TITLE
BBC Not Working

### ISSUE THREAD

**Issue by jmgibbons1** [ab77/netflix-proxy#317]
I am having issues trying to get BBC to work through a web browser. I was referred to the footnote n5 in which BBC uses HTTP/2 and the four BBC domains need to refer to different IPs. This is my current setup:

1) I setup 2 x VPS and attached an additional IP to each server. (4 IPs in total)
2) I logged into the admin panel and added my IP address.
3) In the dnsmasq.conf file, I added the following lines:
address=/fig.bbc.co.uk/167.XX.XX.80
address=/open.live.bbc.co.uk/167.XX.XX.81
address=/sa.bbc.co.uk/139.XX.XX.80
address=/www.bbc.co.uk/139.XX.XX.81
address=/ *bbc.co.uk/167.XX.XX.80
address=/ *bbc.net.uk/167.XX.XX.80
address=/ *bbc.com/167.XX.XX.80
4) The changes were made on both severs. I then ran the following command docker restart dnsmasq

To confirm ITV and 4OD work fine. I am just facing issues with BBC.

**Comment by lignumaqua** [comment]
BBC iPlayer needs all the CDN networks from the standard netflix-proxy dnsmasq.conf. Do you still have all the akamai, level3, and llnw domains? If you just have the bbc.co.uk domains it won't work.

FWIW - I've not had any issues using a single IP address with an Apple TV. I have a single proxy IP and BBC iPlayer runs perfectly.

**Comment by jmgibbons1** [comment]
Sorry for the delay in coming back. I’ve been traveling. I’ve still got all the domains still in the dnsmasq.conf file. 

I’ve tried most browsers with no luck. I will try an Apple TV tomorrow. Ideally I would like this working through a browser as I’m using a Mac mini as my hptc.

**Comment by jmgibbons1** [comment]
I am using Digital Ocean VPS and have changed the setup to a single IP. BBC is still not working on both Apple TV and browser. I would be very grateful for any help.

**Comment by jmgibbons1** [comment]
I just set this up on Vultr and I can now get BBC working on Apple TV but not through a browser. I've been told this is due to HTTP/2.
