### ISSUE TITLE
Question: Ports

### ISSUE THREAD

**Issue by txt3rob** [ab77/netflix-proxy#32]
Can i use different ports other than 80/433 as i have access to a static ip but it's currently got a web server on that can not be removed.

**Comment by ab77** [comment]
You can, but you'll need something on your home network to re-writing port 80/443 to the substituted ports. Check out [how](http://serverfault.com/questions/247623/iptables-redirect-local-connections-to-remote-system-port) to do this with iptables.

-- ab1
