### ISSUE TITLE
Question:IPV6

### ISSUE THREAD

**Issue by txt3rob** [ab77/netflix-proxy#35]
would it be possible to run the bind DNS server on a local machine say a raspberry pi.
Set certain dns entrys to point to a nginx reverse proxy (could be ran on a raspberry pi)
Set other DNS to points to a SNIproxy running on a VPS that only has IPV6 so the stuff that requires a full blown USA IP is proxies via the VPS that only has IPV6?

http://www.vps.me/ offer a free VPS with 10GB bandwith which would be ideal to have so that only stuff that can not be faked use the VPS.

**Comment by txt3rob** [comment]
the VPS is on a open-vz running an old kernel.
i might test with digital ocean.

**Comment by ab77** [comment]
Well, this is essentially what Dnsmasq does, check out [this](https://github.com/trick77/dockerflix/) project.

-- ab1
