### ISSUE TITLE
zones.override entries

### ISSUE THREAD

**Issue by aburrobb** [ab77/netflix-proxy#37]
Hello,
First: great work. Thanks.
Second:
*Some entries in the zone.override file refers to /etc/bind/db.override which does not exist, should i change these to refer to /data/db.override?
*Some domain in the zone.override file does not end with a period (.), like turner.com and mog.com while others like netflix and hulu ends with a period (.) like netflix.com. and hulu.com., should this be edited?

Thanks.

**Comment by ab77** [comment]
Thanks for picking this up, yes you should fix both at your end, but I'll fix it up now at source.

Cheers!

**Comment by aburrobb** [comment]
Thanks.
I used the link in issue #31 to produce the zones.override in the below link.
Could you have a look at it and confirm its adequate.
https://drive.google.com/file/d/0B4VLjJumv9OOTjF3aWV3cHdNRU0/view?usp=sharing

**Comment by ab77** [comment]
Looks fine, but you should be able to simplify zones.override by just including the top domain name (e.g. blinkbox.com) as opposed to data., www., etc.

If you include the top level, all the rest will inherit it.

-- ab1
