### ISSUE TITLE
Dynamic IPs

### ISSUE THREAD

**Issue by lysin** [ab77/netflix-proxy#38]
Hi, first of all thanks for taking the time and putting this together.

In my country all ISPs have dynamic IPs, will this work without modification?

If not, is there a way I can specify IP blocks so It only works for people in my country?

Thanks

**Comment by ab77** [comment]
Hi there, it will work while your IP remains the same. Once your IP changes, you'll need to add the new one (same procedure as authorising additional IPs in the readme).

If your ISP assigns reverse DNS records to the IPs it issues, you could automate this by using a helper script. Check the wiki as there is a thread there on how to do this.

Finally, I wouldn't recommend adding the whole country IP block as this is tantamount to running an open DNS resolver/proxy.

Cheers!

**Comment by NeSmo1** [comment]
Hi AB,

I cant seem to find this page in the wiki.

Any idea where it has gone? :)

**Comment by ab77** [comment]
Oops, I think it was one in one of the issues from a while back, try https://github.com/ab77/netflix-proxy/issues/9#issuecomment-117580338

**Comment by Amazanta** [comment]
Here is some idea to make dynamic IP working. Your ISP automatically generated symbolic names will be something like: "123-234-567-901.cable.dynamic.surfer.de". The idea is to monitor syslog and try to match the rest of URL "dynamic.surfer.de". In case of match, automatically add it to IP tables. So, when you access DNS for first time with new IP, it will be added automatically. I have made simple pl script. This script needs to be run in background. Let me know if it have any sense.

#/usr/bin/perl
use Socket;
use POSIX qw(strftime);

$datestring = strftime "%a %b %e %H:%M:%S %Y", localtime;

$logfile = "/var/log/syslog";
$namecrit = "cable.dynamic.surfer.de|wifi.dynamic.surfer.de|wireless.dyn.tele2.de|adsl.highway.telekom.ru";

open $logfh, '<', $logfile;
my $logpos;
my $checkon = 0;
my $cm_ip = ""; 
while (1) {
  while (my $line = <$logfh>) {
	if($checkon != 0){
		if($line =~/(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/){
		    print $datestring . ' ' . $1 . "\n";
		    $cm_ip    = "iptables -t nat -I PREROUTING -s $1/32 -i eth0 -j ACCEPT -v";
		    $cm_check = "PREROUTING -s $1/32 -i eth0 -j ACCEPT";
		    $name = gethostbyaddr(inet_aton($1), AF_INET);
		    print $datestring . ' ' . $name . "\n";
		    if($name =~ /$namecrit/ ){
			print $datestring . ' ' . "Match\n";
			iptables($cm_ip, $cm_check);
		    }
		}
	}
	$logpos = tell $logfh;
  }
  sleep 2;
  $checkon = 1;
  seek $logfh, $logpos, 0;
}

sub    iptables {
	my($line, $check_line) = @_;
	print $datestring . ' ' . "Check for: $check_line\n";
	my $found = 0;
	open(my $file,  "<",  "/etc/iptables/rules.v4");
	while (<$file>)  {
		if (/$check_line/) {
		   $found = 1;
		   print $datestring . ' ' . "Exists ...\n";
		}
	}
	if($found != 1){
		print $datestring . ' ' . "Adding ...\n";
		print $datestring . ' ' . "$iptables $line > /dev/null\n" if ($debug);
	       $result = system("$iptables $line > /dev/null && iptables-save > /etc/iptables/rules.v4 || iptables-save > /etc/iptables.rules");
	       if ($result != 0) {
	          print $datestring . ' ' . "($result) iptables $line\n";
	       }
	}
}

**Comment by ab77** [comment]
Also look into `ipset`, `iptables` and `dnsmasq` working together.

**Comment by jeffe13th** [comment]
Did the solution recommended in issue#9 (using a dynamic IP service, updating via cron, etc.) ever work well?  I'm also interested in setting up some sort of dynamic IP update, mainly because my wife can't figure anything out and gets frustrated when things don't "just work" (anyone else have that problem??).  Seems like this would be a good solution.  Also an idea for how to share your server with specific people and make sure that it doesn't get shared or used beyond that.

Would this new Pi script be any easier?  Would this new solution also authorize and update any new IP that hit's DNS, meaning anyone who knows the IP addresses and uses it would be authorized?

**Comment by Amazanta** [comment]
The answer to last question is following: 
There is parameter string in code:
$namecrit = "cable.dynamic.surfer.de | wifi.dynamic.surfer.de|wireless.dyn.tele2.de | adsl.highway.telekom.ru";
It keeps the allowed host names. For every new record in syslog, the requester IP address get resolved to host name and examined against allowed names. Main assumption is, variable IPs coming from the same provider will be resolved to uniform host name with the same ending. So, theoretically, people from the same provider who knows your DNS IP will be able to use it as well. Positive part - if you know your friends provider (like t-mobile), you can allow him (and all other users of t-mobile, if they clever to get your hidden DNS IP) to use your DNS. In some cases you can make it even more strict - just look at your random IP address over time. In my case the only part is changing last two digits. So you can set matching like this: "123_456_56_*.cable.dynamic.surfer.de". Hope this helps.
