### ISSUE TITLE
iPlayer Setup

### ISSUE THREAD

**Issue by dmcaodha** [ab77/netflix-proxy#39]
Hi there, 

In your other iPlayer repo, you advise people to use the netflix-proxy repo instead. How is this set up to access iplayer? Is it a case of just adding bbc.co.uk to the zones.override file?

Or will the iplayer-proxy repo still give good results?

Thanks

**Comment by ab77** [comment]
Hi there, please use the netflix-proxy repository and add bbc.co.uk block to zones.override. Just copy the Netflix definition as change the domain name, lastly run "docker restart bind". That should be all..

Cheers!

**Comment by dmcaodha** [comment]
Thanks for the reply. It isn't working for me though. I replaced the zones.override file in this repo with the one in the iplayer repo and ran the build script. I am using a D.O. droplet. When I go to bbc.co.uk in the browser, I am not redirected to the .com site, so it works up to that point. However, when I go to view iPlayer content I get the following message - "This content doesn't seem to be working"

Perhaps they have some way of detecting that the traffic is coming through D.O.

**Comment by ab77** [comment]
It is possible.. try with this directive in zones.override:

zone "." {
    type master;
    file "/data/db.override";
};

This will confirm if BBC are using additional geo blocking (possibly on the
CDN endpoints).

If that works, you'll need to work out what domains to proxy in addition to
bbc.co.uk.

-- ab1

**Comment by ab77** [comment]
P.S. I've added the BBC domains to the master branch now, so iPlayer should be supported out of the box, unless BBC got crafty with their geo-blocking tech.

-- ab1

**Comment by alexali2015** [comment]
BBC iPlayer doesn't work :(

Seems like you can hit 'Play' but it then results in the errors above: 
This content doesn't seem to be working

Any ideas?
