### ISSUE TITLE
HD Streaming

### ISSUE THREAD

**Issue by NeSmo1** [ab77/netflix-proxy#40]
I know this isn't really a issue but is there a way i can get it HD Streaming? 

It seems from where i am (Australia) I can stream normal netflix in HD but am unable to stream it in HD with the proxy enabled but the video buffers quite fast.

**Comment by ab77** [comment]
See if you can get some stats, from the diagnostics screens (PC/MAC):
http://www.tech-recipes.com/rx/7854/netflix-movie-player-use-keyboard-shortcuts-when-viewing-watch-instantly-videos/

Also, if the stats don't contain media URLs, see if you can capture these
via Wireshark, etc.

The proxy shouldn't be proxying media delivery URLs, unless Netflix changed
the media domain back to *.netflix.com..

-- ab1

**Comment by ab77** [comment]
On a related note, how did you get iPlayer to work at all? What domains did you proxy besides bbc.co.uk?
