### ISSUE TITLE
Using the DNS on router often disconnects the internet 

### ISSUE THREAD

**Issue by meshungina** [ab77/netflix-proxy#41]
First of all, thanks so much for this! Once set up without any problems it will replace my Unlocator  service and allow me to use with several IP's. Was wondering if too many browser requests of DNS might knock the thing offline for a while. A router restart seemed to fix it but perhaps I have a setting wrong somewhere. Do you know if there is a way on a router to only forward certain site requests to the proxy? (without dd-wrt).  I realize the zones.override does not have rules to forward other sites and it probably just ignores those requests but perhaps it's too many of those that's whats knocking the net offline. Thanks again for this wonderful piece of work I'm sure it will improve with time and I'll figure it out.

**Comment by ab77** [comment]
Hi there, so from reading between the lines, you configured your router to hand out your custom DNS server and it eventually Stops replying to DNS queries.

In the ideal situation, you would want a local DNS proxy (e.g. Raspberry Pi) running dnsmasq, where you can selectively send DNS requests for certain domains either to your local ISP's DNS or your custom one.

Or you could just try setting your custom DNS on a single device (the one you use to watch stuff) and see if it works continuously..

The project configures bind in such a way, that it passes all other DNS requests to Google.

Hope that helps.

-- ab1

**Comment by meshungina** [comment]
just couldn't figure why too many requests would do that. I'll be setting a
router to ddwrt it turns out i have a compatible model. or how might i use
the pi to do the same? perhaps that would be better. I've got one running
rasbian for vpn might that be used as a dns forward from external networks
as well?

**Comment by ab77** [comment]
DD-WRT on the router is the way I would go first..

**Comment by ab77** [comment]
If you are on OSX, please see the notes in the readme.

**Comment by meshungina** [comment]
Have not had any problems since so I assume my internet was just having problems around testing time.
