### ISSUE TITLE
Auto IP Tables

### ISSUE THREAD

**Issue by NeSmo1** [ab77/netflix-proxy#43]
Hi AB,

How would i make like a webpage or something that i could visit which then after clicking a button or visiting the page would log my IP into the iptables with a expiry date.

Thanks in advance,

Cheers.

**Comment by ab77** [comment]
Presumably you want something which allows you to authorise a new IP address after your ISP assigns a new one via DHCP using a web interface.

If that's the case, maybe have a search around for iptables web front-ends and we if they do what you need..

Alternatively you'll have to probably code something up yourself.

-- ab1

**Comment by NeSmo1** [comment]
Hmm i've had a look around but i cant really find anything. All i want is a simple (even blank) page that i can visit that auths my ip and my friends' ips! :)

**Comment by ab77** [comment]
If I was to do it, I would build a simple app in Python, using http://webpy.org framework.

When I get some time, I'll write something and include it in the project.

-- ab1

**Comment by ab77** [comment]
Done.
