### ISSUE TITLE
Docker Bind not starting properly at boot

### ISSUE THREAD

**Issue by jfdoucet** [ab77/netflix-proxy#44]
The issue appeared today for some unknown reason. When I reboot the DigitalOcean droplet, the docker bind does not start properly, does not listen on port 53. In order to make it work after a reboot, I need to either run "docker restart bind" or "service docker restart" which is quite annoying given the fact that I don't want human intervention every time the droplet gets rebooted.  Is this a known issue and do you have a clean fix for it ?

**Comment by ab77** [comment]
Hi there, not as far as I am aware. I just tried and wasn't able to replicate your issue, at least not in the NYC1 DC. I deployed a fresh Droplet with Docker, rebooted and everything came back fine.

Is this happening in a specific DC and do you have the output of the build log to see if anything has gone wrong? In theory, it could be some kind of timing issue, but I've not seen it before..

 -- ab1

**Comment by jfdoucet** [comment]
Hi,

My droplet is at NYC3. As for the build log, where do I find it ?

- JF

**Comment by ab77** [comment]
The stuff that happens after you run build.sh..

**Comment by jfdoucet** [comment]
I tried to rebuild it however since it was already installed it did not do much. Here's the output:

clientip=X.X.X.X ipaddr=X.X.X.X X.X.X.X extip=X.X.X.X
WARNING: enabling DNS recursion...
		allow-recursion { trusted; };
		recursion yes;
		additional-from-auth yes;
		additional-from-cache yes;
/opt/netflix-proxy /opt/netflix-proxy
iptables: Chain already exists.

Now bind does not want to listen at all. After a reboot,  a 'docker restart bind' or a 'service docker restart'..

Any way I can completely remove the components to run a fresh build ?

-- JF

**Comment by jfdoucet** [comment]
More information: I rolled back to my old folder and now I am back to the old problem where after a reboot I have to restart docker. Before when I was running "netstat -ln" I use to see the ports 53 for ipv4 but now it only shows under ipv6 and only the UDP port 53 is listening.

udp6       0      0 :::53                   :::*                             

I am quite puzzled..

- JF

**Comment by jfdoucet** [comment]
With the new information, I can tell that when I reboot the droplet I do see it listening on UDP6 53 but I can't query it. As soon as I restart bind using 'docker restart bind' then I am able to query it again. What is puzzling me the most is that I use to see it listen on TCP4 and UDP4 2 days ago.. Anyway, if you have no clue, I will just make the system run 'docker restart bind' at the end of the boot sequence but I was hoping for a cleaner fix.

-- JF

**Comment by ab77** [comment]
The build.sh script, as it currently stands, is not idempotent, so it will
fail on the second execution. For repeat runs, my approach was always to
destroy the Droplet and deploy a new one.

In any case, I've tried multiple times to replicate your issue and I can't
do it. I deployed in NYC3 with or without IPv6 and after rebooting,
everything comes back OK.

Perhaps try deleting/destroying your current Droplet and deploy a new one.
Let me know how that goes..

-- ab1

**Comment by ab77** [comment]
Did you get it working after a rebuild?

**Comment by jfdoucet** [comment]
Sorry for the delay. I just ran a build on a new Droplet and I don't have the problem at boot anymore however something else strange happened, it took 2 reboots for the FRIENDS iptables chain to appear so before the second reboot, the DNS was open to the outside world.

Here is my build log: http://pastebin.com/TpEMt7YD

**Comment by belodedenko** [comment]
OK, I think I know what the issue is. You are probably clicking that "IPv6" box during deployment and I haven't provided for IPv6 rules to be setup by the build script (it only handles IPv4). You have a dual-stack setup, which means you are intermittently switching between IPv4 (locked-down) and IPv6 (unsecured).

To fix this is trivial, so I'll see if I can do it soonish. In the mean time, redeploy without IPv6 or add the missing rules to the IPv6 chain manually.

-- ab1

**Comment by ab77** [comment]
OK, iptables-persistent service now fails to load the saved rules on boot for some reason. It was working before, but someone upstream must have phat-fingered something.

Anyway, I put a work around in place to load the rules on eth0 start-up, so it works now.

To fix on your droplets without rebuilding, run:

    printf "\tpre-up service iptables-persistent reload\n" >> /etc/network/interfaces
    service iptables-persistent reload

Please let me know how that goes..

-- ab1

**Comment by jfdoucet** [comment]
The issue with iptables was on the test Droplet I started so I can attempt to reproduce the bind start issue for you however I did not keep that Droplet and on my actual Droplet which is in production with added services and stuff, I simply added a restart command in rc.local for now. I will be running a fresh new build in a few weeks and will let you know if I face any issues. I guess you can close this issue.

-- JF

**Comment by ab77** [comment]
Cheers!
