### ISSUE TITLE
can't ssh to my server after reboot

### ISSUE THREAD

**Issue by jhihguan** [ab77/netflix-proxy#48]
I create a droplet from digitalocean
setup a user account and add some iptables filter
and than install the scripit on droplet
Now I can ssh to my server

But
after shutdown my server and power on again
I can no longer ssh to myserver
Did I ban by the ipfiler?
or what should I do after reboot

**Comment by ab77** [comment]
Hi, the build script sets up the iptables rules for you automatically. If you are adding rules before running the script, then that's most likely to break it.

Try building a new droplet and follow the instructions..

**Comment by jhihguan** [comment]
Thanks! it works fine now!
Besides, if I create a new droplet and add a user, than add iptables filter (tmp/v4) by linode
https://www.linode.com/docs/security/securing-your-server
than run ./build.sh, it will say
```iptables: Chain already exists.```
and nothing installed
but if a run the script first and than add the filter, it will be fine

But anyway thanks for your fix!
