### ISSUE TITLE
Reboot

### ISSUE THREAD

**Issue by lesnox** [ab77/netflix-proxy#51]
Hello, 

that was a soo cool package !!! i have install on OVH VPS. When i finished the serveur said the system be restart. When i reboot my serveur it's impossible to connected it's say : Destination Host Unreachable

have you an idea about that ?? 

Best Regards 

lesnox

My serveur is VPS OVH in France with ubuntu serveur 14.04

Ps : Sorry for my bad english ;)

**Comment by ab77** [comment]
Does it work before you reboot the machine?

**Comment by lesnox** [comment]
Yes

**Comment by ab77** [comment]
Can you please post the contents of your /etc/network/interfaces file..

**Comment by lesnox** [comment]
this is the file :

 This file describes the network interfaces available on your system

# and how to activate them. For more information, see interfaces(5).


# The loopback network interface

auto lo

iface lo inet loopback


# Source interfaces

# Please check /etc/network/interfaces.d before changing this file

# as interfaces may have been defined in /etc/network/interfaces.d

# NOTE: the primary ethernet device is defined in

# /etc/network/interfaces.d/eth0

# See LP: #1262951

source /etc/network/interfaces.d/*.cfg


        pre-up service iptables-persistent reload

2016-01-05 9:57 GMT+01:00 Anton Belodedenko <notifications@github.com>:

> Can you please post the contents of your /etc/network/interfaces file..
>
> On 4 January 2016 at 21:57, lesnox <notifications@github.com> wrote:
>
> > Yes
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ab77/netflix-proxy/issues/51#issuecomment-168823625
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ab77/netflix-proxy/issues/51#issuecomment-168938091>.
>



-- 
-Boisseau Julien-
Lerchesflurweg 18
66119 SAARBRUCKEN
(Allemagne)

Portable : 00 33 6 98 16 27 38

Ce message et les fichiers qui y sont éventuellement joints sont
exclusivement réservés au destinataire. Il peut contenir des données ou des
informations confidentielles ou protégées par la loi. Si ce message vous
est parvenu par erreur, nous vous prions de l’effacer sans effectuer de
reproduction et d’informer l’expéditeur. Nous vous remercions de votre
collaboration.

This message and any attached files are for the sole use of the recipient
named above. It may contain confidential or legally protected data or
information. If you have received this message in error, please delete it
without making any copies whats oever and notify the sender. Thank you for
your assistance.

**Comment by ab77** [comment]
OK, you need to move the last line 'pre-up service iptables-persistent
reload' into /etc/network/interfaces.d/eth0 (at the bottom)

That should fix it. I'll look into updating the script so it handles both
cases where the interface definition is in the root file or in
interfaces.d/..

**Comment by lesnox** [comment]
yes it's works fine ;)

thx a lots !!

lesnox

2016-01-05 10:15 GMT+01:00 Anton Belodedenko <notifications@github.com>:

> OK, you need to move the last line 'pre-up service iptables-persistent
> reload' into /etc/network/interfaces.d/eth0 (at the bottom)
>
> That should fix it. I'll look into updating the script so it handles both
> cases where the interface definition is in the root file or in
> interfaces.d/..
>
> On 5 January 2016 at 09:10, lesnox <notifications@github.com> wrote:
>
> > this is the file :
> >
> > This file describes the network interfaces available on your system
> >
> > # and how to activate them. For more information, see interfaces(5).
> >
> >
> > # The loopback network interface
> >
> > auto lo
> >
> > iface lo inet loopback
> >
> >
> > # Source interfaces
> >
> > # Please check /etc/network/interfaces.d before changing this file
> >
> > # as interfaces may have been defined in /etc/network/interfaces.d
> >
> > # NOTE: the primary ethernet device is defined in
> >
> > # /etc/network/interfaces.d/eth0
> >
> > # See LP: #1262951
> >
> > source /etc/network/interfaces.d/*.cfg
> >
> >
> > pre-up service iptables-persistent reload
> >
> > 2016-01-05 9:57 GMT+01:00 Anton Belodedenko <notifications@github.com>:
> >
> > > Can you please post the contents of your /etc/network/interfaces file..
> > >
> > > On 4 January 2016 at 21:57, lesnox <notifications@github.com> wrote:
> > >
> > > > Yes
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > https://github.com/ab77/netflix-proxy/issues/51#issuecomment-168823625
> > > >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/ab77/netflix-proxy/issues/51#issuecomment-168938091
> > >.
> > >
> >
> >
> >
> > --
> > -Boisseau Julien-
> > Lerchesflurweg 18
> > 66119 SAARBRUCKEN
> > (Allemagne)
> >
> > Portable : 00 33 6 98 16 27 38
> >
> > Ce message et les fichiers qui y sont éventuellement joints sont
> > exclusivement réservés au destinataire. Il peut contenir des données ou
> des
> > informations confidentielles ou protégées par la loi. Si ce message vous
> > est parvenu par erreur, nous vous prions de l’effacer sans effectuer de
> > reproduction et d’informer l’expéditeur. Nous vous remercions de votre
> > collaboration.
> >
> > This message and any attached files are for the sole use of the recipient
> > named above. It may contain confidential or legally protected data or
> > information. If you have received this message in error, please delete it
> > without making any copies whats oever and notify the sender. Thank you
> for
> > your assistance.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ab77/netflix-proxy/issues/51#issuecomment-168940350
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ab77/netflix-proxy/issues/51#issuecomment-168941116>.
>



-- 
-Boisseau Julien-
Lerchesflurweg 18
66119 SAARBRUCKEN
(Allemagne)

Portable : 00 33 6 98 16 27 38

Ce message et les fichiers qui y sont éventuellement joints sont
exclusivement réservés au destinataire. Il peut contenir des données ou des
informations confidentielles ou protégées par la loi. Si ce message vous
est parvenu par erreur, nous vous prions de l’effacer sans effectuer de
reproduction et d’informer l’expéditeur. Nous vous remercions de votre
collaboration.

This message and any attached files are for the sole use of the recipient
named above. It may contain confidential or legally protected data or
information. If you have received this message in error, please delete it
without making any copies whats oever and notify the sender. Thank you for
your assistance.
