### ISSUE TITLE
dns python

### ISSUE THREAD

**Issue by lesnox** [ab77/netflix-proxy#52]
i have this message when i make pip : 

root@vps232903:~# pip install dsnpython
Downloading/unpacking dsnpython
  Could not find any downloads that satisfy the requirement dsnpython
Cleaning up...
No distributions at all found for dsnpython
Storing debug log for failure in /root/.pip/pip.log

did you know why ?? 

Best Regards 

Lesnox

**Comment by ab77** [comment]
Hi, you probably want "dnspython" rather than "dsnpython", but I am not quite sure what you are doing..

**Comment by lesnox** [comment]
Oh sport for that bug :/
