### ISSUE TITLE
Doesn't work from Singapore

### ISSUE THREAD

**Issue by newsera** [ab77/netflix-proxy#54]
Doesn't work from Singapore since Netflix officially launched Netflix in Singapore. 
Fails when trying to load content

**Comment by ab77** [comment]
Hi, can you please let me know which hosting provider you are hosting your
DNS/proxy server with (i.e. AWS, Azure, DigitalOcean, etc.) and which
region?

**Comment by newsera** [comment]
DigitalOcean - SFO1

**Comment by newsera** [comment]
Let me know if u need any additional information from my side.. I will try with another VPS provider tomorrow and shall update u to see if it makes a difference.

**Comment by ab77** [comment]
I've just deployed into Digital Ocean SFO1, repointed DNS and was able to
start playback (Narcos).

I am not sure if they've implemented some sort of title specific blocking,
but on face value it appears to work.

The Droplet IP was in the 162.243.149.x range.

-- ab1

**Comment by newsera** [comment]
Narcos is available in Singapore. Try House of Cards or Sherlock. Yes there are some restrictions

**Comment by newsera** [comment]
Ideally the titles shouldn't be restricted right

**Comment by ab77** [comment]
OK, I've just did a few tests from UK to US and although I can't replicate the exact scenario you are in (I can't place myself in Singapore), it seems to work still.

I turned off IPv6, deployed a server into SFO, configured the stack and changed my local DNS.

I tested using `101 Dalmatians`, which is only available in the US catalogue and with DNS pointing at the SFO IP, the title was available. Returning to my UK DNS, made the title disappear.

There is a delay between the catalogue changes, so sometimes you have to wait before the changes "propagate".

Let me know how it goes..

-- ab1

**Comment by newsera** [comment]
Tried another VPS Provider and worked well. Thanks for your efforts.
