### ISSUE TITLE
Scaleway

### ISSUE THREAD

**Issue by lesnox** [ab77/netflix-proxy#55]
Hello,

I want to know if this program work in arm processor ? I have see some server on scalway : https://www.scaleway.com/

But I don't know if it's work ;) 

Best regard. 
Lesnox

**Comment by ab77** [comment]
If you can run Docker on it, then yes, it will work.

-- ab1

**Comment by lesnox** [comment]
I will test the next month ;)

**Comment by meetshawn** [comment]
Isn't Scaleway out of a French data center?

**Comment by lesnox** [comment]
Yes it's on Paris :) 

Envoyé de mon iPhone
