### ISSUE TITLE
Netflix blocking Digital Ocean? 

### ISSUE THREAD

**Issue by amityweb** [ab77/netflix-proxy#59]
I followed this method and even tunnelled via SSH into the server and used Falcon Proxy for the browser to connect through the SSL tunnel. Whatismyip even shows my IP address as the US server. But Netflix is still blocking it :(. I wondered if Netflix is just blocking Digital Ocean, or a range of IPs from them.

**Comment by xportz** [comment]
Seems blocked in NY and SF regions.

**Comment by newsera** [comment]
Last time I tried in DO - SFO, it was blocked..

**Comment by newsera** [comment]
You can try OVH. Costs $3.49/month It's not blocked yet.

**Comment by ab77** [comment]
Load Netflix in Chrome and have a look in Chrome Developer Tools (network) tab to make sure the correct IP is being resolved.

I tried a few times last week and had no issues accessing US catalogue via SFO.

Note, Chrome will use IPv6 if available, so turn it off if this is happening..

-- ab1

**Comment by amityweb** [comment]
Think I will try OVH or a lesser known server provider.

**Comment by xportz** [comment]
On OVH I'm only seeing a Canadian or a European hosting option. What am I missing?

**Comment by amityweb** [comment]
Oh shoot, I signed up for North America/Beauharnois and just assumed that was US. So guess this wont work then? Cant see a US server on OVH either.

**Comment by lesnox** [comment]
il suffit de prendre une ip localisé au us sur le vps ;)

2016-01-24 18:35 GMT+01:00 Laurence Cope <notifications@github.com>:

> Oh shoot, I signed up for North America/Beauharnois and just assumed that
> was US. So guess this wont work then? Cant see a US server on OVH either.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ab77/netflix-proxy/issues/59#issuecomment-174322568>.
>



-- 
-Boisseau Julien-
Lerchesflurweg 18
66119 SAARBRUCKEN
(Allemagne)

Portable : 00 33 6 98 16 27 38

Ce message et les fichiers qui y sont éventuellement joints sont
exclusivement réservés au destinataire. Il peut contenir des données ou des
informations confidentielles ou protégées par la loi. Si ce message vous
est parvenu par erreur, nous vous prions de l’effacer sans effectuer de
reproduction et d’informer l’expéditeur. Nous vous remercions de votre
collaboration.

This message and any attached files are for the sole use of the recipient
named above. It may contain confidential or legally protected data or
information. If you have received this message in error, please delete it
without making any copies whats oever and notify the sender. Thank you for
your assistance.

**Comment by sjswerdloff** [comment]
Netflix and HBO were OK today for me but not SHO...
created my droplet today (2016-01-24 ~17:00 PST)

**Comment by lesnox** [comment]
you can take : http://oneprovider.com/

**Comment by maxima120** [comment]
> I tried a few times last week and had no issues accessing US catalogue via SFO.
Netflix started to block actively (at least in my region) 4 days ago only so you wouldnt see it.

I just installed your docker on DO and I am blocked. I am pretty sure I use my new docker IP for DNS. So it seems DO is blocked..

**Comment by maxima120** [comment]
whats SFO ?

**Comment by ab77** [comment]
Airport code for San Fransisco, also DO DC in or near it.

**Comment by idontdomath** [comment]
seems blocked at sfo1 and nyc2, nyc3 at least from some attempts here.

**Comment by ab77** [comment]
Seems to be working for me. Are you trying to do this from a device with a working IPv6 stack by any chance?

**Comment by newsera** [comment]
I noticed something. Not all accounts are enabled with "Proxy/Unblocker" Detection. VPS that works for X account might not work for Y account.

**Comment by ab77** [comment]
How did you come to this conclusion? What steps have you taken to verify
this behaviour?

Please share...

**Comment by lesnox** [comment]
have you test : http://oneprovider.com/ ???

2016-01-31 10:06 GMT+01:00 Anton Belodedenko <notifications@github.com>:

> How did you come to this conclusion? What steps have you taken to verify
> this behaviour?
>
> Please share...
>
> On 31 January 2016 at 08:44, newsera <notifications@github.com> wrote:
>
> > I noticed something. Not all accounts are enabled with "Proxy/Unblocker"
> > Detection. VPS that works for X account might not work for Y account.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ab77/netflix-proxy/issues/59#issuecomment-177435316
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ab77/netflix-proxy/issues/59#issuecomment-177445412>.
>



-- 
-Boisseau Julien-
Lerchesflurweg 18
66119 SAARBRUCKEN
(Allemagne)

Portable : 00 33 6 98 16 27 38

Ce message et les fichiers qui y sont éventuellement joints sont
exclusivement réservés au destinataire. Il peut contenir des données ou des
informations confidentielles ou protégées par la loi. Si ce message vous
est parvenu par erreur, nous vous prions de l’effacer sans effectuer de
reproduction et d’informer l’expéditeur. Nous vous remercions de votre
collaboration.

This message and any attached files are for the sole use of the recipient
named above. It may contain confidential or legally protected data or
information. If you have received this message in error, please delete it
without making any copies whats oever and notify the sender. Thank you for
your assistance.

**Comment by idontdomath** [comment]
No ipv6 stack here, but reviewed all the stack just to make sure that ipv6 was disabled but still no luck.
I was able to test the with an account that hadn't being used thru a proxy before (using sfo1) and worked, so it seems that my newsera comment could be right.

**Comment by ab77** [comment]
Interesting. Are you able to share with me privately your Netflix account details (the blocked one) so I can do some testing and verify this? You can change the password, etc. afterwards..

**Comment by newsera** [comment]
ab77@ I also believe all the newly created accounts are enabled with this "Proxy/Unblocker" sensor. So no use creating new accounts irrespective of the source IP Address. But I believe it is just a matter of time for Netflix to enable this "Proxy/Unblocker" sensor to old accounts. So the real challenge is finding VPS providers which would work on "these" accounts with "Proxy/Unblocker" sensor enabled. And I believe OVH is one of the provider.

**Comment by newsera** [comment]
ab77@ just sign up for a new trial and you will get an account with this "Proxy/Unblocker" sensor enabled.

**Comment by maxima120** [comment]
before you invented the whole new conspiracy story and furnish it with nice details lie proxy unblocker sensor.. just try may be a simpler explanation - the blocking algorithm works in a nonobvious way, perhaps across blocks of IPs. so one of your accounts got caught and the other doesnt.

my netflix account is years old. and i got caught 7 days after the news started about the blocking..

why dont you just find quietly a hosting provider which is not caught yet and dont tell anyone. go into your lounge room and watch it..

the more you spin this story in the public internet, the faster they will catchup with you.

**Comment by ab77** [comment]
@maxima120: spot on :)

**Comment by newsera** [comment]
maxima120@ atleast i am trying something here rather than just telling its not working. there cannot be any algorithm made to work in a nonobvious way. there should be some logic behind it. my claim is, NOT all accounts are enabled with blocking algorithm. If your account is part of this blocking algorithm and you managed to find a VPS to work for you, it is a win (for now) rather than your legacy account getting blocked all of a sudden one day. But again, this blocking algorithm might be constant updated with the list of IP ranges to be blocked, but not so aggressively. Enjoy while it lasts...

And I have already shared the VPS provider name above. Netflix can't go on blocking IP ranges of every VPS provider out there. It will definitely spoil their business

ab77@ remember, the soul of this script is an VPS that works!

**Comment by maxima120** [comment]
sure.. sure (slowly recedes back to the door).. take it easy mate (running away)..
http://www.adultswim.com/videos/family-guy/run-away/

**Comment by ab77** [comment]
Feel free to re-build and test again, it is working again (at least for now).

-- ab1
