### ISSUE TITLE
iptables v1.4.21: host/network `' not found

### ISSUE THREAD

**Issue by alijabbar** [ab77/netflix-proxy#60]
I get this error when I tried to install it in Ubuntu 14 

root@ali-virtual-machine:/opt/netflix-proxy# ./build.sh
clientip= ipaddr=192.168.18.130 extip=51.36.130.41 -r=1 -b=0 -i=0 -d=0
WARNING: enabling DNS recursion...
                allow-recursion { trusted; };
                recursion yes;
                additional-from-auth yes;
                additional-from-cache yes;
/opt/netflix-proxy /opt/netflix-proxy
iptables v1.4.21: host/network `' not found
Try `iptables -h' or 'iptables --help' for more information.
root@ali-virtual-machine:/opt/netflix-proxy#

**Comment by ab77** [comment]
Hi there, the problem is that "clientip" is not being set for some reason
through your SSH session.

Try specifying your home public IP manually, using "./build.sh -c 1.2.3.4"

Where 1.2.3.4 is your public home IP address.

-- ab1
