### ISSUE TITLE
Hulu not working - Posible solution

### ISSUE THREAD

**Issue by tomcontr** [ab77/netflix-proxy#61]
Hi, 
Since hulu has blocked almost every VPS. Is it posible to hire any SmartDNS provider that works, and use that service on my own server to redirect all traffic through that SmartDNS?

This will allow me to use 2 different IP address at the same time, to use one SmartDNS provider with the same account. I understand that clearly is not what they want, but I was just wondering it from a technical point of view.
Clearly they do something like that with their servers because I don't think that they need to change their smart dns server ip every time they get blocked. I think the have on server that internally redirects all traffic to other non blocked ip, so when those get blocked they just go for new ones and customers don't need to change the DNS every time.

Is that the way it works? Can it be replicated with this this schema? 
My Device -> SmartDNS (DigitalOcean)  -> SmartDNS(Any SmartDNS provider that is working with Hulu) ? 

Best Regards,

**Comment by ab77** [comment]
Hi there, yes you could define a DNS zone so it returns any IP address. So just define a separate zone for hulu.com and have it return the IP of your other provider.

-- ab1
