### ISSUE TITLE
DNS bind9

### ISSUE THREAD

**Issue by CipAppix** [ab77/netflix-proxy#63]
Hi there,
Could you let me know how to do this with bind9 in ubuntu?

Regards

**Comment by lbdroid** [comment]
I have to assume that you mean using bind instead of dnsmasq on the client side, since the server side already runs bind in the docker container.

To do this with bind would be slightly more complicated than using dnsmasq. You would have to set up zone files for all of the domains that you are proxying. In the zone file for the proxied domains, you would set up a wildcard A record pointing to your proxy's IP address, or the address of a tunnel to the proxy.

Is there a particular reason why you need to use bind on your ubuntu machine? If not, do you realize that dnsmasq is an included package in the ubuntu distro?

**Comment by CipAppix** [comment]
I don't have a particular reason for using bind.
Could you give me a hint for using dnsmasq then but not in docker, directly from ubuntu 14.04 from DO?

Thanks

**Comment by CipAppix** [comment]
Hmm .. I figure it out...

One question ... how can I forward a dns zone to a different IP (proxy)...

EXAMPLE:
$ORIGIN netflix.com.
$TTL  86400

@   IN  SOA ns1. root (
                2016030402  ; serial
                604800      ; refresh 1w
                86400       ; retry 1d
                2419200     ; expiry 4w
                86400       ; minimum TTL 1d
                )

                IN      NS      ns1.
ns1             IN      A       xxx
@               IN      A       xxx
www             IN      A       xxx


I want xxx to be a proxy IP (different machine) that works on port 1234 (for example).

Regards

**Comment by ab77** [comment]
This is the flow..

1. the client makes a DNS lookup for netflix.com
2. client resolver contacts DNS server
3. DNS server responds with IP of the proxy
4. the client tries to connect to port 80 (HTTP) or 443 (HTTPS) on the
proxy IP

If there isn't a proxy listening on ports 80/443 on the returned IP, then
the client will fail.

If you want to have a proxy listening on a different ports, you will need
to start redirecting ports at the network level, which is not particularly
friendly.

-- ab1

**Comment by CipAppix** [comment]
Aha.
Thank you.

And a final question please.

If my zone is something like this:
zone {
type master;
file "netflix.db";
}

and my file netflix.db is something link this:

$TTL  86400

@   IN  SOA ns1. root (
                2016030401  ; serial
                604800      ; refresh 1w
                86400       ; retry 1d
                2419200     ; expiry 4w
                86400       ; minimum TTL 1d
                )

                IN      NS      ns1.
ns1             IN      A       x.x.x.x
@               IN      A       x.x.x.x
secure        IN      A      x.x.x.x


Question:
How can I make all other subdomains to go directly?
Like help, api, cdn, and many many more...

Regards

**Comment by ab77** [comment]
I think you might want to look at RPZ (
https://en.wikipedia.org/wiki/Response_policy_zone). BIND9 has support for
this time of domain.

**Comment by lbdroid** [comment]
@CipAppix You don't need zone files in dnsmasq. You can just use wildcards in your dnsmasq config file like this;

address=/.somedomain.something/111.111.111.111

**Comment by CipAppix** [comment]
@lbdroid  I made my DNS server with bind so I have zone files.

Thanks
