### ISSUE TITLE
Warnings and error

### ISSUE THREAD

**Issue by MeiRos** [ab77/netflix-proxy#64]
Sorry to bother, but this time I can't make this work.
Here are a few lines from installation:

> Downloading/unpacking docker-compose
>   Downloading docker-compose-1.6.0.tar.gz (126kB): 126kB downloaded
>   Running setup.py (path:/tmp/pip_build_root/docker-compose/setup.py) egg_info for package docker-compose
>     
>     warning: no previously-included files found matching 'README.md'
>     warning: no previously-included files matching '*.pyc' found anywhere in distribution
>     warning: no previously-included files matching '*.pyo' found anywhere in distribution
>     warning: no previously-included files matching '*.un~' found anywhere in distribution
> Downloading/unpacking cached-property>=1.2.0,<2 (from docker-compose)
>   Downloading cached_property-1.3.0-py2.py3-none-any.whl
> Downloading/unpacking docopt>=0.6.1,<0.7 (from docker-compose)
>   Downloading docopt-0.6.2.tar.gz
>   Running setup.py (path:/tmp/pip_build_root/docopt/setup.py) egg_info for package docopt
>     
> Downloading/unpacking PyYAML>=3.10,<4 (from docker-compose)
>   Downloading PyYAML-3.11.tar.gz (248kB): 248kB downloaded
>   Running setup.py (path:/tmp/pip_build_root/PyYAML/setup.py) egg_info for package PyYAML
>     
> Downloading/unpacking requests>=2.6.1,<2.8 (from docker-compose)
>   Downloading requests-2.7.0-py2.py3-none-any.whl (470kB): 470kB downloaded
> Downloading/unpacking texttable>=0.8.1,<0.9 (from docker-compose)
>   Downloading texttable-0.8.4.tar.gz
>   Running setup.py (path:/tmp/pip_build_root/texttable/setup.py) egg_info for package texttable
>     
> Downloading/unpacking websocket-client>=0.32.0,<1.0 (from docker-compose)
>   Downloading websocket_client-0.35.0.tar.gz (193kB): 193kB downloaded
>   Running setup.py (path:/tmp/pip_build_root/websocket-client/setup.py) egg_info for package websocket-client
>     
> Downloading/unpacking docker-py>=1.7.0,<2 (from docker-compose)
>   Downloading docker_py-1.7.0-py2.py3-none-any.whl
> Downloading/unpacking dockerpty>=0.4.1,<0.5 (from docker-compose)
>   Downloading dockerpty-0.4.1.tar.gz
>   Running setup.py (path:/tmp/pip_build_root/dockerpty/setup.py) egg_info for package dockerpty
>     
> Requirement already satisfied (use --upgrade to upgrade): six>=1.3.0,<2 in /usr/lib/python2.7/dist-packages (from docker-compose)
> Downloading/unpacking jsonschema>=2.5.1,<3 (from docker-compose)
>   Downloading jsonschema-2.5.1-py2.py3-none-any.whl
> Downloading/unpacking enum34>=1.0.4,<2 (from docker-compose)
>   Downloading enum34-1.1.2.tar.gz (46kB): 46kB downloaded
>   Running setup.py (path:/tmp/pip_build_root/enum34/setup.py) egg_info for package enum34
>     
> Downloading/unpacking backports.ssl-match-hostname (from websocket-client>=0.32.0,<1.0->docker-compose)
>   Downloading backports.ssl_match_hostname-3.5.0.1.tar.gz
>   Running setup.py (path:/tmp/pip_build_root/backports.ssl-match-hostname/setup.py) egg_info for package backports.ssl-match-hostname
>     
> Downloading/unpacking functools32 (from jsonschema>=2.5.1,<3->docker-compose)
>   Downloading functools32-3.2.3-2.tar.gz
>   Running setup.py (path:/tmp/pip_build_root/functools32/setup.py) egg_info for package functools32
>     
>     warning: no files found matching '*.txt'
>     no previously-included directories found matching 'build'
>     no previously-included directories found matching 'dist'
>     no previously-included directories found matching '.git*'
> Installing collected packages: docker-compose, cached-property, docopt, PyYAML, requests, texttable, websocket-client, docker-py, dockerpty, jsonschema, enum34, backports.ssl-match-hostname, functools32
>   Running setup.py install for docker-compose
>     
>     warning: no previously-included files found matching 'README.md'
>     warning: no previously-included files matching '*.pyc' found anywhere in distribution
>     warning: no previously-included files matching '*.pyo' found anywhere in distribution
>     warning: no previously-included files matching '*.un~' found anywhere in distribution
>     Installing docker-compose script to /usr/local/bin
>   Running setup.py install for docopt
>     
>   Running setup.py install for PyYAML
>     checking if libyaml is compilable
>     x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/check_libyaml.c -o build/temp.linux-x86_64-2.7/check_libyaml.o
>     build/temp.linux-x86_64-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
>      #include <yaml.h>
>                       ^
>     compilation terminated.
>     
>     libyaml is not found or a compiler error: forcing --without-libyaml
>     (if libyaml is installed correctly, you may need to
>      specify the option --include-dirs or uncomment and
>      modify the parameter include_dirs in setup.cfg)
>     
>   Found existing installation: requests 2.2.1
>     Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
>   Running setup.py install for texttable
>     
>   Running setup.py install for websocket-client
>     changing mode of build/scripts-2.7/wsdump.py from 644 to 755
>     
>     changing mode of /usr/local/bin/wsdump.py to 755
>   Running setup.py install for dockerpty
>     
>   Running setup.py install for enum34
>     
>   Running setup.py install for backports.ssl-match-hostname
>     
>   Running setup.py install for functools32
>     
>     warning: no files found matching '*.txt'
>     no previously-included directories found matching 'build'
>     no previously-included directories found matching 'dist'
>     no previously-included directories found matching '.git*'
> Successfully installed docker-compose cached-property docopt PyYAML requests texttable websocket-client docker-py dockerpty jsonschema enum34 backports.ssl-match-hostname functools32
> Cleaning up...
> ERROR: client and server don't have same version (client : 1.21, server: 1.18)

﻿
I used digital ocean's instructions, because last time they worked.

**Comment by ab77** [comment]
Looks like you are missing a dependency for PyYAML.

Try first running 'sudo apt-get -y install libyaml-cpp-dev'

**Comment by ab77** [comment]
Or http://stackoverflow.com/a/24791419/1559300

**Comment by MeiRos** [comment]
I tried both with a clean vps. Didn't help.
Service provider must have change something. Earlier there were Docker Ubuntu-14.04.1-LTS and now only docker-64bit OS where to choose which os to use.
Docker-64 bit is: Docker version 1.6.2, build 7c8fca2 and Ubuntu 14.04.1 LTS

Below a few lines after stackoverflow's instruction.
> Installing python-pip and docker-compose..
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 173 not upgraded.
Downloading/unpacking docker-compose
  Downloading docker-compose-1.6.0.tar.gz (126kB): 126kB downloaded
  Running setup.py (path:/tmp/pip_build_root/docker-compose/setup.py) egg_info for package docker-compose
    
    warning: no previously-included files found matching 'README.md'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.un~' found anywhere in distribution
Downloading/unpacking cached-property>=1.2.0,<2 (from docker-compose)
  Downloading cached_property-1.3.0-py2.py3-none-any.whl
Downloading/unpacking docopt>=0.6.1,<0.7 (from docker-compose)
  Downloading docopt-0.6.2.tar.gz
  Running setup.py (path:/tmp/pip_build_root/docopt/setup.py) egg_info for package docopt
    
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.10,<4 in /usr/local/lib/python2.7/dist-packages (from docker-compose)
Downloading/unpacking requests>=2.6.1,<2.8 (from docker-compose)
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB): 470kB downloaded
Downloading/unpacking texttable>=0.8.1,<0.9 (from docker-compose)
  Downloading texttable-0.8.4.tar.gz
  Running setup.py (path:/tmp/pip_build_root/texttable/setup.py) egg_info for package texttable
    
Downloading/unpacking websocket-client>=0.32.0,<1.0 (from docker-compose)
  Downloading websocket_client-0.35.0.tar.gz (193kB): 193kB downloaded
  Running setup.py (path:/tmp/pip_build_root/websocket-client/setup.py) egg_info for package websocket-client
    
Downloading/unpacking docker-py>=1.7.0,<2 (from docker-compose)
  Downloading docker_py-1.7.0-py2.py3-none-any.whl
Downloading/unpacking dockerpty>=0.4.1,<0.5 (from docker-compose)
  Downloading dockerpty-0.4.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/dockerpty/setup.py) egg_info for package dockerpty
    
Requirement already satisfied (use --upgrade to upgrade): six>=1.3.0,<2 in /usr/lib/python2.7/dist-packages (from docker-compose)
Downloading/unpacking jsonschema>=2.5.1,<3 (from docker-compose)
  Downloading jsonschema-2.5.1-py2.py3-none-any.whl
Downloading/unpacking enum34>=1.0.4,<2 (from docker-compose)
  Downloading enum34-1.1.2.tar.gz (46kB): 46kB downloaded
  Running setup.py (path:/tmp/pip_build_root/enum34/setup.py) egg_info for package enum34
    
Downloading/unpacking backports.ssl-match-hostname (from websocket-client>=0.32.0,<1.0->docker-compose)
  Downloading backports.ssl_match_hostname-3.5.0.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/backports.ssl-match-hostname/setup.py) egg_info for package backports.ssl-match-hostname
    
Downloading/unpacking functools32 (from jsonschema>=2.5.1,<3->docker-compose)
  Downloading functools32-3.2.3-2.tar.gz
  Running setup.py (path:/tmp/pip_build_root/functools32/setup.py) egg_info for package functools32
    
    warning: no files found matching '*.txt'
    no previously-included directories found matching 'build'
    no previously-included directories found matching 'dist'
    no previously-included directories found matching '.git*'
Installing collected packages: docker-compose, cached-property, docopt, requests, texttable, websocket-client, docker-py, dockerpty, jsonschema, enum34, backports.ssl-match-hostname, functools32
  Running setup.py install for docker-compose
    
    warning: no previously-included files found matching 'README.md'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.un~' found anywhere in distribution
    Installing docker-compose script to /usr/local/bin
  Running setup.py install for docopt
    
  Found existing installation: requests 2.2.1
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for texttable
    
  Running setup.py install for websocket-client
    changing mode of build/scripts-2.7/wsdump.py from 644 to 755
    
    changing mode of /usr/local/bin/wsdump.py to 755
  Running setup.py install for dockerpty
    
  Running setup.py install for enum34
    
  Running setup.py install for backports.ssl-match-hostname
    
  Running setup.py install for functools32
    
    warning: no files found matching '*.txt'
    no previously-included directories found matching 'build'
    no previously-included directories found matching 'dist'
    no previously-included directories found matching '.git*'
Successfully installed docker-compose cached-property docopt requests texttable websocket-client docker-py dockerpty jsonschema enum34 backports.ssl-match-hostname functools32
Cleaning up...
Creating and starting Docker containers (from repository)
ERROR: client and server don't have same version (client : 1.21, server: 1.18)

**Comment by ab77** [comment]
Can you choose an OS without Docker? Like vanilla Ubuntu 14.x or Debian 8.x?

If you can, then scroll down to the "Vultr" instructions and use those
(provided you are running as root).

-- ab1

**Comment by MeiRos** [comment]
Thank You for the help! That make it work. No error, but warnings were still there and installation went through. Netflix-proxy was working but my vps wasn't...

btw.
Is there a log for the proxy?
How do I upgrade netflix proxy to a newer version, if needed?

**Comment by ab77** [comment]
No problem, glad it worked. Let me know which VPS and I'll put a note in
the readme.

The logs for sniproxy can be enabled in the config, see example config:
https://github.com/dlundquist/sniproxy/blob/master/sniproxy.conf

You can then update ./data/sniproxy.conf and restart the Docker container.

Because you are running in a docker container, rather than writing files,
you probably want the logs to go to /dev/stdout and /dev/stderr, which you
can then read using 'docker logs sniproxy'.

I had some issues with logging to files (sniproxy was crashing), but this
was using the binary from the Fedora repository, which is the same one the
Docker container uses.

If you want to upgrade sniproxy, you'll need to build it from source. I put
the instructions on my old blog here:
http://blog.belodedenko.me/2014/02/diy-clone-of-netflix-tunlr-vps.html

-- ab1

**Comment by MeiRos** [comment]
Thanks again! I'm very glad you helped me so fast. :)
I'm using Cloud at Cost. I think, it will not be very popular among Netflix-proxy users, because it's for Canadian Netflix. Anyway, it works for that. At least with Ubuntu-14.04.1-LTS-64bit setup.
