### ISSUE TITLE
Add IP

### ISSUE THREAD

**Issue by lesnox** [ab77/netflix-proxy#67]
I have a problem with auth.py, when I use I have that : 

http://0.0.0.0:43867/
87.143.146.11:58607 - - [14/Feb/2016 22:28:04] "HTTP/1.1 GET /auth" - 200 OK
87.143.146.11:58607 - - [14/Feb/2016 22:28:05] "HTTP/1.1 GET /favicon.ico" - 404 Not Found
87.143.146.11:58607 - - [14/Feb/2016 22:28:05] "HTTP/1.1 GET /favicon.ico" - 404 Not Found
u'Authorising ipaddr=87.143.146.11'
u'DEBUG: ipaddr=87.143.146.11, op=I, ipt_cmd=iptables -I FRIENDS -s 87.143.146.11/32 -j ACCEPT -v && iptables-save > /etc/iptables/rules.v4 || iptables-save > /etc/iptables.rules && service docker restart && docker restart bind sniproxy'
87.143.146.11:58607 - - [14/Feb/2016 22:28:17] "HTTP/1.1 POST /auth" - 200 OK

in internet : (0, 'iptables: No chain/target/match by that name.\n', 'ACCEPT  all opt -- in * out *  87.143.146.11  -> 0.0.0.0/0  \ndocker stop/waiting\ndocker start/running, process 2447\nbind\nsniproxy\n')

Have you an idea of error ?? 

Best regards.
Lesnox

**Comment by ab77** [comment]
If you are referring to 404 Not Found errors, they are harmless and can be safely ignored.

Run 'iptables-save' to verify if the address was added to the FRIENDS chain..

-- ab1

**Comment by lesnox** [comment]
Ok super ! ;)

Le lundi 15 février 2016, Anton Belodedenko <notifications@github.com> a
écrit :

> If you are referring to 404 Not Found errors, they are harmless and can be
> safely ignored.
>
> Run 'iptables-save' to verify if the address was added to the FRIENDS
> chain..
>
> -- ab1
>
> > On 14 Feb 2016, at 21:31, lesnox <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > I have a problem with auth.py, when I use I have that :
> >
> > http://0.0.0.0:43867/
> > 87.143.146.11:58607 - - [14/Feb/2016 22:28:04] "HTTP/1.1 GET /auth" -
> 200 OK
> > 87.143.146.11:58607 - - [14/Feb/2016 22:28:05] "HTTP/1.1 GET
> /favicon.ico" - 404 Not Found
> > 87.143.146.11:58607 - - [14/Feb/2016 22:28:05] "HTTP/1.1 GET
> /favicon.ico" - 404 Not Found
> > u'Authorising ipaddr=87.143.146.11'
> > u'DEBUG: ipaddr=87.143.146.11, op=I, ipt_cmd=iptables -I FRIENDS -s
> 87.143.146.11/32 -j ACCEPT -v && iptables-save > /etc/iptables/rules.v4
> || iptables-save > /etc/iptables.rules && service docker restart && docker
> restart bind sniproxy'
> > 87.143.146.11:58607 - - [14/Feb/2016 22:28:17] "HTTP/1.1 POST /auth" -
> 200 OK
> >
> > Have you an idea of error ??
> >
> > Best regards.
> > Lesnox
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ab77/netflix-proxy/issues/67#issuecomment-183999221>.
>


-- 
-Boisseau Julien-
Lerchesflurweg 18
66119 SAARBRUCKEN
(Allemagne)

Portable : 00 33 6 98 16 27 38

Ce message et les fichiers qui y sont éventuellement joints sont
exclusivement réservés au destinataire. Il peut contenir des données ou des
informations confidentielles ou protégées par la loi. Si ce message vous
est parvenu par erreur, nous vous prions de l’effacer sans effectuer de
reproduction et d’informer l’expéditeur. Nous vous remercions de votre
collaboration.

This message and any attached files are for the sole use of the recipient
named above. It may contain confidential or legally protected data or
information. If you have received this message in error, please delete it
without making any copies whats oever and notify the sender. Thank you for
your assistance.
