### ISSUE TITLE
Blocked

### ISSUE THREAD

**Issue by kyle95wm** [ab77/netflix-proxy#68]
I just used a spare DO droplet for accessing netflix via DNS method and they picked it up. RIP

**Comment by chovy** [comment]
go on lowendtalk and find a provider.

**Comment by ab77** [comment]
Yep, just confirmed all the DO IPs I've tried are blocked.

**Comment by ab77** [comment]
Feel free to re-build and test again, it is working again (at least for now).

-- ab1

**Comment by kyle95wm** [comment]
What service are you using? DO?

**Comment by ab77** [comment]
Tested on DO and Vultr as per the readme.

-- ab1

**Comment by kyle95wm** [comment]
ah. I see well its working fine for me. I'm a bit confused as to why we need IPV6 to be enabled on our droplets, and more importantly what's changed in terms of commits in laymen's terms.

**Comment by ab77** [comment]
The most important change is IPv6. Without it, it won't unblock Netflix as
they've blocked most IPv4 addresses used by most cloud hosting providers.

-- ab1

On 27 February 2016 at 23:13, Kyle Warwick-Mathieu <notifications@github.com

**Comment by kyle95wm** [comment]
Right, BUT we in Canada don't yet have IPV6 support (routable addresses) and in the readme it tells us to disable IPV6 on our network/devices. I'm assuming IPV6 is used to actually trick netflix and not be used for the CLIENTS. Correct me if I'm wrong.

**Comment by ab77** [comment]
IPv6 on your VPS/cloud server = enable; IPv6 on your home network = disable.

-- ab1

On 27 February 2016 at 23:17, Kyle Warwick-Mathieu <notifications@github.com

**Comment by kyle95wm** [comment]
Okay but you still haven't answered my question about IPV6. Does Netflix see the IPV6 address of the VPS? I'm assuming IPV4 traffic is tunnelled somehow?

**Comment by kyle95wm** [comment]
Obviously this isn't relevant to the 'issue" but I made a video showing this project. https://www.youtube.com/watch?v=vPNG878IBJU&ab_channel=TheATBVCopyrightChannel I had this on my tech channel but it was taken down by YouTube because of "inaaprioate content" so I had no choice but to post it on my "I don't give a shit" channel

**Comment by ab77** [comment]
Yes, if you select IPv6 during build, Netflix will see your IPv6 address. There is no tunnelling as such used anywhere.

You -- ipv4 --> VPS proxy --- ipv6 --> Netflix

Hope that makes it clear..

-- ab1
