### ISSUE TITLE
Nutflax down!

### ISSUE THREAD

**Issue by WeirdG** [ab77/netflix-proxy#70]
Just got this working on BuyVM, but received this error message when going to Netflix.

> Whoops, something went wrong...
> 
> Streaming Error
> 
> You seem to be using an unblocker or proxy. Please turn off any of these services and try again. For more help, visit netflix.com/proxy.

Is there anything that can be done to get around it?

**Comment by chovy** [comment]
where were you hosting it?

**Comment by WeirdG** [comment]
BuyVM LV server.

**Comment by ab77** [comment]
Casting or AirPlaying by any chance?

**Comment by WeirdG** [comment]
Nope... Tried from two laptops (Windows 10 and Macbook), a Samsung SmartTV, and a Sony Blu-ray Player.  No dice when I go to play.  I think they might be blocking my host BuyVM.

I also tried the solution at the link below, and that also gave me the same results.
https://vpsboard.com/topic/7754-sni-proxy-bind-in-ubuntu/

**Comment by ab77** [comment]
Could be.. Have a look with Chrome or Safari Developer Tools what network requests the browser is making and what responses it is getting from Netflix..

**Comment by Weirdness** [comment]
Trying a new VPS now.  Turfing DO and BuyVM.  Hopefully this one works.  Just waiting for them to provision a server for me.

**Comment by hdibani** [comment]
Just got the same message, I am hosting on Digital Ocean, Let's see if a different VPS will do (was using DO.

**Comment by Weirdness** [comment]
Ya... DO crapped out on me a few days ago.

**Comment by hdibani** [comment]
Any luck with your new VPS?

**Comment by Weirdness** [comment]
Building it now.

**Comment by WeirdG** [comment]
w00t! w00t!  Got it working with my new VPS provider.  It's official, BuyVM, DO, and Linode are blacklisted.

**Comment by cheapsteak** [comment]
hudsonvalleyhost does not work

**Comment by ab77** [comment]
Yep, confirmed - DO is blocked (at least the tests I've done). However, there are plenty of other, less known providers that I am sure will continue to work just fine as long as people don't advertise them of forums, etc.

**Comment by ab77** [comment]
Feel free to re-build and test again, it is working again (at least for now).

-- ab1
