### ISSUE TITLE
Rebooting causes docker containers to stop working.

### ISSUE THREAD

**Issue by WeirdG** [ab77/netflix-proxy#72]
I'm running Debian 8.0.  During the initial install of the netflix-proxy, everything was working fine.  I decided to do a reboot and when the server came back up, netflix-proxy stopped working.  I wasn't sure what to do, so I deleted and re-added the two docker containers.  That seemed to fix the problem.

Is there anyway I can avoid this issue in the future, if I choose to reboot again?

**Comment by WeirdG** [comment]
Nvm... spoke too soon.  It's still not working, even after the reboot.

**Comment by ab77** [comment]
I just tested it under Debian 8.3 x64 (DigitalOcean) and it reboots fine.
All Docker containers are running on start-up.

Can you rebuild, reboot and run `docker ps` upon logging back in please.

Also, check output of `iptables-save` before and after the reboot..

-- ab1

**Comment by ab77** [comment]
Can you please share the output of `iptables-save` as well as `docker ps`
before and after the reboot..

-- ab1

**Comment by WeirdG** [comment]
Doh!  Okay... I'll rebuild again.  Gimme some time.  Question, does matter which version of Docker I use?  I'm using the newest version.

**Comment by WeirdG** [comment]
Interesting... I just did a restart of the docker service, and now it seems to be working.  Testing.  Will keep you posted.

**Comment by WeirdG** [comment]
Confirmed.  Upon reboot, the docker service appears to start properly.  When I add the server as a DNS entry on my laptop, it doesn't work.  My laptop is unable to resolve names.

After running 'sudo service docker restart', everything works fine.  My laptop is able to resolve names, and when I browse the internet I can access Netflix/Pandora without any issues.

Any idea why I need to restart the docker service after every reboot?

**Comment by ab77** [comment]
OK, probably a startup order issue. What provider are you using? I'll test it out myself..

**Comment by WeirdG** [comment]
Sent you an email.... didn't want to plaster my provider on GitHub.

**Comment by WeirdG** [comment]
Here are the errors I found.

`● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled)
   Active: active (running) since Wed 2016-03-02 00:07:45 MST; 1min 32s ago
     Docs: https://docs.docker.com
 Main PID: 468 (docker)
   CGroup: /system.slice/docker.service
           └─468 /usr/bin/docker daemon -H fd://

Mar 02 00:07:45 MYSERVER docker[468]: ..time="2016-03-02T00:07:45.462199763-07:00" level=warning msg="Your kernel does not support OOM notifications: There is no path for \"memory\" in state"
Mar 02 00:07:45 MYSERVER docker[468]: time="2016-03-02T00:07:45.462233569-07:00" level=warning msg="Your kernel does not support OOM notifications: There is no path for \"memory\" in state"
Mar 02 00:07:45 MYSERVER docker[468]: time="2016-03-02T00:07:45.494784515-07:00" level=warning msg="Your kernel does not support OOM notifications: There is no path for \"memory\" in state"
Mar 02 00:07:45 MYSERVER docker[468]: time="2016-03-02T00:07:45.494814505-07:00" level=warning msg="Your kernel does not support OOM notifications: There is no path for \"memory\" in state"
Mar 02 00:07:45 MYSERVER docker[468]: time="2016-03-02T00:07:45.495528148-07:00" level=info msg="Loading containers: done."
Mar 02 00:07:45 MYSERVER docker[468]: time="2016-03-02T00:07:45.495545357-07:00" level=info msg="Daemon has completed initialization"
Mar 02 00:07:45 MYSERVER docker[468]: time="2016-03-02T00:07:45.495566551-07:00" level=info msg="Docker daemon" commit=c3959b1 execdriver=native-0.2 graphdriver=aufs version=1.10.2
Mar 02 00:07:45 MYSERVER docker[468]: time="2016-03-02T00:07:45.622074174-07:00" level=info msg="API listen on /var/run/docker.sock"
Mar 02 00:07:45 MYSERVER docker[468]: time="2016-03-02T00:07:45.710360115-07:00" level=error msg="Handler for POST /v1.22/containers/bind/start returned error: Container already started"
Mar 02 00:07:45 MYSERVER docker[468]: time="2016-03-02T00:07:45.711366648-07:00" level=error msg="Handler for POST /v1.22/containers/sniproxy/start returned error: Container already started"`

**Comment by ab77** [comment]
I made a small change to the build script, try to re-deploy and test again..

-- ab1

**Comment by ab77** [comment]
Found the problem - on DHCP enabled systems, Docker service starts before the public IP is available, so containers don't bind to it.

I put the fix in the main branch, so please try to redeploy from scratch and let me know how it goes..

-- ab1

**Comment by WeirdG** [comment]
That's awesome!  Thanks for figuring that out.  I'll rebuild and try again.

**Comment by WeirdG** [comment]
Just finished rebuilding.  The first time I did a reboot, I needed to restart the docker service because it wasn't working properly.  

I rebooted two more times after that, and everything worked properly.  I guess I'll report back if the docker service gitches again.

**Comment by ab77** [comment]
Hmm, strange, if this happens again, you need to go through the syslog to see when the docker service loads and when the dhcp response is received. If the later is after the docker container start, then there is a problem.

You could ask your provider if hard coding the IP instead of DHCP is a valid supported option. If it is, do that and it should sort out this problem once and for all. Because after all, DHCP on a DNS server is a bad idea generally..

-- ab1

**Comment by WeirdG** [comment]
K... thanks... I'll see if I can setup something static.

**Comment by ab77** [comment]
OK, I'll close this for now at least.
