### ISSUE TITLE
port 53 reject connections

### ISSUE THREAD

**Issue by eqmo** [ab77/netflix-proxy#73]
Everything works perfect for about 10~15 minutes, after that the dos stops respond. If I query from the server it's ok, but not from my home.  

Restart the docker containers doesn't work, I had to rebuild to get it work again.

iptables issue?

**Comment by ab77** [comment]
Is the BIND container crashing maybe? When it stops working, can you run `docker ps` to see what is running...

**Comment by eqmo** [comment]
Yes, It's running. If I restart the docker container doesn't work, port 53 still don't answer.

**Comment by ab77** [comment]
I am unable to replicate the issue. I am using DigitalOcean. The VPS is built with IPv6 support. I've fixed some issues in the BIND config just now, so you may want to try rebuilding, but I doubt those updates will address your specific issue.

You could temporarily drop iptables (`iptables -F && ip6tables -F`) to see if it is causing the problem. Reload back by running `iptables-restore < /etc/iptables/rules.v4 && ip6tables-restore /etc/iptables/rules.v6` or reboot.

I've also fixed BIND logging, so you can run `docker logs bind` to see if there are any errors in its functionality.

Let me know how your troubleshooting goes..

-- ab1

**Comment by eqmo** [comment]
The problem is solved when I drop the iptables. So I create a new droplet with ipv6 support(last one doesn't). and rebuild again. It's working for about 1 hour now, a little slow sometimes but  I think is solved. Thanks

**Comment by ab77** [comment]
No problem, glad it is working for you.
