### ISSUE TITLE
VM has a new IP

### ISSUE THREAD

**Issue by gviddy** [ab77/netflix-proxy#74]
I am running an Ubuntu image.. I shutdown the VM and restarted it resulting in a new IP...

Is there anything I need to run now that the IP has changed?  Also is there a handy way to test that everything is working again?

**Comment by ab77** [comment]
You should only need to change the DNS server on the device you are
watching to the new server address.

If your home IP changes, you will need to update the iptables rules.

-- ab1

**Comment by gviddy** [comment]
thanks.... that's what I thought too however I am now getting this error from Netflix: netflix has encountered an error nw-2-5

A couple of days ago I got the dreaded 'a proxy has been detected' so I decided to reboot the VM to get a new IP and see if that gets past it.. However this new error seems to be stopping me...

**Comment by gviddy** [comment]
Oh and if this helps.. I am on Xbox One... When i check network settings in Netflix I get the following errors.

Netflix server 1  X
Netflix server 2 X
Netflix server 3 X
Internet Connection OK

So it fails connecting to the Netflix servers....

**Comment by gviddy** [comment]
Does it matter that the db.override file still has the old IP ?

**Comment by ab77** [comment]
Oh, yes it does, you should m change it and restart BIND.

**Comment by gviddy** [comment]
And you do this all in the docker? correct?

**Comment by ab77** [comment]
Right, so first edit your `db.override` file to update the IP, then run `docker restart bind`.

Also, you should probably find a VPS which doesn't change the IP randomly. It is a server after all and servers shouldn't change their IPs..

-- ab1

**Comment by gviddy** [comment]
Agreed.. However Netflix seems to have blocked the IP and that's why I needed to change it. :)

**Comment by ab77** [comment]
Shall I close?

**Comment by gviddy** [comment]
Oh I couldn't get it to work. Not sure am I supposed to edit the file in the docker? or edit the file on the VM? Do I recompile the code?

As it is I just created a brand new VM and did a fresh install... :)

**Comment by ab77** [comment]
OK, if it happens next time, edit the file on the host and restart the
containers or just reboot.

-- ab1

**Comment by gviddy** [comment]
awesome. thanks!  :)
