### ISSUE TITLE
Script for Ramnode

### ISSUE THREAD

**Issue by mhergon** [ab77/netflix-proxy#76]
hi,

Can you post instructions to get script working on Ramnode VPS servers?

Thanks!

**Comment by ab77** [comment]
Hi there, for Ramnode (KVM only) use the following command:

`Ubuntu 14.04 x86_64 Server Minimal` or `Debian 8.0 x86_64 Minimal` images:

```apt-get update && apt-get -y install vim dnsutils curl sudo git && curl -sSL https://get.docker.com/ | sh && git clone https://github.com/ab77/netflix-proxy /opt/netflix-proxy && cd /opt/netflix-proxy && ./build.sh```

I've also updated the [readme](https://github.com/ab77/netflix-proxy/blob/master/README.md).

Note: OpenVZ won't work, don't every bother trying.

-- ab1
