### ISSUE TITLE
Netflix doesn't work from browser

### ISSUE THREAD

**Issue by EpicPilgrim** [ab77/netflix-proxy#77]
Using my browser with my EC2 IP configured (running netflix-proxy), I keep getting redirected to my local Netflix. On the same network, my iPhone and iPad running Netflix apps are properly redirected to the US Netflix. Can't figure out why my browser won't show the other region. Done all standard cache/cookie resets, etc.

**Comment by ab77** [comment]
Have you checked if the browser is preferring IPv6 over IPv4? Also, do a DNS lookup (e.g. `dig netflix.com`) on your PC (running the browser) to make sure it returns the correct address and if it does, try Chrome in Incognito mode..

-- ab1

**Comment by EpicPilgrim** [comment]
Hi Anton

Yes, ipv4 is definitely what is being used here, no ipv6 on this network but I've disabled v6 in the browser anyway and no difference. Interestingly, on the login page, Netflix shows me their US phone number, so they think I'm in the US until I login.

I can't figure out how to "update" netflix-proxy on my EC2 instance, I don't know Docker that well and build.sh keeps crashing out for one reason or another. Not sure if that's part of it. I spun the current version up in January and I see you've made some changes since then.

Thanks

Brett

**Comment by ab77** [comment]
Can you re-deploy the OS and netflix-proxy from scratch?

If you can't destroy/re-install the OS for some reason, the following steps should remove everything (except Docker) and re-deploy netflix-proxy:

```
cd / && docker stop sniproxy bind && docker rm sniproxy bind && rm -rf /opt/netflix-proxy && iptables -F && iptables -F -t nat && iptables -X ALLOW && iptables -X FRIENDS && sudo usermod -aG docker $(whoami | awk '{print $1}') && sudo git clone https://github.com/ab77/netflix-proxy /opt/netflix-proxy && cd /opt/netflix-proxy && ./build.sh
```

If the build script throws errors, please send me the output of the build script and I'll take a look.

But all of this is irrelevant, if some devices work and some don't. You need to do some detective work to see what the difference is between these devices..

-- ab1

**Comment by ab77** [comment]
Did you get anywhere with this, if so, can I close?

**Comment by pmoon00** [comment]
Hi there,

I'm having the same issue.  I've made sure it's going over IPv4 and I'm getting the same behaviour as EpicPilgrim.

When I got to netflix.com I'm getting the US phone number at the bottom, can log in, can search shows that are available in the US, but when I go to stream them I get a streaming error with code M7111-1331-5059.

I thought it might have been my previous server provider IP getting blocked, so I moved to another one and am getting the same issue.

Any help would be much appreciated!  This netflix-proxy is so damn cool!

Thanks

**Comment by ab77** [comment]
@pmoon00: please run and post the output of `ifconfig` on your VPS..

**Comment by pmoon00** [comment]
@ab77 

`docker0   Link encap:Ethernet  HWaddr 02:42:c4:e0:39:e7
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 00:16:3e:82:4d:9d
          inet addr:199.233.236.206  Bcast:199.233.236.255  Mask:255.255.255.192
          inet6 addr: fe80::216:3eff:fe82:4d9d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:118934 errors:80 dropped:0 overruns:0 frame:0
          TX packets:84272 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:507059696 (507.0 MB)  TX bytes:16444988 (16.4 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:20 errors:0 dropped:0 overruns:0 frame:0
          TX packets:20 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:5067 (5.0 KB)  TX bytes:5067 (5.0 KB)

`

**Comment by ab77** [comment]
@pmoon00: You don't have a public IPv6 address on your VPS, that is why it isn't working. Netflix has blocked all known IPv4 ranges used by popular VPS providers. Your best option is to redeploy on a provider with IPv6 support.

**Comment by pmoon00** [comment]
@ab77 I've got a second VPS that does have an IPv6 address, I get the same issue.  Here is the ifconfig

`docker0   Link encap:Ethernet  HWaddr 02:42:11:34:1f:96
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 00:16:3c:b0:86:26
          inet addr:168.235.92.239  Bcast:168.235.92.255  Mask:255.255.255.0
          inet6 addr: 2604:180:3:84::8c3d/64 Scope:Global
          inet6 addr: fe80::216:3cff:feb0:8626/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:243692970 errors:0 dropped:309 overruns:0 frame:0
          TX packets:7611989 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:18433163559 (18.4 GB)  TX bytes:2289366452 (2.2 GB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1299 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1299 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:127401 (127.4 KB)  TX bytes:127401 (127.4 KB)
`

**Comment by ab77** [comment]
Please take this to #netflix-proxy on freenode (IRC).

Cheers!
