### ISSUE TITLE
SNI Proxy traffic isn't show - question

### ISSUE THREAD

**Issue by eqmo** [ab77/netflix-proxy#78]
Hi, there is a reason why I can't see the real bandwidth and amount of GB traffic in the droplet?

**Comment by ab77** [comment]
Have you seen [this](https://www.digitalocean.com/company/blog/announcing-digitalocean-graphs/)?

-- ab1

**Comment by eqmo** [comment]
Yes, that works for my other droplets but for netflix proxy doesn't. 
Even the ifconfig show me only the data transfers I made by wget.

I really appreciate if you can help me with this, It work perfectly thank you again.

![screen shot 2016-03-01 at 5 14 30 pm](https://cloud.githubusercontent.com/assets/11879293/13422780/de6c8398-dfd1-11e5-8338-746df24c5550.png)
![screen shot 2016-03-01 at 5 16 15 pm](https://cloud.githubusercontent.com/assets/11879293/13422781/ded4dc04-dfd1-11e5-9cdd-abdb391b2252.jpg)

**Comment by ab77** [comment]
Hi, please contact DO with regards to that specific issue.

It may be that they have not enabled the bandwidth collection in that
specific DC or something else isn't right with the deployment.

-- ab1

**Comment by eqmo** [comment]
I'll. Thank you.
