### ISSUE TITLE
WHOOPS SOMETHING WET WRONG

### ISSUE THREAD

**Issue by zhuxl09** [ab77/netflix-proxy#81]
iNTERNET CONNECTION PROBLEM
To resolve this issue ,please follow the steps in our help center.

https://help.netflix.com/en/node/190
Netflix Error N8202

**Comment by ab77** [comment]
```
# on the home PC
dig netflix.com
```

```
# on the VPS
ifconfig
```

**Comment by ab77** [comment]
Please take this to #netflix-proxy on freenode (IRC).

Cheers!
