### ISSUE TITLE
If iptables fails initially, build.sh breaks

### ISSUE THREAD

**Issue by birjolaxew** [ab77/netflix-proxy#82]
When I initially ran build.sh, I got the error described in #60 for whatever reason (possibly because I `sudo`'d it?). This means that the script got past [build.sh#L144](https://github.com/ab77/netflix-proxy/blob/ed6a5e4d10c5c2b5ba8716ff54ce3ffc1f80e323/build.sh#L114), creating the `FRIENDS` chain in iptables.

Running the script again stopped it with 

    adding IPv4 iptables rules..
    iptables: Chain already exists.

After removing the chain (`iptables -X FRIENDS`) everything worked fine and the rest of the script executed as expected.

**Comment by ab77** [comment]
Hi, if you run the script as sudo, you need to pass '-H' flag to preserve environment variables. But in any case, you don't have to run it under sudo as it already performs all the necessary steps as root automatically.

**Comment by birjolaxew** [comment]
The issue is that, if the script fails for any reason (or the chain `FRIENDS` already exists in your iptables), it'll keep failing until you manually delete the chain.

**Comment by ab77** [comment]
I am aware. I never wrote the build script to be idempotent. There are too
many clean-up scenarios to consider and it is far less effort to destroy
and re-deploy from scratch.

But yes, if you want to reset the server back to the state which will allow
the script to be re-run, you'll need to clean-up manually:

sudo docker stop bind sniproxy && \
  sudo docker rm bind sniproxy && \
  sudo iptables -F && \
  sudo iptables -F -t nat && \
  sudo ip6tables -F && \
  sudo ip6tables -F -t nat && \
  sudo iptables -X ALLOW && \
  sudo iptables -X FRIENDS && \
  sudo ip6tables -X ALLOW
  sudo service docker restart && \
  sudo cd / && \
  sudo rm -rf /opt/netflix-proxy

-- ab1
