### ISSUE TITLE
Netflix still blocking, HBO NOW working.

### ISSUE THREAD

**Issue by nickpope** [ab77/netflix-proxy#83]
Hi,

First of all, thank you so much for setting this up! This also allowed me to get HBO NOW working on my Apple TV. Previously we had to airplay from our iPhone running a vpn which was pretty painful.

After fighting a bit with docker (was on old versions) I got this working. When I tested it on Netflix however I am still getting blocked.

I tested with sni-velox.ch and everything checked out. I ran dig on my machine and got the following (where XXX.XXX.XXX.XXX is the proper IP for my droplet):

```
; <<>> DiG 9.8.3-P1 <<>> netflix.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31069
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; QUESTION SECTION:
;netflix.com.			IN	A

;; ANSWER SECTION:
netflix.com.		86400	IN	A	XXX.XXX.XXX.XXX

;; AUTHORITY SECTION:
netflix.com.		86400	IN	NS	ns1.netflix.com.

;; ADDITIONAL SECTION:
ns1.netflix.com.	86400	IN	A	XXX.XXX.XXX.XXX

;; Query time: 87 msec
;; SERVER: XXX.XXX.XXX.XXX#53(XXX.XXX.XXX.XXX)
;; WHEN: Sun Mar  6 15:07:59 2016
;; MSG SIZE  rcvd: 79
```

I have also added `nflxvideo.net.` to `.data/zones.override`, but still no avail.

Are there more zones that need to be added?

**Comment by ab77** [comment]
Jump onto #netflix-proxy on freenode (IRC) and we can troubleshoot... 

https://webchat.freenode.net/?channels=netflix-proxy
