### ISSUE TITLE
Netflix One Profile Works, Others Don't

### ISSUE THREAD

**Issue by envoys** [ab77/netflix-proxy#84]
Not even sure this is a netflix-proxy issue, but I have my account with 3 profiles. 2 of the profiles tell me I am using a proxy when I try and watch a show, the other profile can watch the exact same show no problems. The 2 profiles are the default profile and just a regular one. Very weird activity...I don't get it. If I create a new profile, it is able to watch the shows no problem as well. Not such a big deal, but having the main profile say its using a proxy but other profile is working fine baffles me.

**Comment by WeirdG** [comment]
Odd.... are all your profiles with the same provider?  I ran into the same issue with two different providers.  Turns out their IP ranges were blacklisted.  Found another provider which hasn't been blacklisted yet.

**Comment by ab77** [comment]
Maybe it is something to do with stale session cookies. Have you tried a fresh browser session or even a completely different browser. Logging out of all your devices, etc. I would have thought geo blocking would be done at the IP level, well maybe the account level, but certainly not at the profile level..

**Comment by envoys** [comment]
Yes it's very odd. It's happening on multiple devices all usinch the same dns. Even tried unblockus and same issue. I don't get it. It's happening on a Sony tv, Apple TV, chrome on Mac and IE in Windows. Just tested the one profile Jack and it says I am using a proxy so I deleted that profile and recreated it with the same name and now it's not blocked. Very puzzling. One thing I could think of is I have got the using a proxy error multiple times under these two profiles so I got flagged by Netflix for using unblocking and recreating the one profile removes the flag. Obviously I can't remove the main profile so I guess for now I will have to recreate my profiles if it happens again.

**Comment by WeirdG** [comment]
Oooh... three Netflix profiles under one account.  Very weird that two won't work and one will.  Try resetting the app on those devices, and then login again.  With some devices there's an option to reset the Netflix app... have you tried that?

**Comment by ab77** [comment]
This is baffling, although it is an useful insight into how Netflix handle detection and enforcement of users connecting via proxies.

You should jump onto the IRC channel and ask if anyone else has seen similar behavior. Details in the README..

I'll close this for now.

-- ab1

**Comment by envoys** [comment]
I know this is closed but just to update, I added the nflxvideo.net to the DNS and now all profiles are working, so strange that only 1 profile would be affected by the new blocking.

**Comment by ab77** [comment]
I put an update at the bottom of the README [n12] on new-auth, have a read and you'll probably get an idea what is going on..
