### ISSUE TITLE
auto-authorize the IP visiting URL generated using ./auth.py

### ISSUE THREAD

**Issue by ahmednitul** [ab77/netflix-proxy#86]
Hello,

Can someone provide either a modified auth.py or customized auth.html to automatically add the user-ip, I mean I wish to ignore submit button, and as I would like to share my server with friends and my community buddies, I just want to give them an URL, visiting which their IP shall be added to the server.

& it would be also nice if this customized scripts redirect the visitor to some URL/Link instead of displaying the status info, or just show "Congratulations! your IP has been enabled... now you'll be forwarding to our friendly site to learn more..."

Thanks!

**Comment by ab77** [comment]
You can easily change the code to do that, but how do you intent to protect your public server from being used (abused?) by anyone else outside of your group?

Probably not such a great idea..

-- ab1

**Comment by ahmednitul** [comment]
I have already tried and failed :( I am not good at programming/coding and that's why I asked if anyone could share such a code, I have about 37 idle servers- for which I am already paying every month but not even using half of the allocated bandwidth, so I was planning to share these server as public one to our local ISP community and I'd be also glad to share them with other netflix-proxy users like those members in freenode chat room- however, if I see that some server started being used too heavily, I'll stop the auth.py process to make sure no new members are able to register but let the existing users enjoy it.

There was a service like this **tvunblock.com ** which was very popular and ranked two in google search for netflix dns proxy, but last week they closed their door because their IPs are starting to get blocked by Netflix too quickly, and its now only available to existing users.

So, I am kind of trying to do something like this- It would be so appreciating- if you or someone else can write this few short-line code and share with me and also add that inside the git as extra feature so other peoples like me also can share their love.

If I am able to get it done, I'll share few dozens DNS IPs here so people who are failed to work with netflix-proxy and/or have their server's IP/range already blacklisted may enjoy the sweet experience of this love.

Thanks and regards,
Ahmed Nitul Hossain

**Comment by ab77** [comment]
You could try ask someone on #netflix-proxy IRC channel (freenode).

**Comment by ab77** [comment]
Try deploying the [new](https://github.com/ab77/netflix-proxy/tree/new-auth) version, set  `AUTO_AUTH=True` in `auth/settings.py` and run `service sdns-admin restart`.

It the automatic authorization works, it will redirect back to `google.com` after authorizing the IP.

-- ab1
