### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by Ezzahh** [ab77/netflix-proxy#87]
I'm using DigitalOcean with docker (as per instructions), but it's extremely slow loading Netflix? If I use openvpn or something else like SoftEther, it is a lot faster. I assumed that this would be a bit faster?

I added the zone update that was provided, which should stream through the entire server, but the dstat only shows 130k recv and 50 k send (to me). I have a good internet connection, over 100mbps up and down, and the DigitalOcean should be capable of something better? I can watch but the resolution is really low and very slow to load.

If I install a vpn like openvpn or SoftEther, it will load much faster, but will be blocked from IP range, though I am hoping we can fix this slow stream issue, because I can watch US content, but the resolution is like 360p.

**Comment by ab77** [comment]
Make sure the relevant DNS traffic is really going via your VPS (check with browser dev. tools). It could also be a transient issue, so wait and try at another time. If problem persists, try a different VPS..

**Comment by Ezzahh** [comment]
I assume that if netflix is showing me US content that it should be going through the VPS? I'm not sure how to check with browser dev. tools. I've tried with 2 other VPS providers and it's still really slow, even without the stream traffic going through.

**Comment by ab77** [comment]
Try put a speedtest site domain into your `zones.override`, restart BIND and do some speed tests through your VPS. Repeat direct. Compare..

Also, when you are watching Netflix, monitor using the diag. screen for playing bitrate vs. buffering bitrate and maybe try manual bitrate lock:
http://qz.com/261426/the-hidden-commands-for-diagnosing-and-improving-your-netflix-streaming-quality/

Sending all traffic through the VPS is never going to be as fast as watching directly via your closest POP, but there has to be a trade-off somewhere, while the studios are pulling their finger out.

-- ab1

:smirk:

**Comment by Ezzahh** [comment]
Hmmm, no luck. Once I started trying to update the zones file, it started breaking things. I couldn't access anything but those in the zones file. Google, etc, would not resolve. I restarted bind with "docker restart [container]", since docker bind restart does not work. I tried changing the CDN location and bitrate, but to no avail. Netflix would give me a "Internet connection error".

**Comment by ab77** [comment]
Delete everything and start again.

**Comment by Ezzahh** [comment]
I already have done this 3-4 times lol. Looks like I won't be watching US content. Thanks anyways.

**Comment by ab77** [comment]
Don't give up, try the [new](https://github.com/ab77/netflix-proxy/tree/new-auth) version first..

:grimacing:
