### ISSUE TITLE
No DNS resolution

### ISSUE THREAD

**Issue by mike548141** [ab77/netflix-proxy#88]
Hi this does not seem to be working anymore.  The Droplet creation is fine and your install script appears to complete properly, it says the proxy is running at the end.
However I'm not getting any DNS resolution from the Droplet as a DNS server.  I can resolve names from the Droplets console (it uses Google 8.8.8.8) but if I set the DNS on my computer to the Droplet I get no response.

**Comment by ab77** [comment]
Try `dig netflix.com @localhost` on your VPS first..

**Comment by mike548141** [comment]
Hi @ab77 

I had already destroyed the original droplet which I created in the San Francisco data centre.  So I created a new one in New York 3.

dig on the VPS works so I assume there is a host based firewall on the Droplet blocking DNS?  Sorry I have never used Digital Ocean Droplets before.
I still can not perform look ups from my computers to the Droplet, I can lookup to other (random) DNS servers.  I have tested from a few different Internet connections that use different ISP's to ensure the ISP is not messing with the traffic.  My firewalls do not block DNS lookups to any destination.

> ---

DONE
/opt/netflix-proxy
Change your DNS to 104.236.221.101 and start watching Netflix out of region.
Done!
root@ubuntu-512mb-nyc3-01:/opt/netflix-proxy# 
root@ubuntu-512mb-nyc3-01:/opt/netflix-proxy# 
root@ubuntu-512mb-nyc3-01:/opt/netflix-proxy# dig netflix.com @localhost

; <<>> DiG 9.9.5-3ubuntu0.7-Ubuntu <<>> netflix.com @localhost
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52373
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;netflix.com.			IN	A

;; ANSWER SECTION:
netflix.com.		86400	IN	A	104.236.221.101

;; AUTHORITY SECTION:
netflix.com.		86400	IN	NS	ns1.netflix.com.

;; ADDITIONAL SECTION:
ns1.netflix.com.	86400	IN	A	104.236.221.101

;; Query time: 3 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Mar 09 19:31:01 EST 2016
;; MSG SIZE  rcvd: 90

root@ubuntu-512mb-nyc3-01:/opt/netflix-proxy#

**Comment by ab77** [comment]
The most likely case is that your home IP is not in the iptables (firewall) on the VPS.

Blow everything away and start again, this time making sure to SSH to your host direct and then running `build.sh` without `sudo`, preserving the `${SSH_CONNECTION}` variable.

Check iptables rules by running `iptables-save | more` to make sure you home IP address in the `FRIENDS` group.

Failing all that, you could try the [new](https://github.com/ab77/netflix-proxy/tree/new-auth) version, which will bring up a web interface if your IP isn't authorized.

-- ab1

**Comment by mike548141** [comment]
Sorry I was following instructables and not your instructions on GitHub http://www.instructables.com/id/Build-your-own-Smart-DNS-Proxy-and-unblock-Netflix/

Following your instructions I get the following, I think the script is not completing properly (username, password and IP's sanitised).
`root@docker:~# 
root@docker:~# ping6 netflix.com
connect: Network is unreachable
root@docker:~# git clone https://github.com/ab77/netflix-proxy /opt/netflix-proxy && cd /opt/netflix-proxy && ./build.sh -u [my username] -p [my password]
Cloning into '/opt/netflix-proxy'...
remote: Counting objects: 2894, done.
remote: Compressing objects: 100% (115/115), done.
remote: Total 2894 (delta 47), reused 0 (delta 0), pack-reused 2769
Receiving objects: 100% (2894/2894), 51.82 MiB | 20.11 MiB/s, done.
Resolving deltas: 100% (1573/1573), done.
Checking connectivity... done.
resolved params: clientip=1.2.3.4 ipaddr=2.3.4.5 extip=2.3.4.5
cmd: ./build.sh -r=1 -b=0 -s= -z=0 -n=1 -u=[my username] -p [secret] -k [secret]

 * disabling native IPv6 on eth0...                                                                                                                      [ OK ] 
 * installing XPath...                                                                                                                                   [ OK ] 
 * enabling he-ipv6 interface...                                                                                                                         [ OK ] 
 * bringing up IPv6 tunnel...                                                                                                                            [ OK ] 
 * testing IPv6 tunnel (this may take a while)...                                                                                                        [ OK ] 
 * enabling DNS recursion...                                                                                                                             [ OK ] 
 * authorising clientip=1.2.3.4 on iface=eth0...                                                                                                  [ OK ] 
 * adding IPv4 iptables rules...                                                                                                                         [ OK ] 
 * creating Docker and sniproxy configuration templates...                                                                                               [ OK ] 
 * checking IPv6 connectivity...                                                                                                                                 
 * enabling sniproxy IPv6 priority...                                                                                                                    [ OK ] 
 * installing sipcalc...                                                                                                                                 [ OK ] 
 * enabling Docker IPv6 dual-stack support with fixed-cidr-v6=1:2:3:4::/64...                                                                  [ OK ] 
 * adding IPv6 iptables rules...                                                                                                                         [ OK ] 
 * installing iptables|netfilter-persistent service...                                                                                                   [ OK ] 
 * socialising Docker with iptables-persistent service...                                                                                                [ OK ] 
 * updating iptables-persistent init script...                                                                                                           [ OK ] 
 * saving iptables rules...                                                                                                                              [ OK ] 
 * creating zones.override from template...                                                                                                              [ OK ] 
 * updating db.override with extip=2.3.4.5 and date=20160427...                                                                                   [ OK ] 
 * installing python-pip and docker-compose...                                                                                                           [ OK ] 
 * configuring netflix-proxy-admin backend...                                                                                                            [ OK ] 
 * configuring netflix-proxy-admin reverse-proxy...                                                                                                      [ OK ] 
 * creating and starting Docker containers...                                                                                                            [ OK ] 
 * configuring upstart...                                                                                                                                [ OK ] 
 * reloading ipables rules...                                                                                                                            [ OK ] 
 * no specific steps to execute for Ubuntu at this time...                                                                                               [ OK ] 
 * testing DNS...                                                                                                                                        [ OK ] 
 * testing proxy (OpenSSL)...                                                                                                                                   
root@docker:/opt/netflix-proxy# 
`
