### ISSUE TITLE
Ios App and apple TV

### ISSUE THREAD

**Issue by lesnox** [ab77/netflix-proxy#89]
Hello, 

i have tested the new thing on ios app of Netflix and doesn't work :( have you an idea for ios or apple TV app ? ;)

best regard.

Lesnox

**Comment by ab77** [comment]
New thing? Please be more specific..

**Comment by lesnox** [comment]
just netflix detect i'm not in the usa

**Comment by lesnox** [comment]
just netflix say i use a proxy or VPN ? i don't know how it's possible ?

**Comment by ab77** [comment]
Then you fat-fingered something. Go back to basics and check everything. For example, test with a browser first.

**Comment by lesnox** [comment]
Ok i tested that in this afternon ;) and make a message with result after ;)
