### ISSUE TITLE
using vpn(or ssh, shadowsocks) instead of changing dns on my client

### ISSUE THREAD

**Issue by radowitz** [ab77/netflix-proxy#90]
It works well using your solutions to watch Netflix. But there was troubles by pointing the DNS at my VPS IP because it proxy all my requests.
Is there any solution not using DNS proxy? Maybe using VPN(PPTP, L2TP) of Shadowsocks? Just let my VPS automatically using IPv6 to Netflix?

what i need:
 client(using VPN,SSH or Shadowsocks) ------------**vps**-----------automatically ipv6---------netflix

**Comment by ab77** [comment]
`netflix-proxy` should only proxy the requests for domains which are in `zones.override` file.

A VPN will essentially `proxy` **everything**, unless you disable default route and selectively route IPs/nets through your VPS. This will get very boring, very quickly.

So I am not sure I follow your logic..

-- ab1
