### ISSUE TITLE
Apple TV - Netflix works, Hulu gets GeoBlock Message

### ISSUE THREAD

**Issue by i37** [ab77/netflix-proxy#91]
So i've got my VM and docker up and running - Success! 

Websites resolve, I've added whatismyip.com to my db.override and my IP comes up.

I can access Netflix on Desktop and Apple TV - Success!

However I can only access Hulu on desktop, it fails on Apple TV with a Geoblocked message.

I have a VM with 1TB of IN+OUT traffic so i'm not concerned about data usage as I can just spin a second server up however I'm wondering if there's a new DNS zone require for Hulu on apple tv?

**Comment by ab77** [comment]
From memory, when I was testing Hulu on ATV, they do some kind of additional checks in that specific app. I could work out if there was another domain or if they are using an Apple API to obtain a more accurate geo location (i.e. using Wi-Fi).

Have you tried loading it on your iPhone or iPad (assuming you have one) and AirPlaying to ATV instead?

Not sure if Hulu Android/iOS app has Google Chromecast support, but if it does, might be worth trying that too, given the devices are so cheap..

-- ab1

**Comment by i37** [comment]
That's a shame. They are really trying harder then netflix. I also added level3.net to my DNS zone too because it appears they are using them for CDN.

I will try it on the Hulu app too and see if I can airplay to it or look at Chromecast...
