### ISSUE TITLE
Install on Digital Ocean Docker 1.x Ubuntu fails

### ISSUE THREAD

**Issue by securityguy** [ab77/netflix-proxy#93]
root@ny:~# git clone https://github.com/ab77/netflix-proxy /opt/netflix-proxy && cd /opt/netflix-proxy && ./build.sh
Cloning into '/opt/netflix-proxy'...
remote: Counting objects: 1217, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 1217 (delta 6), reused 0 (delta 0), pack-reused 1200
Receiving objects: 100% (1217/1217), 642.38 KiB | 0 bytes/s, done.
Resolving deltas: 100% (684/684), done.
Checking connectivity... done.
clientip= ipaddr=<redacted>
10.17.0.5 extip=<redacted> -r=1 -b=0 -i=0 -d=0
WARNING: enabling DNS recursion...
		allow-recursion { trusted; };
		recursion yes;
		additional-from-auth yes;
		additional-from-cache yes;
/opt/netflix-proxy /opt/netflix-proxy
adding IPv4 iptables rules..
iptables v1.4.21: host/network `' not found
Try `iptables -h' or 'iptables --help' for more information.

Re-running results in:

WARNING: enabling DNS recursion...
		allow-recursion { trusted; };
		recursion yes;
		additional-from-auth yes;
		additional-from-cache yes;
/opt/netflix-proxy /opt/netflix-proxy
adding IPv4 iptables rules..
iptables: Chain already exists.

Proxy does not appear to be listening:

root@ny:~# netstat -a | grep -i listen
tcp        0      0 *:ssh                   *:*                     LISTEN     
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN

**Comment by misto1234** [comment]
having same issue..  should it look like : git clone https://github.com/ab77/netflix-proxy /opt/netflix-proxy && cd /opt/netflix-proxy && ./build.sh  -c xx.xxx.xxx.xx 

??

**Comment by ab77** [comment]
On DO, try: 
```
git clone -b new-auth https://github.com/ab77/netflix-proxy /opt/netflix-proxy && cd /opt/netflix-proxy && ./build.sh -c 123.123.123.123
```

Then, look through the steps in the [wiki](https://github.com/ab77/netflix-proxy/wiki), especially the part about logging off, clearing cookies, etc.

-- ab1
