### ISSUE TITLE
Works on every device in the house except my Android phone

### ISSUE THREAD

**Issue by ojlab** [ab77/netflix-proxy#95]
I've got this working all over the house, thanks for making this. 

- iPhone
- Chromecast
- PC 
- Mac

I've added the nflxvideo.net. zone and blocked all Google DNS ports on my router. 

It used to work perfectly on my Android phone, but it doesn't anymore. It says things like 
"Please make sure that your device has network connectivity and the date and time settings are accurate (-3)" 

I've rebooted, logout and reinstalled, but nothing seems to work. Any idea's on what to try next?

**Comment by ab77** [comment]
So the Android device definitely supports SNI? You can check by loading https://sni.velox.ch/ in its browser..

-- ab1

**Comment by ojlab** [comment]
Interesting, thanks for getting back to me. It says 'not implemented', I figured this wouldn't be an issue, with it being a newer Android phone. Is SNI unsupported on all Android devices?

**Comment by ab77** [comment]
Can you run a packet sniffer to see what the device is actually doing?

**Comment by ojlab** [comment]
I packetsniffed and got a pcap flie into wireshark with my Android wifi traffic. I see a bunch of calls to android.nccp.netflix.com but other than that, I have no idea what I'm looking for.

**Comment by ab77** [comment]
Filter by `tcp port 53 or udp port 53` and see what DNS requests it is making and to where..

**Comment by ojlab** [comment]
Very interesting all this! 

I see a call to android.cnnp.netflix.com, a destination of 8.8.8.8 followed by a "destination not reachable".

Now, last weekend I did changed the routing in the router to block 8.8.8.8 and 8.8.4.4 so that my Chromecast would work with the proxy. I guess that this means that the Android app won't work with that rule in place.

**Comment by ab77** [comment]
Well, it should fall back to system assigned DNS server if it can't reach Google's.. What do you have configured as the DNS server on the device?

**Comment by ojlab** [comment]
The DNS server is set to my netflix-proxy at Digital Ocean. I think I should try to allow 8.8.8.8 but have it redirect to my Digital Ocean or something?

**Comment by ojlab** [comment]
Alright! Found it. I opened up the 8.8.8.8 port on the router, but blocked it only for the Chromecast, using the firewall. Now everything works. Thanks!

**Comment by ab77** [comment]
Good stuff!
