### ISSUE TITLE
Issue with install on RamNode

### ISSUE THREAD

**Issue by haniag** [ab77/netflix-proxy#96]
I installed the solution like how it is stated in instructions, and I tested it where it was working great. However, I tried to connect using it the next day, and the connection is not working for any internet connection (not just Netflix, etc...). From VPS control panel, the server is online and IP address didn't change. I can also SSH, and I received the following from docker ps:

```
CONTAINER ID | IMAGE | COMMAND | CREATED | STATUS | PORTS | NAMES
a4867ca8302b | ab77/sniproxy | "/usr/sbin/sniproxy -" | 15 hours ago | Up 2 minutes  |    | sniproxy
64053662b27e | ab77/bind | "/usr/sbin/named -u n" | 15 hours ago | Up 2 minutes |    | bind
```

Is it ok that ports is empty? I also tried service docker restart, but nothing changed. Can someone please help me in troubleshooting this?

**Comment by ab77** [comment]
Can you please try rebuild with the new version..
https://github.com/ab77/netflix-proxy/tree/new-auth

-- ab1

**Comment by haniag** [comment]
hmm, not sure how to do that. Should I create a new VPS, and in step 4 (under RamNode), should I use "/netflix-proxy/tree/new-auth" instead of "/netflix-proxy"?

**Comment by ab77** [comment]
Just create a new server and follow the instructions in the [README](https://github.com/ab77/netflix-proxy/blob/new-auth/README.md).

-- ab1

**Comment by haniag** [comment]
Same issue, and I can ping server fine. However, docker ps now shows ports:

CONTAINER ID | IMAGE | COMMAND | CREATED | STATUS | PORTS | NAMES
ce528208d10f | ab77/sniproxy:new-auth | "/bin/sh -c /opt/snip" | 6 hours ago | Up 21 seconds | 0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp | sniproxy
8471af07c717 | andyshinn/dnsmasq | "dnsmasq -k --log-fac" | 6 hours ago | Up 21 seconds | 53/tcp, 53/udp | caching-resolver
4bc0d0393f0e | andyshinn/dnsmasq | "dnsmasq -k --port=53" | 6 hours ago | Up 21 seconds | 53/tcp, 53/udp, 0.0.0.0:5353->5353/tcp, 0.0.0.0:5353->5353/udp | dnsmasq
245c9ab40da6 | ab77/bind:new-auth | "/usr/sbin/named -u n" | 6 hours ago | Up 21 seconds | 0.0.0.0:53->53/udp | bind
8b689aa67b7c | abiosoft/caddy | "/usr/bin/caddy --con" | 6 hours ago | Up 21 seconds | caddy

Could this be related to RamNode?

**Comment by ab77** [comment]
Can a look at the `/var/log/upstart/netflix-proxy-admin.log` right after you get the HTTP 500. There must be a bug in the auth code due to something I haven't anticipated..

**Comment by Projectnsb** [comment]
I have the same issue with the new-auth (RamNode). I can connect to every site but when i try to open netflix, i wont work.
The site is with the dns not reachable.

**Comment by haniag** [comment]
Here it is. I removed IP address:

127.0.0.1:59021 - - [17/Mar/2016 09:12:23] "HTTP/1.1 GET /add" - 303 See Other
Traceback (most recent call last):
  File "./auth.py", line 301, in GET
    if session.user:
  File "/usr/local/lib/python2.7/dist-packages/web/session.py", line 71, in __getattr__
    return getattr(self._data, name)
AttributeError: 'ThreadedDict' object has no attribute 'user'
None
127.0.0.1:59021 - - [17/Mar/2016 09:12:23] "HTTP/1.1 GET /login" - 200 OK
127.0.0.1:59023 - - [17/Mar/2016 09:50:15] "HTTP/1.1 GET /" - 303 See Other
127.0.0.1:59023 - - [17/Mar/2016 09:50:15] "HTTP/1.1 GET /add" - 200 OK
u'Authorising ipaddr=XXX.XXX.171.78'
"DEBUG: getting public iface name cmd=ip route | grep default | awk '{print $5}'"
"DEBUG: get_iface()=[0, '', 'eth0\\n']"
'DEBUG: public iface=eth0'
u'DEBUG: ipaddr=XXX.XXX.171.78, op=I, ipt_cmd=iptables -t nat -I PREROUTING -s XXX.XXX.171.78/32 -i eth0 -j ACCEPT -v && iptables-save > /etc/iptables/rule$
"iptables_update: [(0, '', 'ACCEPT  all opt -- in eth0 out *  XXX.XXX.171.78  -> 0.0.0.0/0  \\n')]"
u'DEBUG: ipaddr=XXX.XXX.171.78, op=I, ipt_cmd=iptables -t nat -I PREROUTING -s XXX.XXX.171.78/32 -i eth0 -j ACCEPT -v && iptables-save > /etc/iptables/rule$
"iptables_update: [(0, '', 'ACCEPT  all opt -- in eth0 out *  XXX.XXX.171.78  -> 0.0.0.0/0  \\n')]"
'db.insert: 3'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 239, in process
    return self.handle()
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "./auth.py", line 105, in decorated
    return f(*args, **kwargs)
  File "./auth.py", line 383, in POST
    if is_redirected():
  File "./auth.py", line 82, in is_redirected
    fqdn = get_server_public_fqdn()
  File "./auth.py", line 73, in get_server_public_fqdn
    return str(reslvr.query(ipaddr, 'PTR')[0]).rstrip('.').lower()
  File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 910, in query
    raise NXDOMAIN
NXDOMAIN

127.0.0.1:59023 - - [17/Mar/2016 09:50:23] "HTTP/1.1 POST /add" - 500 Internal Server Error

**Comment by ab77** [comment]
I've fixed the HTTP 500 error, try re-deploying..

**Comment by ab77** [comment]
OK, I've fixed HTTP 500 issue and made some more changes to networking.. See if that resolves it for you.

**Comment by haniag** [comment]
Yes, that error is fixed, but I am still unable to open Netflix. In Firefox, I get: "Secure Connection Failed" on https://www.netflix.com, and I have netflix.com and nflxvideo.net added in zones.override

What's also interesting is that sites like Pandora open and I can log in, but it won't stream any music afterwards. However, not sure if this is related to security, as I can open Gmail fine.

**Comment by ab77** [comment]
OK, try running on your PC: `curl -H "host: netflix.com" x.x.x.x -v -L` replace with VPS IP..

**Comment by haniag** [comment]
Thanks, as your help is very appreciated. Here's the result:
    rMBP:~ User$ curl -H "host: netflix.com" XXX.XXX.100.77 -v -L
    * Rebuilt URL to: XXX.XXX.100.77/
    *   Trying XXX.XXX.100.77...
    * Connected to XXX.XXX.100.77 (XXX.XXX.100.77) port 80 (#0)
    > GET / HTTP/1.1
    > host: netflix.com
    > User-Agent: curl/7.43.0
    > Accept: */*
    > 
    < HTTP/1.1 301 Moved Permanently
    < Cache-Control: no-cache, no-store
    < Date: Thu, 17 Mar 2016 18:14:31 GMT
    < Edge-Control: no-cache, no-store
    < Location: https://www.netflix.com/
    < Server: wwwservice i-289760fc
    < Set-Cookie: nflx-rgn=ue1|1458238472339; Max-Age=-1; Expires=Thu, 17 Mar 2016 18:14:31 GMT; Path=/; Domain=.netflix.com
    < Set-Cookie: memclid=d5f395f9-b641-466a-beb1-96d0343f11f8; Max-Age=31536000; Expires=Fri, 17 Mar 2017 18:14:32 GMT; Path=/; Domain=.netflix.com
    < Strict-Transport-Security: max-age=0; includeSubDomains
    < Via: 1.1 i-408dc8c4 (us-east-1)
    < X-Content-Type-Options: nosniff
    < X-Netflix-From-Zuul: true
    < X-Netflix.nfstatus: 1_1
    < X-Originating-URL: http://netflix.com/
    < X-Xss-Protection: 1; mode=block; report=https://ichnaea.netflix.com/log/freeform/xssreport
    < Content-Length: 0
    < Connection: keep-alive
    < 
    * Connection #0 to host XXX.XXX.100.77 left intact
    * Issue another request to this URL: 'https://www.netflix.com/'
    *   Trying XXX.XXX.100.77...
    * Connected to www.netflix.com (XXX.XXX.100.77) port 443 (#1)
    * Server aborted the SSL handshake
    * Closing connection 1
    curl: (35) Server aborted the SSL handshake

**Comment by ab77** [comment]
Can you try on DigitalOcean?

**Comment by ab77** [comment]
I've added some exception handling to the new version - try deploying on a fresh re-install and see what it says at the end (about IPv6).

**Comment by ab77** [comment]
Anyway, I turned off `caching-resolver` feature, which means it should now work on all providers. Try re-building..

**Comment by ab77** [comment]
Let me know if you hit the same issue after the rebuild. I'll close in the mean time..
