### ISSUE TITLE
Error 500 on auth page

### ISSUE THREAD

**Issue by kyle95wm** [ab77/netflix-proxy#97]
I get error 500 when adding/removing IP's

**Comment by ab77** [comment]
Can a look at the `/var/log/upstart/netflix-proxy-admin.log` right after you get the HTTP 500. There must be a bug in the auth code due to something I haven't anticipated..

**Comment by kyle95wm** [comment]
no such file or directory according to cat

**Comment by kyle95wm** [comment]
okay, here ya go! 1 month it will expire: http://pastebin.com/yBj9WPcn

**Comment by ab77** [comment]
Well, HTTP 500 should be fixed now. Try re-deploying..

**Comment by kyle95wm** [comment]
Will do at my earliest convenience

**Comment by ab77** [comment]
I am going to close this as the HTTP 500 has been resolved and we can continue troubleshooting the build in the other thread.
