### ISSUE TITLE
Netflix not loading after re-build

### ISSUE THREAD

**Issue by kyle95wm** [ab77/netflix-proxy#98]
I just rebuild my server (used a second droplet) and Netflix wouldnt load. It's just sitting there.

Every other website loads fine. My old build works just fine

**Comment by Projectnsb** [comment]
I have the same prob. with ramnode

**Comment by ab77** [comment]
Is this with the `new-auth` version or the old one?

If it is the new one, I've added some IPv6 exception handling, perhaps give it a fresh deploy and see what it says at the end..

**Comment by ab77** [comment]
Anyway, I turned off `caching-resolver` feature, which means it should now work on all providers. Try re-building..

**Comment by kyle95wm** [comment]
It works! Thanks!
