### ISSUE TITLE
Error: an inet address is expected rather than ":2".

### ISSUE THREAD

**Issue by OEmGee** [ab77/netflix-proxy#99]
Script always stops working here.

Creating and starting Docker containers
caddy is up-to-date
bind is up-to-date
dnsmasq is up-to-date
caching-resolver is up-to-date
sniproxy is up-to-date
docker stop/waiting
docker start/running, process 30608
netflix-proxy-admin start/running, process 30629
Restarting Docker containers and updating IPv6 NDP info
Restarting sniproxy ... done
Restarting caching-resolver ... done
Restarting dnsmasq ... done
Restarting bind ... done
Restarting caddy ... done
xargs: sipcalc: No such file or directory
xargs: sipcalc: No such file or directory
add: proxy :2 dev eth0
Error: an inet address is expected rather than ":2".
add: proxy :3 dev eth0
Error: an inet address is expected rather than ":3".
add: proxy :4 dev eth0
Error: an inet address is expected rather than ":4".
add: proxy :5 dev eth0
Error: an inet address is expected rather than ":5".
add: proxy :6 dev eth0
Error: an inet address is expected rather than ":6".
add: proxy :7 dev eth0
Error: an inet address is expected rather than ":7".
add: proxy :8 dev eth0
Error: an inet address is expected rather than ":8".

**Comment by ab77** [comment]
Are you enabling IPv6 support on the host? What does `ifconfig docker0` and `ifconfig eth0` output?

**Comment by ab77** [comment]
Anyway, I turned off `caching-resolver` feature, which means it should now work on all providers. Try re-building..

**Comment by OEmGee** [comment]
Seems to work fine now. Thanks.

**Comment by ab77** [comment]
Good stuff.
